import os
import logging
from typing import Optional, List, Any

logger = logging.getLogger(__name__)


def build_alert_email_html(project: Any, prediction: Any) -> str:
    """
    Builds a formatted HTML email body for risk escalation alerts.
    Includes project details, risk tier change, and top 3 SHAP drivers.
    """
    frontend_url = os.getenv("FRONTEND_URL", "http://localhost:3000")
    project_url = f"{frontend_url}/projects/{project.id}"
    
    new_tier = prediction.risk_tier.upper()
    tier_color = {
        "CRITICAL": "#f43f5e",
        "HIGH": "#f59e0b",
        "MEDIUM": "#3b82f6",
        "LOW": "#10b981",
    }.get(new_tier, "#64748b")

    # Top 3 SHAP drivers
    shap_rows = ""
    shap_values = prediction.shap_values or []
    if isinstance(shap_values, list):
        for sv in shap_values[:3]:
            if isinstance(sv, dict):
                label = sv.get("label", sv.get("feature", ""))
                val = sv.get("value", 0)
                direction = sv.get("direction", "positive")
                icon = "🔴" if direction == "positive" else "🟢"
                sign = "+" if direction == "positive" else "-"
                shap_rows += f"<li style='margin:6px 0;'>{icon} {sign}{abs(float(val)):.0%} — {label}</li>"

    return f"""
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: Arial, sans-serif; background: #f8fafc; padding: 24px; color: #1e293b;">
  <div style="max-width: 600px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; border: 1px solid #e2e8f0;">
    
    <!-- Header -->
    <div style="background: {tier_color}; padding: 20px 24px;">
      <h1 style="margin: 0; color: white; font-size: 18px;">⚠️ Risk Escalation Alert</h1>
      <p style="margin: 4px 0 0; color: rgba(255,255,255,0.9); font-size: 14px;">PRISM Infrastructure Risk Intelligence Platform</p>
    </div>

    <!-- Body -->
    <div style="padding: 24px;">
      <h2 style="margin: 0 0 4px; font-size: 20px;">{project.project_name}</h2>
      <p style="margin: 0 0 20px; color: #64748b;">{project.ministry} · {project.sector} · {project.state}</p>

      <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
        <tr>
          <td style="padding: 8px 12px; background: #f8fafc; border: 1px solid #e2e8f0; font-weight: 600;">Risk Tier</td>
          <td style="padding: 8px 12px; border: 1px solid #e2e8f0;">
            <span style="background: {tier_color}; color: white; padding: 2px 10px; border-radius: 9999px; font-size: 13px; font-weight: 600;">{new_tier}</span>
          </td>
        </tr>
        <tr>
          <td style="padding: 8px 12px; background: #f8fafc; border: 1px solid #e2e8f0; font-weight: 600;">Composite Score</td>
          <td style="padding: 8px 12px; border: 1px solid #e2e8f0;">{prediction.composite_risk_score:.2f} / 1.00</td>
        </tr>
        <tr>
          <td style="padding: 8px 12px; background: #f8fafc; border: 1px solid #e2e8f0; font-weight: 600;">Delay Probability</td>
          <td style="padding: 8px 12px; border: 1px solid #e2e8f0;">{prediction.delay_probability:.0%}</td>
        </tr>
        <tr>
          <td style="padding: 8px 12px; background: #f8fafc; border: 1px solid #e2e8f0; font-weight: 600;">Cost Overrun Risk</td>
          <td style="padding: 8px 12px; border: 1px solid #e2e8f0;">{prediction.cost_overrun_probability:.0%}</td>
        </tr>
        <tr>
          <td style="padding: 8px 12px; background: #f8fafc; border: 1px solid #e2e8f0; font-weight: 600;">Revised Cost</td>
          <td style="padding: 8px 12px; border: 1px solid #e2e8f0;">₹{getattr(project, 'revised_cost_cr', 0) or getattr(project, 'original_cost_cr', 0):.1f} Cr</td>
        </tr>
      </table>

      <h3 style="margin: 0 0 8px; font-size: 15px; color: #374151;">Top AI Risk Drivers (SHAP)</h3>
      <ul style="margin: 0 0 20px; padding-left: 20px; color: #374151; font-size: 14px; line-height: 1.6;">
        {shap_rows if shap_rows else "<li>Run a prediction to see SHAP drivers</li>"}
      </ul>

      <a href="{project_url}" style="display: inline-block; background: #0f172a; color: white; padding: 10px 20px; border-radius: 6px; text-decoration: none; font-weight: 600; font-size: 14px;">
        View Project Details →
      </a>
    </div>

    <!-- Footer -->
    <div style="padding: 16px 24px; background: #f8fafc; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8;">
      Generated by PRISM Infrastructure Risk Intelligence Platform &middot; {new_tier} Alert
    </div>
  </div>
</body>
</html>
"""


def send_escalation_email(project: Any, prediction: Any, previous_tier: Optional[str]) -> bool:
    """
    Sends an escalation email via Resend API when risk tier increases to HIGH or CRITICAL.
    Returns True if email was sent successfully, False otherwise.
    """
    resend_api_key = os.getenv("RESEND_API_KEY", "")
    recipient = os.getenv("ALERT_EMAIL_RECIPIENT", "officer@prism.gov.in")
    
    if not resend_api_key or resend_api_key.startswith("re_xxx"):
        logger.info("Resend API key not configured — skipping email dispatch")
        return False

    try:
        import resend
        resend.api_key = resend_api_key
        
        new_tier = prediction.risk_tier.upper()
        prev = previous_tier.upper() if previous_tier else "INITIAL"
        
        resend.Emails.send({
            "from": "alerts@prism-risk.gov.in",
            "to": [recipient],
            "subject": f"⚠️ Risk Escalation: {project.project_name} — {prev} → {new_tier}",
            "html": build_alert_email_html(project, prediction),
        })
        logger.info("Escalation email sent for project %s (%s → %s)", project.project_name, prev, new_tier)
        return True
    except Exception as e:
        logger.warning("Failed to send escalation email: %s", e)
        return False
