"use client";
import { useState, useEffect } from "react";
import type { Project, RiskPrediction, StructuredMitigationPlan, MitigationPlanResponse } from "@/lib/types";
import { generateMitigationPlan, downloadMitigationPdf } from "@/lib/api";

interface Props {
  project: Project;
  prediction: RiskPrediction | null;
}

const PROGRESS_STEPS = [
  "Gathering project risk context & asset parameters...",
  "Analyzing XGBoost predictive risk scores...",
  "Extracting live SHAP feature contributions...",
  "Qwen 2.5 generating project-specific mitigation strategy...",
  "Running Multi-LLM validation & factual consistency check...",
  "Finalizing structured government mitigation plan...",
];

export default function StructuredMitigationSection({ project, prediction }: Props) {
  const [plan, setPlan] = useState<StructuredMitigationPlan | null>(null);
  const [modelUsed, setModelUsed] = useState<string>("Qwen 2.5 (Primary) + Multi-LLM Validation");
  const [valModels, setValModels] = useState<string[]>([]);
  const [loading, setLoading] = useState<boolean>(false);
  const [progressStep, setProgressStep] = useState<number>(0);
  const [error, setError] = useState<string>("");
  const [activeTab, setActiveTab] = useState<"immediate" | "short" | "medium" | "monitoring" | "escalation">("immediate");
  const [pdfDownloading, setPdfDownloading] = useState<boolean>(false);

  // Auto-load cached plan on mount
  useEffect(() => {
    if (!project?.id) return;
    generateMitigationPlan(project.id, false)
      .then((res: MitigationPlanResponse) => {
        if (res?.plan) {
          setPlan(res.plan);
          setModelUsed(res.model || "Qwen 2.5 (Primary) + Multi-LLM Validation");
          setValModels(res.validation_models || []);
        }
      })
      .catch((err) => {
        console.warn("Cached mitigation plan check skipped", err);
      });
  }, [project?.id]);

  async function handleGenerate(force = false) {
    if (!project?.id || loading) return;
    setLoading(true);
    setError("");
    setProgressStep(0);

    // Progress step interval animation
    const interval = setInterval(() => {
      setProgressStep((prev) => (prev < PROGRESS_STEPS.length - 1 ? prev + 1 : prev));
    }, 450);

    try {
      const res = await generateMitigationPlan(project.id, force);
      if (res?.plan) {
        setPlan(res.plan);
        setModelUsed(res.model || "Qwen 2.5 (Primary) + Multi-LLM Validation");
        setValModels(res.validation_models || []);
      } else {
        throw new Error("Invalid mitigation plan response from AI service.");
      }
    } catch (e: any) {
      setError(e?.message || "AI generation temporarily unavailable. Please retry.");
    } finally {
      clearInterval(interval);
      setLoading(false);
    }
  }

  async function handleDownloadPdf() {
    if (!project?.id || !plan || pdfDownloading) return;
    setPdfDownloading(true);
    try {
      const blob = await downloadMitigationPdf(project.id, plan, modelUsed);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `PRISM_Mitigation_Plan_${plan.project_summary.project_id || project.id}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (e) {
      console.error("PDF download error:", e);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setPdfDownloading(false);
    }
  }

  return (
    <div className="card animate-fade" style={{ marginBottom: 24, background: "var(--surface)" }}>
      {/* Header Bar */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16, flexWrap: "wrap", gap: 12 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}>
          <div
            style={{
              width: 22, height: 22, borderRadius: 6, overflow: "hidden", flexShrink: 0,
              border: "1px solid var(--accent-glow)",
            }}
          >
            <img src="/logo.jpg" alt="PRISM AI" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
          </div>
          <span style={{ fontSize: 13, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.06em", color: "var(--accent)" }}>
            AI-Powered Infrastructure Mitigation Plan
          </span>
          {plan && (
            <span
              style={{
                fontSize: 10,
                padding: "2px 10px",
                background: "rgba(6, 182, 212, 0.12)",
                color: "var(--accent)",
                borderRadius: 9999,
                border: "1px solid rgba(6, 182, 212, 0.3)",
                fontWeight: 600,
              }}
            >
              Generated by: {modelUsed}
            </span>
          )}
        </div>

        {/* Buttons */}
        <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}>
          {plan && !loading && (
            <button
              onClick={handleDownloadPdf}
              disabled={pdfDownloading}
              className="btn btn-secondary animate-fade"
              style={{ fontSize: 12, padding: "7px 14px", display: "flex", alignItems: "center", gap: 6 }}
            >
              {pdfDownloading ? (
                <>
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" style={{ animation: "spin 1s linear infinite" }}>
                    <path d="M21 12a9 9 0 1 1-6.219-8.56"/>
                  </svg>
                  Rendering Government PDF...
                </>
              ) : (
                <>
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                    <polyline points="7 10 12 15 17 10"/>
                    <line x1="12" y1="15" x2="12" y2="3"/>
                  </svg>
                  Export Government PDF
                </>
              )}
            </button>
          )}

          <button
            onClick={() => handleGenerate(plan ? true : false)}
            disabled={loading}
            className="btn btn-primary"
            style={{ fontSize: 12, padding: "7px 16px", display: "flex", alignItems: "center", gap: 6 }}
          >
            {loading ? (
              <>
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" style={{ animation: "spin 1s linear infinite" }}>
                  <path d="M21 12a9 9 0 1 1-6.219-8.56"/>
                </svg>
                Synthesizing Multi-LLM Plan...
              </>
            ) : (
              <>
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>
                </svg>
                {plan ? "Regenerate AI Plan" : "Generate AI Mitigation Plan"}
              </>
            )}
          </button>
        </div>
      </div>

      {/* Loading Multi-Step Progress State */}
      {loading && (
        <div style={{ padding: "28px 20px", textAlign: "center", background: "var(--surface-2)", borderRadius: 10, border: "1px solid var(--border)" }}>
          <div style={{ fontSize: 13, fontWeight: 700, color: "var(--accent)", marginBottom: 6 }}>
            {PROGRESS_STEPS[progressStep]}
          </div>
          <div style={{ fontSize: 11, color: "var(--text-muted)", marginBottom: 14 }}>
            Step {progressStep + 1} of {PROGRESS_STEPS.length} · Processing real-time SHAP feature vectors and multi-LLM consensus
          </div>
          <div style={{ height: 5, background: "rgba(255,255,255,0.06)", borderRadius: 3, overflow: "hidden", maxWidth: 420, margin: "0 auto" }}>
            <div
              style={{
                height: "100%",
                width: `${((progressStep + 1) / PROGRESS_STEPS.length) * 100}%`,
                background: "linear-gradient(90deg, var(--accent) 0%, #a855f7 50%, #38bdf8 100%)",
                transition: "width 0.35s ease",
              }}
            />
          </div>
        </div>
      )}

      {/* Error State */}
      {error && !loading && (
        <div style={{ color: "#f43f5e", fontSize: 12, padding: "12px 16px", background: "rgba(244, 63, 94, 0.08)", borderRadius: 8, border: "1px solid rgba(244, 63, 94, 0.25)", display: "flex", alignItems: "center", gap: 8, marginBottom: 14 }}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#f43f5e" strokeWidth="2">
            <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/>
            <line x1="12" y1="9" x2="12" y2="13"/>
            <line x1="12" y1="17" x2="12.01" y2="17"/>
          </svg>
          {error}
        </div>
      )}

      {/* Plan Render */}
      {plan && !loading && (
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          {/* Executive Summary Rationale Box */}
          <div style={{ background: "rgba(6, 182, 212, 0.06)", borderLeft: "4px solid var(--accent)", borderRadius: "0 8px 8px 0", padding: "14px 18px", border: "1px solid rgba(6, 182, 212, 0.2)", borderLeftWidth: 4 }}>
            <div style={{ fontSize: 11, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--accent)", marginBottom: 6 }}>
              Executive Intelligence & Risk Rationale
            </div>
            <div style={{ fontSize: 12.5, color: "var(--text)", lineHeight: 1.65 }}>
              {plan.executive_summary}
            </div>
          </div>

          {/* Root-Cause Risk Assessment Cards */}
          {plan.risk_assessment && plan.risk_assessment.length > 0 && (
            <div>
              <div style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.06em", color: "var(--text-muted)", marginBottom: 8 }}>
                Root-Cause Risk Assessment (XGBoost + SHAP)
              </div>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: 10 }}>
                {plan.risk_assessment.map((r, i) => (
                  <div key={i} style={{ background: "var(--surface-2)", borderRadius: 8, padding: "12px 14px", border: "1px solid var(--border)" }}>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 }}>
                      <span style={{ fontSize: 12, fontWeight: 700, color: "var(--text)" }}>{r.risk}</span>
                      <span
                        style={{
                          fontSize: 10,
                          fontWeight: 700,
                          padding: "1px 6px",
                          borderRadius: 4,
                          background: r.severity.toLowerCase() === "critical" ? "rgba(244, 63, 94, 0.15)" : "rgba(245, 158, 11, 0.15)",
                          color: r.severity.toLowerCase() === "critical" ? "#f43f5e" : "#f59e0b",
                        }}
                      >
                        {r.severity}
                      </span>
                    </div>
                    <div style={{ fontSize: 11, color: "var(--text-sub)", lineHeight: 1.5, marginBottom: 6 }}>
                      <strong style={{ color: "var(--text)" }}>Root Cause:</strong> {r.root_cause}
                    </div>
                    {r.shap_factors && r.shap_factors.length > 0 && (
                      <div style={{ display: "flex", gap: 4, flexWrap: "wrap", marginTop: 4 }}>
                        {r.shap_factors.map((sf, j) => (
                          <span key={j} style={{ fontSize: 9.5, padding: "1px 6px", background: "rgba(56, 189, 248, 0.1)", color: "#38bdf8", borderRadius: 4, border: "1px solid rgba(56, 189, 248, 0.2)" }}>
                            SHAP: {sf}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Dynamic Tabs for Action Roadmap */}
          <div>
            <div style={{ display: "flex", gap: 6, borderBottom: "1px solid var(--border)", paddingBottom: 6, overflowX: "auto" }}>
              <button
                onClick={() => setActiveTab("immediate")}
                style={{
                  padding: "6px 12px",
                  borderRadius: 6,
                  fontSize: 11,
                  fontWeight: 700,
                  border: "none",
                  cursor: "pointer",
                  background: activeTab === "immediate" ? "var(--accent)" : "var(--surface-2)",
                  color: activeTab === "immediate" ? "#ffffff" : "var(--text-sub)",
                  transition: "all 0.15s ease",
                }}
              >
                Immediate Actions ({plan.immediate_actions?.length || 0})
              </button>
              <button
                onClick={() => setActiveTab("short")}
                style={{
                  padding: "6px 12px",
                  borderRadius: 6,
                  fontSize: 11,
                  fontWeight: 700,
                  border: "none",
                  cursor: "pointer",
                  background: activeTab === "short" ? "var(--accent)" : "var(--surface-2)",
                  color: activeTab === "short" ? "#ffffff" : "var(--text-sub)",
                  transition: "all 0.15s ease",
                }}
              >
                Phase 2: Acceleration ({plan.short_term_actions?.length || 0})
              </button>
              <button
                onClick={() => setActiveTab("medium")}
                style={{
                  padding: "6px 12px",
                  borderRadius: 6,
                  fontSize: 11,
                  fontWeight: 700,
                  border: "none",
                  cursor: "pointer",
                  background: activeTab === "medium" ? "var(--accent)" : "var(--surface-2)",
                  color: activeTab === "medium" ? "#ffffff" : "var(--text-sub)",
                  transition: "all 0.15s ease",
                }}
              >
                Phase 3: Handover ({plan.medium_term_actions?.length || 0})
              </button>
              <button
                onClick={() => setActiveTab("monitoring")}
                style={{
                  padding: "6px 12px",
                  borderRadius: 6,
                  fontSize: 11,
                  fontWeight: 700,
                  border: "none",
                  cursor: "pointer",
                  background: activeTab === "monitoring" ? "var(--accent)" : "var(--surface-2)",
                  color: activeTab === "monitoring" ? "#ffffff" : "var(--text-sub)",
                  transition: "all 0.15s ease",
                }}
              >
                Monitoring Plan ({plan.monitoring_plan?.length || 0})
              </button>
              <button
                onClick={() => setActiveTab("escalation")}
                style={{
                  padding: "6px 12px",
                  borderRadius: 6,
                  fontSize: 11,
                  fontWeight: 700,
                  border: "none",
                  cursor: "pointer",
                  background: activeTab === "escalation" ? "var(--accent)" : "var(--surface-2)",
                  color: activeTab === "escalation" ? "#ffffff" : "var(--text-sub)",
                  transition: "all 0.15s ease",
                }}
              >
                Escalation Triggers ({plan.escalation_plan?.length || 0})
              </button>
            </div>

            {/* Tab Contents */}
            <div style={{ marginTop: 12 }}>
              {activeTab === "immediate" && (
                <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
                  {plan.immediate_actions?.map((act, i) => (
                    <div key={i} style={{ background: "var(--surface-2)", borderRadius: 8, padding: "14px 16px", border: "1px solid var(--border)", display: "flex", gap: 12, alignItems: "flex-start" }}>
                      <span style={{ width: 26, height: 26, borderRadius: "50%", background: "#f43f5e", color: "white", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 800, flexShrink: 0 }}>
                        P{act.priority}
                      </span>
                      <div style={{ flex: 1 }}>
                        <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text)", marginBottom: 4 }}>
                          {act.action}
                        </div>
                        <div style={{ fontSize: 11.5, color: "var(--text-sub)", lineHeight: 1.5, marginBottom: 8 }}>
                          <strong style={{ color: "var(--text)" }}>Rationale:</strong> {act.reason}
                        </div>
                        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 8, background: "rgba(0,0,0,0.15)", padding: "8px 10px", borderRadius: 6, fontSize: 11 }}>
                          <div><span style={{ color: "var(--text-muted)" }}>Target Timeline:</span> <strong style={{ color: "var(--accent)" }}>{act.timeline}</strong></div>
                          <div><span style={{ color: "var(--text-muted)" }}>Responsible:</span> <strong style={{ color: "var(--text)" }}>{act.responsible_role}</strong></div>
                          <div><span style={{ color: "var(--text-muted)" }}>Expected Outcome:</span> <strong style={{ color: "#10b981" }}>{act.expected_outcome}</strong></div>
                          <div><span style={{ color: "var(--text-muted)" }}>Escalation:</span> <span style={{ color: "#f43f5e" }}>{act.escalation_condition}</span></div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {activeTab === "short" && (
                <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
                  {plan.short_term_actions?.map((act, i) => (
                    <div key={i} style={{ background: "var(--surface-2)", borderRadius: 8, padding: "14px 16px", border: "1px solid var(--border)", display: "flex", gap: 12, alignItems: "flex-start" }}>
                      <span style={{ width: 26, height: 26, borderRadius: "50%", background: "#f59e0b", color: "white", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 800, flexShrink: 0 }}>
                        P{act.priority}
                      </span>
                      <div style={{ flex: 1 }}>
                        <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text)", marginBottom: 4 }}>
                          {act.action}
                        </div>
                        <div style={{ fontSize: 11.5, color: "var(--text-sub)", lineHeight: 1.5, marginBottom: 8 }}>
                          <strong style={{ color: "var(--text)" }}>Rationale:</strong> {act.reason}
                        </div>
                        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 8, background: "rgba(0,0,0,0.15)", padding: "8px 10px", borderRadius: 6, fontSize: 11 }}>
                          <div><span style={{ color: "var(--text-muted)" }}>Timeline:</span> <strong style={{ color: "var(--accent)" }}>{act.timeline}</strong></div>
                          <div><span style={{ color: "var(--text-muted)" }}>Responsible:</span> <strong style={{ color: "var(--text)" }}>{act.responsible_role}</strong></div>
                          <div><span style={{ color: "var(--text-muted)" }}>Outcome:</span> <strong style={{ color: "#10b981" }}>{act.expected_outcome}</strong></div>
                          <div><span style={{ color: "var(--text-muted)" }}>Trigger:</span> <span style={{ color: "#f59e0b" }}>{act.escalation_condition}</span></div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {activeTab === "medium" && (
                <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
                  {plan.medium_term_actions?.map((act, i) => (
                    <div key={i} style={{ background: "var(--surface-2)", borderRadius: 8, padding: "14px 16px", border: "1px solid var(--border)", display: "flex", gap: 12, alignItems: "flex-start" }}>
                      <span style={{ width: 26, height: 26, borderRadius: "50%", background: "#3b82f6", color: "white", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 800, flexShrink: 0 }}>
                        P{act.priority}
                      </span>
                      <div style={{ flex: 1 }}>
                        <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text)", marginBottom: 4 }}>
                          {act.action}
                        </div>
                        <div style={{ fontSize: 11.5, color: "var(--text-sub)", lineHeight: 1.5, marginBottom: 8 }}>
                          <strong style={{ color: "var(--text)" }}>Rationale:</strong> {act.reason}
                        </div>
                        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 8, background: "rgba(0,0,0,0.15)", padding: "8px 10px", borderRadius: 6, fontSize: 11 }}>
                          <div><span style={{ color: "var(--text-muted)" }}>Timeline:</span> <strong style={{ color: "var(--accent)" }}>{act.timeline}</strong></div>
                          <div><span style={{ color: "var(--text-muted)" }}>Responsible:</span> <strong style={{ color: "var(--text)" }}>{act.responsible_role}</strong></div>
                          <div><span style={{ color: "var(--text-muted)" }}>Outcome:</span> <strong style={{ color: "#10b981" }}>{act.expected_outcome}</strong></div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {activeTab === "monitoring" && (
                <div style={{ overflowX: "auto" }}>
                  <table className="data-table" style={{ width: "100%", fontSize: 11.5 }}>
                    <thead>
                      <tr>
                        <th>Monitoring Indicator</th>
                        <th>Current Baseline</th>
                        <th>Target Threshold</th>
                        <th>Cadence</th>
                        <th>Accountable Role</th>
                      </tr>
                    </thead>
                    <tbody>
                      {plan.monitoring_plan?.map((m, i) => (
                        <tr key={i}>
                          <td style={{ fontWeight: 600, color: "var(--text)" }}>{m.indicator}</td>
                          <td style={{ color: "var(--text-sub)" }}>{m.current_value}</td>
                          <td style={{ color: "#10b981", fontWeight: 700 }}>{m.target_value}</td>
                          <td><span style={{ background: "rgba(255,255,255,0.06)", padding: "2px 8px", borderRadius: 4 }}>{m.frequency}</span></td>
                          <td style={{ color: "var(--accent)" }}>{m.responsible_role}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}

              {activeTab === "escalation" && (
                <div style={{ overflowX: "auto" }}>
                  <table className="data-table" style={{ width: "100%", fontSize: 11.5 }}>
                    <thead>
                      <tr>
                        <th>Trigger Event</th>
                        <th>Variance Threshold</th>
                        <th>Escalate To</th>
                        <th>Recommended Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      {plan.escalation_plan?.map((e, i) => (
                        <tr key={i}>
                          <td style={{ fontWeight: 700, color: "#f43f5e" }}>{e.trigger}</td>
                          <td style={{ color: "var(--text)" }}>{e.threshold}</td>
                          <td style={{ color: "var(--accent)", fontWeight: 600 }}>{e.escalate_to}</td>
                          <td style={{ color: "var(--text-sub)" }}>{e.recommended_action}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Initial Call-to-action before first generation */}
      {!plan && !loading && !error && (
        <div style={{ padding: "28px 20px", textAlign: "center", color: "var(--text-muted)", fontSize: 13 }}>
          Click <strong style={{ color: "var(--accent)" }}>Generate AI Mitigation Plan</strong> to run Qwen 2.5 + Multi-LLM intelligence on live project SHAP drivers.
        </div>
      )}
    </div>
  );
}
