"""
scripts/expand_gazetteer_data.py
Enriches AUTHORITATIVE_GAZETTEER in scripts/india_authoritative_gazetteer.py
with 100% official district coverage and rich stretch/facility keywords across all Indian states.
"""
import sys, os

ADDITIONAL_DISTRICTS = {
    "GUJARAT": [
        {"district": "Amreli", "coords": (21.6032, 71.2221), "place": "Port Pipavav & Amreli Rail Corridor", "keywords": ["AMRELI", "PIPAVAV", "PORT PIPAVAV", "BADHADA", "BABRA", "DHARI", "RAJULA", "JAFRABAD", "SAVARKUNDLA"]},
        {"district": "Anand", "coords": (22.5645, 72.9289), "place": "Anand Milk City & Petlad Rail Corridor", "keywords": ["ANAND", "PETLAD", "BHADRAN", "KHAMBHAT", "VALLABH VIDYANAGAR", "BORSAD", "UMRETH", "ANAKLAV", "SOJITRA"]},
        {"district": "Aravalli", "coords": (23.5419, 73.1706), "place": "Modasa & Shamlaji Rail Corridor", "keywords": ["ARAVALLI", "MODASA", "SHAMLAJI", "BHILODA", "MALPUR", "MEGHRAJ", "BAYAD"]},
        {"district": "Botad", "coords": (22.1695, 71.6663), "place": "Botad Rail Junction & Highway", "keywords": ["BOTAD", "GADHADA", "BARWALA", "RANPUR"]},
        {"district": "Chhota Udaipur", "coords": (22.3089, 74.0131), "place": "Bodeli & Chhota Udaipur Highway", "keywords": ["CHHOTA UDAIPUR", "CHHOTA UDEPUR", "BODELI", "JABUGAM", "SANKHEDA", "JETPUR PAVI", "NASWADI", "DHAMASIYA", "BITADA", "MOVI"]},
        {"district": "Dahod", "coords": (22.8378, 74.2530), "place": "Dahod Locomotive & Greenfield Alignment", "keywords": ["DAHOD", "DOHAD", "GARBADA", "LIMKHEDA", "ZALOD", "FATEPURA", "DEVGADH BARIA", "CH.696", "PKG-26"]},
        {"district": "Dang", "coords": (20.8333, 73.7167), "place": "Ahwa & Saputara Tourism Node", "keywords": ["DANG", "DANGS", "AHWA", "SAPUTARA", "WAGHAI", "SUBIR"]},
        {"district": "Gir Somnath", "coords": (20.9042, 70.3667), "place": "Veraval Somnath & Kodinar Highway", "keywords": ["GIR SOMNATH", "VERAVAL", "SOMNATH", "KODINAR", "UNA", "KAGVADAR", "TALALA", "SUTRAPADA"]},
        {"district": "Kheda", "coords": (22.7533, 72.6844), "place": "Nadiad & Kheda Industrial Node", "keywords": ["KHEDA", "NADIAD", "KAPADVANJ", "MAHUDHA", "MATAR", "THASRA", "GALTESHWAR", "VASO"]},
        {"district": "Mahisagar", "coords": (23.1678, 73.5855), "place": "Lunawada & Santrampur Corridor", "keywords": ["MAHISAGAR", "LUNAWADA", "SANTRAMPUR", "BALASINOR", "VIRPUR", "KADANA"]},
        {"district": "Navsari", "coords": (20.9467, 72.9520), "place": "Navsari & Gandeva Highway Corridor", "keywords": ["NAVSARI", "GANDEVA", "BILIMORA", "JALALPORE", "CHIKHLI", "VANSDA", "GANDEVA TO ENA"]},
        {"district": "Panchmahal", "coords": (22.7758, 73.6149), "place": "Godhra & Halol Industrial Corridor", "keywords": ["PANCHMAHAL", "PANCHMAHALS", "GODHRA", "HALOL", "KALOL GUJARAT", "GHOGHAMBA", "SHEHRA", "MORVA HADAF", "CH.729", "CH.756", "PKG-27", "PKG-28", "TIMBA ROAD"]},
        {"district": "Porbandar", "coords": (21.6417, 69.6293), "place": "Porbandar Port & Coast Highway", "keywords": ["PORBANDAR", "RANAVAV", "KUTIYANA", "CHHAYA"]},
        {"district": "Surendranagar", "coords": (22.7275, 71.6370), "place": "Surendranagar & Wadhwan Node", "keywords": ["SURENDRANAGAR", "WADHWAN", "CHOTILA", "DHRANGADHRA", "LIMBDI", "PATDI", "SAYLA"]},
        {"district": "Tapi", "coords": (21.2333, 73.4333), "place": "Vyara & Ukai Dam Power Node", "keywords": ["TAPI", "VYARA", "UKAI", "SONGADH", "VALOD", "UCHCHHAL", "NIZAR"]},
        {"district": "Valsad", "coords": (20.5992, 72.9342), "place": "Valsad, Vapi & Expressway Corridor", "keywords": ["VALSAD", "VAPI", "JUJUWA", "KARVAD", "UMBERGAON", "PARDI", "DHARAMPUR", "KAPRADA", "TALSARI TO KARVAD", "JUJUWA - GANDEVA", "KARVAD - JUJUWA"]},
    ],
    "BIHAR": [
        {"district": "Kaimur", "coords": (25.0447, 83.6144), "place": "Mohania & Bhabua Highway Corridor", "keywords": ["KAIMUR", "BHABUA", "MOHANIA", "KUDRA", "CHAINPUR", "RAMGARH BIHAR"]},
        {"district": "Jamui", "coords": (24.9214, 86.2258), "place": "GMC Jamui & Rail Corridor", "keywords": ["JAMUI", "JHAJHA", "SONO", "CHAKAI", "SIKANDRA", "GMC JAMUI"]},
        {"district": "Jehanabad", "coords": (25.2156, 84.9867), "place": "Jehanabad & Makhdumpur Highway", "keywords": ["JEHANABAD", "MAKHDUMPUR", "GHOSI", "PATNA - GAYA -DOBHI PKG-II"]},
        {"district": "Arwal", "coords": (25.2442, 84.6739), "place": "Arwal Sone River Corridor", "keywords": ["ARWAL", "KURTHA", "KALER", "KARPI"]},
        {"district": "Aurangabad", "coords": (24.7533, 84.3739), "place": "Nabinagar Super Thermal Power Plant", "keywords": ["AURANGABAD", "NABINAGAR", "DAUDNAGAR", "OBRA", "BARUN", "RAFIGANJ"]},
        {"district": "Sitamarhi", "coords": (26.5939, 85.4914), "place": "Bairgania & Sitamarhi Rail Corridor", "keywords": ["SITAMARHI", "BAIRGANIA", "RUNNI SAIDPUR", "BELSAND", "PUPRI", "SURSAND"]},
        {"district": "Sheohar", "coords": (26.5167, 85.2917), "place": "Sheohar Highway Corridor", "keywords": ["SHEOHAR", "TARIYANI", "PIPRAHI", "DUMRI KATSARI", "CHORMA"]},
        {"district": "Supaul", "coords": (26.1247, 86.6047), "place": "Araria-Supaul Rail Line Project", "keywords": ["SUPAUL", "NIRMALI", "PIPRA", "TRIVENIGANJ", "CHHATAPUR", "RAGHOPUR"]},
        {"district": "Araria", "coords": (26.1508, 87.5208), "place": "Araria Rail Junction & Highway", "keywords": ["ARARIA", "FORBESGANJ", "JOKIHAT", "RANIGANJ"]},
        {"district": "Kishanganj", "coords": (26.0739, 87.9406), "place": "Kishanganj Border Corridor", "keywords": ["KISHANGANJ", "BAHADURGANJ", "THAKURGANJ", "POKHARIYA"]},
        {"district": "Khagaria", "coords": (25.5033, 86.4819), "place": "Khagaria-Kusheshwar Asthan Rail Link", "keywords": ["KHAGARIA", "KUSHESHWAR ASTHAN", "GOGRI", "BELDAUR", "ALAULI"]},
        {"district": "Saharsa", "coords": (25.8822, 86.5989), "place": "Saharsa Rail & Highway Node", "keywords": ["SAHARSA", "SIMRI BAKHTIARPUR", "MAHISHI", "SONBARSA"]},
        {"district": "Madhepura", "coords": (25.9222, 86.7919), "place": "Madhepura Electric Locomotive Factory", "keywords": ["MADHEPURA", "SINGHESHWAR", "MURLIGANJ", "ALAMNAGAR"]},
        {"district": "Banka", "coords": (24.8833, 86.9200), "place": "Banka Power & Rail Corridor", "keywords": ["BANKA", "AMARPUR", "BARAHAT", "BELHAR", "KATORIYA"]},
        {"district": "Munger", "coords": (25.3756, 86.4739), "place": "Munger Rail-cum-Road Ganga Bridge", "keywords": ["MUNGER", "MONGHYR", "JAMALPUR", "HAVELI KHARAGPUR"]},
        {"district": "Lakhisarai", "coords": (25.1783, 86.0944), "place": "Kiul Junction & Lakhisarai", "keywords": ["LAKHISARAI", "KIUL", "SURYAGARHA", "BARAHIYA"]},
        {"district": "Sheikhpura", "coords": (25.1389, 85.8611), "place": "Sheikhpura Highway Node", "keywords": ["SHEIKHPURA", "BARBIGHA", "ARIARI", "CHEWARA"]},
        {"district": "Nawada", "coords": (24.8878, 85.5433), "place": "Nawada & Rajauli Highway Node", "keywords": ["NAWADA", "RAJAULI", "WARISALIGANJ", "HISUA"]},
        {"district": "Samastipur", "coords": (25.8628, 85.7811), "place": "Samastipur Rail Division & Highway", "keywords": ["SAMASTIPUR", "DALSINGHSARAI", "ROSERA", "PUSA", "TAJPUR"]},
        {"district": "Gopalganj", "coords": (26.4678, 84.4444), "place": "Gopalganj & Thawe Junction", "keywords": ["GOPALGANJ", "THAWE", "MIRGANJ", "BARAULI"]},
        {"district": "Siwan", "coords": (26.2194, 84.3564), "place": "Siwan Junction & Highway Node", "keywords": ["SIWAN", "MAIRWA", "MAHARAJGANJ", "DARAUNDHA"]},
    ],
    "MADHYA PRADESH": [
        {"district": "Morena", "coords": (26.4948, 77.9940), "place": "Morena Ambah Porsa Bypass Corridor", "keywords": ["MORENA", "AMBAH", "PORSA", "JOURA", "SABALGARH", "KAILARAS", "MORENA BYPASS", "AMBAH BYPASS", "PORSA BYPASS"]},
        {"district": "Bhind", "coords": (26.5653, 78.7884), "place": "Bhind & Malanpur Industrial Area", "keywords": ["BHIND", "MALANPUR", "ATHO", "MEHGAON", "GOHAD", "LAHAR"]},
        {"district": "Sheopur", "coords": (25.6667, 76.7000), "place": "Sheopur Kuno Corridor", "keywords": ["SHEOPUR", "VIJAYPUR", "KARAHAL"]},
        {"district": "Shivpuri", "coords": (25.4244, 77.6565), "place": "Shivpuri Highway Corridor", "keywords": ["SHIVPURI", "KOLARAS", "POHARI", "KARERA", "NARWAR", "PICHHORE"]},
        {"district": "Guna", "coords": (24.6468, 77.3117), "place": "Guna & Raghogarh Industrial Area", "keywords": ["GUNA", "RAGHOGARH", "AARON", "CHACHOURA", "KUMBRAJ"]},
        {"district": "Ashoknagar", "coords": (24.5772, 77.7289), "place": "Chanderi & Mungaoli Highway Corridor", "keywords": ["ASHOKNAGAR", "ASHOK NAGAR", "CHANDERI", "MUNGAOLI", "ISAGARH", "KURWAIMUNGAOLICHANDERI"]},
        {"district": "Vidisha", "coords": (23.5251, 77.8081), "place": "Vidisha & Kurwai Highway Node", "keywords": ["VIDISHA", "KURWAI", "BASODA", "SIRONJ", "LATERI", "GYARASPUR"]},
        {"district": "Sehore", "coords": (23.2032, 77.0844), "place": "Budhni & Shahganj Industrial Corridor", "keywords": ["SEHORE", "BUDHNI", "SHAHGANJ", "ASHTA", "ICHHAWAR", "NASRULLAGANJ", "BHERUNDA", "BUDHNI TO SHAHGANJ"]},
        {"district": "Raisen", "coords": (23.3303, 77.7816), "place": "Mandideep & Badi Industrial Corridor", "keywords": ["RAISEN", "MANDIDEEP", "BADI", "SANCHI", "BARELI", "UDAIPURA", "SILWANI", "BEGUMGANJ", "SHAHGANJ BYPASS END TO BADI"]},
        {"district": "Rajgarh", "coords": (24.0064, 76.7303), "place": "Biaora & Rajgarh Highway Junction", "keywords": ["RAJGARH", "BIAORA", "SARANGPUR", "NARSINGHGARH", "KHILCHIPUR", "JIRAPUR"]},
        {"district": "Dewas", "coords": (22.9676, 76.0534), "place": "Dewas Industrial Area & Highway", "keywords": ["DEWAS", "TONK KHURD", "SONKATCH", "BAGLI", "KANNOD", "KHATEGAON", "NANASA"]},
        {"district": "Shajapur", "coords": (23.4267, 76.2778), "place": "Shajapur & Shujalpur Rail Corridor", "keywords": ["SHAJAPUR", "SHUJALPUR", "KALAPIPAL", "MOHAN BARODIA"]},
        {"district": "Agar Malwa", "coords": (23.7142, 76.0150), "place": "Agar Malwa Renewable Corridor", "keywords": ["AGAR MALWA", "AGAR", "SUSNER", "NALKHERA", "BADOD"]},
        {"district": "Ratlam", "coords": (23.3315, 75.0367), "place": "Ratlam Railway Junction & DFC", "keywords": ["RATLAM", "JAORA", "ALOT", "SAILANA", "PIPLODA"]},
        {"district": "Mandsaur", "coords": (24.0722, 75.0683), "place": "Mandsaur Solar & Highway Node", "keywords": ["MANDSAUR", "SUWASRA", "GAROTH", "SITAMAU", "MALHARGARH"]},
        {"district": "Neemuch", "coords": (24.4764, 74.8722), "place": "Neemuch Solar & Industrial Area", "keywords": ["NEEMUCH", "JAWAD", "MANASA", "SINGOLI"]},
        {"district": "Khargone", "coords": (21.8239, 75.6174), "place": "Khargone (West Nimar) & Balwara Corridor", "keywords": ["KHARGONE", "WEST NIMAR", "BALWARA", "BARWAHA", "SANAWAD", "KASRAWAD", "MAHESHWAR", "BHIKANGAON", "TEJAJINAGAR TO BALWARA"]},
        {"district": "Barwani", "coords": (22.0367, 74.9031), "place": "Barwani & Sendhwa Highway Corridor", "keywords": ["BARWANI", "SENDHWA", "ANJAD", "PANSEMAL", "RAJPUR MP"]},
        {"district": "Khandwa", "coords": (21.8242, 76.3508), "place": "Khandwa & Dhangaon Rail/Road Corridor", "keywords": ["KHANDWA", "EAST NIMAR", "DHANGAON", "PANDHANA", "PUNASA", "HARSUD", "BALWARA TO DHANGAON"]},
        {"district": "Burhanpur", "coords": (21.3144, 76.2294), "place": "Burhanpur & Borgaon Highway Corridor", "keywords": ["BURHANPUR", "BORGAON", "NEPANAGAR", "KHAKNAR", "DHANGAON - BORGAON", "BOREGAON"]},
        {"district": "Harda", "coords": (22.3444, 77.0964), "place": "Harda & Pidgaon Highway Corridor", "keywords": ["HARDA", "PIDGAON", "TIMARNI", "KHIRKIYA", "HANDIA", "NANASA TO PIDGAON"]},
        {"district": "Narmadapuram", "coords": (22.7511, 77.7289), "place": "Itarsi Railway Junction & Narmadapuram", "keywords": ["HOSHANGABAD", "NARMADAPURAM", "ITARSI", "PIPARIYA", "BABAI", "SEONI MALWA", "SOHAGPUR"]},
        {"district": "Betul", "coords": (21.9014, 77.9022), "place": "Betul & Multai Highway Corridor", "keywords": ["BETUL", "MULTAI", "SARNI", "AMLA", "BHAINSDEHI", "ATHNER"]},
        {"district": "Damoh", "coords": (23.8322, 79.4422), "place": "Damoh Cement & Highway Node", "keywords": ["DAMOH", "HATTA", "PATHARIA", "TENDUKHEDA", "JABERA"]},
        {"district": "Panna", "coords": (24.7214, 80.1856), "place": "Panna Diamond & Highway Node", "keywords": ["PANNA", "GUNOUR", "PAWAI", "SHAHNGAR", "AJAIGARH"]},
        {"district": "Chhatarpur", "coords": (24.9161, 79.5811), "place": "Khajuraho Airport & Chhatarpur Node", "keywords": ["CHHATARPUR", "KHAJURAHO", "NOWGONG", "RAJNAGAR", "BIJAWAR", "LAVKUSHNAGAR"]},
        {"district": "Tikamgarh", "coords": (24.7447, 78.8317), "place": "Tikamgarh Solar & Rail Node", "keywords": ["TIKAMGARH", "JATARA", "BALDEOGARH", "PALERA"]},
        {"district": "Niwari", "coords": (25.3583, 78.8000), "place": "Orchha Tourism & Niwari Corridor", "keywords": ["NIWARI", "ORCHHA", "PRITHVIPUR"]},
        {"district": "Shahdol", "coords": (23.2858, 81.3539), "place": "Shahdol & Sohagpur Coal Area", "keywords": ["SHAHDOL", "SOHAGPUR", "BURHAR", "BEOHARI", "JAITPUR"]},
        {"district": "Umaria", "coords": (23.5244, 80.8356), "place": "Umaria Coalfields & Bandhavgarh", "keywords": ["UMARIA", "NOWROZABAD", "BIRSINGHPUR", "MANPUR MP", "CHANDIA"]},
        {"district": "Anuppur", "coords": (23.1042, 81.6917), "place": "Amarkantak & Anuppur Thermal Power", "keywords": ["ANUPPUR", "AMARKANTAK", "KOTMA", "JAITHARI"]},
        {"district": "Dindori", "coords": (22.9467, 81.0811), "place": "Dindori Narmada Corridor", "keywords": ["DINDORI", "SHAHWALA", "BAJAG", "SAMNAPUR"]},
        {"district": "Mandla", "coords": (22.5975, 80.3714), "place": "Mandla Tribal & Highway Corridor", "keywords": ["MANDLA", "NAINPUR", "BICHHIYA", "NIWAS"]},
        {"district": "Balaghat", "coords": (21.8089, 80.1844), "place": "Balaghat Manganese & Copper Mines", "keywords": ["BALAGHAT", "MALANJKHAND", "WARASEONI", "KATANGI", "LANJI", "BAIHAR"]},
        {"district": "Seoni", "coords": (22.0858, 79.5447), "place": "Seoni Highway Corridor", "keywords": ["SEONI", "LAKHNADON", "BARGHAT", "KEOLARI", "GHANSOR"]},
        {"district": "Chhindwara", "coords": (22.0572, 78.9389), "place": "Chhindwara Industrial & Rail Node", "keywords": ["CHHINDWARA", "PARASIA", "SAUSAR", "PANDHURNA", "AMARWARA", "JUNNARDEO", "CHOUDAI"]},
        {"district": "Narsinghpur", "coords": (22.9439, 79.1969), "place": "Gadarwara Super Thermal Power Plant", "keywords": ["NARSINGHPUR", "GADARWARA", "KARELI", "GOTITORI", "TENDUKHEDA MP"]},
        {"district": "Alirajpur", "coords": (22.3039, 74.3547), "place": "Alirajpur Border Corridor", "keywords": ["ALIRAJPUR", "BHABRA", "JOBAT"]},
        {"district": "Jhabua", "coords": (22.7689, 74.5947), "place": "Jhabua Highway & Tribal Corridor", "keywords": ["JHABUA", "THANDLA", "PETLAWAD", "RANAPUR"]},
        {"district": "Dhar", "coords": (22.5978, 75.3014), "place": "Pithampur Industrial Area & Dhar", "keywords": ["DHAR", "PITHAMPUR", "BADNAWAR", "SARDARPUR", "KUKSHI", "MANAWAR", "DHAMNOD"]},
        {"district": "Sidhi", "coords": (24.4167, 81.8833), "place": "Sidhi Mineral & Highway Node", "keywords": ["SIDHI", "MAJHAULI", "CHURHAT", "RAMPUR NAIKIN", "KUSMI"]},
    ],
    "MAHARASHTRA": [
        {"district": "Jalgaon", "coords": (21.0077, 75.5626), "place": "Pachora & Jamner Rail Corridor", "keywords": ["JALGAON", "PACHORA", "JAMNER", "BHUSAWAL", "AMALNER", "CHALISGAON", "ERANDOL", "PACHORA-JAMNER", "WAGHUR"]},
        {"district": "Buldhana", "coords": (20.5311, 76.1839), "place": "Malkapur & Bodwad Rail Link", "keywords": ["BULDHANA", "MALKAPUR", "BODWAD", "KHAMGAON", "SHEGAON", "MEHKAR", "CHIKHLI MH", "SABALKhed", "JIGAON", "BODWAD PARISAR"]},
        {"district": "Parbhani", "coords": (19.2611, 76.7767), "place": "Parbhani City Four Lane Bypass", "keywords": ["PARBHANI", "PARWA", "ASOLA", "JINTUR", "GANGAKHED", "PATHRI", "SELU", "PURNA", "PARBHANI CITY", "PARWA TO ASOLA", "CHARTHANA JINTUR"]},
        {"district": "Beed", "coords": (18.9897, 75.7600), "place": "Parli Vaijanath & Beed Rail Corridor", "keywords": ["BEED", "PARLI VAIJANATH", "PARLI", "MAJALGAON", "GEORAI", "AMBAJOGAI", "ASHTI", "PARLI stations"]},
        {"district": "Palghar", "coords": (19.6967, 72.7699), "place": "Tarapur Atomic & Talasari Expressway Corridor", "keywords": ["PALGHAR", "TARAPUR", "TALASARI", "TALSARI", "DAHANU", "BOISAR", "JAWHAR", "WADA", "VASAI", "VIRAR", "TALSARI TO KARVAD", "SHIRSAD", "MASVAN", "GANJAD", "MANOR", "SHIRSAD - MASVAN", "MASVAN - GANJAD", "SHIRSAD - AKLOLI", "PKG XIII", "PKG XII", "MASVAN TO GANJAD", "SHIRSAD TO MASVAN"]},
        {"district": "Thane", "coords": (19.2183, 72.9781), "place": "Kalyan-Bhiwandi Logistics Hub", "keywords": ["THANE", "KALYAN", "BHIWANDI", "DOMBIVLI", "TITWALA", "KASARA", "MUMBRA", "DIVA", "AKLOLI", "AMNE", "BHOJ", "AKLOLI - AMNE", "AMNE - BHOJ", "PKG XIV", "PKG XV", "PKG XVI", "VADAPE TO THANE", "VADAPE"]},
        {"district": "Raigad", "coords": (18.5158, 73.1822), "place": "JNPT Port & Navi Mumbai International Airport", "keywords": ["RAIGAD", "JNPT", "NAVI MUMBAI", "PANVEL", "ALIBAG", "KARJAT", "KHOPOLI", "MAHAD", "PEN", "ROHA", "DUPL-DPPL", "MORBE", "BHOJ - MORBE", "PKG XVII", "MANGAON", "REWAS", "NHAVA SHEVA", "USAR", "PANVEL INDAPUR", "PANVEL TO INDAPUR", "PUNE RAIGARH DISTRICT BORDER TO MANGAON"]},
        {"district": "Ratnagiri", "coords": (16.9902, 73.3120), "place": "Ratnagiri Port & NH-66 Coastal Highway", "keywords": ["RATNAGIRI", "KASHEDI", "KHED", "CHIPLUN", "LANJA", "RAJAPUR", "SANGAMESHWAR", "GUHAGAR", "BHOGAON KHURD", "KASHEDI GHAT", "KASHEDI GHAT TUNNEL", "BHOGAON KHURD - KASHEDI"]},
        {"district": "Sindhudurg", "coords": (16.1200, 73.7000), "place": "Sindhudurg Coastal & Irrigation Corridor", "keywords": ["SINDHUDURG", "ARUNA", "NARDAVE", "VAIBHAVWADI", "KANKAVLI", "SAWANTWADI", "MALVAN", "VENGURLA", "KUDAL", "DODAMARG", "ARUNA MEDIUM", "NARDAVE MEDIUM"]},
        {"district": "Chandrapur", "coords": (19.9615, 79.2961), "place": "Bhatadi, Sasti & Yekona Coalfields", "keywords": ["CHANDRAPUR", "GAURIDEEP", "GAURI", "BALLARPUR", "SASTI", "DHUPTALA", "YEKONA", "MAJRI", "BHATADI", "GADCHANDUR", "WARORA", "TADOBA", "KORPANA", "RAJURA", "GAURIDEEP/GAURI CENTRAL OCP", "NEW MAJRI", "AMALGAMATED YEKONA"]},
        {"district": "Dhule", "coords": (20.9042, 74.7749), "place": "Dhule & Nardana DFC Industrial Node", "keywords": ["DHULE", "NARDANA", "SHIRPUR", "SINDKHEDA", "SAKRI", "SULWADE", "JAMPHAL", "KANOLI", "SULWADE-JAMPHAL-KANOLI", "TARSOD - FAGNE", "BODHRE - DHULE"]},
        {"district": "Nandurbar", "coords": (21.3700, 74.2400), "place": "Nandurbar Tribal & Renewable Corridor", "keywords": ["NANDURBAR", "SHAHADA", "NAWAPUR", "TALODA", "AKRANI", "AKKALKUWA"]},
        {"district": "Akola", "coords": (20.7002, 77.0082), "place": "Akola Industrial & Rail Junction", "keywords": ["AKOLA", "BALAPUR", "AKOT", "TELHARA", "MURTIZAPUR", "BARSHITAKLI", "PATUR"]},
        {"district": "Washim", "coords": (20.1111, 77.1333), "place": "Washim & Samruddhi Highway Node", "keywords": ["WASHIM", "RISOD", "MALEGAON WASHIM", "MANORA", "MANGULPIR", "KARANJA"]},
        {"district": "Amravati", "coords": (20.9374, 77.7796), "place": "Amravati Textile Park & Highway", "keywords": ["AMRAVATI", "ACHALPUR", "CHANDUR", "MORSHI", "WARUD", "DARYAPUR", "ANJANGAON", "LOWER PEDHI"]},
        {"district": "Yavatmal", "coords": (20.3888, 78.1204), "place": "Yavatmal & Wani Coal Mining Area", "keywords": ["YAVATMAL", "WANI", "PUSAD", "DARWHA", "DIGRAS", "UMARKHED", "PANDHARKAWADA", "GHONSA", "MUNGOLI", "NIRGUDA", "KOLARPIMPRI", "MUNGOLI NIRGUDA", "KOLARPIMPRI EXPANSION"]},
        {"district": "Wardha", "coords": (20.7453, 78.6022), "place": "Wardha & Sewagram Rail Corridor", "keywords": ["WARDHA", "SEWAGRAM", "HINGANGHAT", "ARVI", "DEOLI", "SELOU"]},
        {"district": "Gondia", "coords": (21.4597, 80.1961), "place": "Gondia Rail Junction & Birsi Airport", "keywords": ["GONDIA", "BIRSI", "TIRODA", "GOREGAON MH", "AMGAON", "DEORI", "SADAK ARJUNI", "ARJUNI MORGAON"]},
        {"district": "Gadchiroli", "coords": (20.1844, 80.0028), "place": "Surjagarh Iron Ore Mining & Corridor", "keywords": ["GADCHIROLI", "SURJAGARH", "ARMORI", "CHAMORSHI", "AHERI", "SIRONCHA", "DHANORA", "KURKHEDA"]},
        {"district": "Hingoli", "coords": (19.7197, 77.1494), "place": "Hingoli LIGO-India Science Node", "keywords": ["HINGOLI", "AUNDHA NAGNATH", "KALAMNURI", "BASMATH", "SENGAON"]},
        {"district": "Jalna", "coords": (19.8410, 75.8864), "place": "Jalna Dry Port & Steel Hub", "keywords": ["JALNA", "PARTUR", "AMBAD", "BHOKARDAN", "JAFRABAD MH", "BADNAPUR"]},
        {"district": "Dharashiv", "coords": (18.1856, 76.0419), "place": "Dharashiv (Osmanabad) Renewable Node", "keywords": ["OSMANABAD", "DHARASHIV", "TULJAPUR", "UMERGA", "PARANDA", "BHUM", "KALAMB"]},
        {"district": "Latur", "coords": (18.4088, 76.5604), "place": "Marathwada Rail Coach Factory Latur", "keywords": ["LATUR", "AUSA", "UDGIR", "AHMADPUR", "NILANGA", "CHAKUR", "RENAPUR", "CHAKUR LOHA"]},
        {"district": "Solapur", "coords": (17.6599, 75.9064), "place": "Solapur NTPC Super Thermal Power Plant", "keywords": ["SOLAPUR", "PANDHARPUR", "BARSHI", "AKKALKOT", "MOHOL", "KARMALA", "MADHA", "MANGALWEDHA", "SANGOLA", "PANDHARPUR TOWN", "DHARAMPURI-LONAND"]},
        {"district": "Sangli", "coords": (16.8524, 74.5815), "place": "Sangli & Miraj Railway Junction", "keywords": ["SANGLI", "MIRAJ", "ISLAMPUR", "TASGAON", "VITA", "WALWA", "JATH", "KAVATHE MAHANKAL"]},
        {"district": "Kolhapur", "coords": (16.7050, 74.2433), "place": "Kolhapur Foundry SEZ & Airport", "keywords": ["KOLHAPUR", "ICHALKARANJI", "JAYSINGPUR", "KAGAL", "GADHINGLAJ", "SHIROL", "RADHANAGARI", "PANHALA", "KAGAL-SATARA"]},
        {"district": "Satara", "coords": (17.6805, 74.0183), "place": "Satara Wind Energy & NH-48 Corridor", "keywords": ["SATARA", "KARAD", "WAI", "PHALTAN", "MAHABALESHWAR", "KOREGAON", "SHIRWAL", "PATAN MH", "URMODI", "KHAMBATAKI", "SHIRWAL-LONAND", "LONAND TO DIVE GHAT"]},
    ],
    "RAJASTHAN": [
        {"district": "Dausa", "coords": (26.8928, 76.3375), "place": "Bandikui & Dausa Greenfield Expressway Spur", "keywords": ["DAUSA", "BANDIKUI", "LALSOT", "MAHWA", "SIKRAI", "BANDIKUI TO JAIPUR"]},
        {"district": "Rajsamand", "coords": (25.0747, 73.8828), "place": "Gomti & Rajsamand Highway Corridor", "keywords": ["RAJSAMAND", "GOMTI", "BEAWAR GOMTI", "NATHDWARA", "KANKROLI", "AMET", "KUMBHALGARH", "BHIM"]},
        {"district": "Pali", "coords": (25.7711, 73.3234), "place": "Pali Industrial Hub & DFC Corridor", "keywords": ["PALI", "SOJAT", "SUMERPUR", "FALNA", "ROHAT", "MARWAR JUNCTION", "BALI"]},
        {"district": "Sirohi", "coords": (24.8826, 72.8589), "place": "Abu Road & Mount Abu Highway Node", "keywords": ["SIROHI", "ABU ROAD", "MOUNT ABU", "PINDWARA", "SHEOGANJ", "REODAR"]},
        {"district": "Jalore", "coords": (25.3444, 72.6156), "place": "Jalore Granite Hub & Amritsar-Jamnagar Corridor", "keywords": ["JALORE", "SANCHORE", "BHINMAL", "AHORE", "SAYLA RJ"]},
        {"district": "Pratapgarh", "coords": (24.0300, 74.7800), "place": "Pratapgarh Solar & Tribal Corridor", "keywords": ["PRATAPGARH RJ", "PRATAPGARH RAJASTHAN", "CHHOTI SADRI", "DHARIAWAD", "ARNOD"]},
        {"district": "Dungarpur", "coords": (23.8364, 73.7147), "place": "Dungarpur Border Highway & Rail Link", "keywords": ["DUNGARPUR", "SAGWARA", "ASPUR", "SIMALWARA", "BICHIWARA"]},
        {"district": "Banswara", "coords": (23.5461, 74.4350), "place": "Mahi Banswara Nuclear Power Plant", "keywords": ["BANSWARA", "MAHI BANSWARA", "GHATOL", "KUSHALGARH", "BAGIDORA", "GARHI"]},
        {"district": "Chittorgarh", "coords": (24.8887, 74.6269), "place": "Chittorgarh Zinc & Cement SEZ", "keywords": ["CHITTORGARH", "CHITTOR", "NIMBAHERA", "BEGUN", "RAWATBHATA", "KAPASAN", "GANGRAR"]},
        {"district": "Bhilwara", "coords": (25.3467, 74.6367), "place": "Bhilwara Textile City & Mining Corridor", "keywords": ["BHILWARA", "MANDAL", "ASIND", "GULABPURA", "SHAHPURA RJ", "BIJOLIA", "JAHAZPUR"]},
        {"district": "Bundi", "coords": (25.4414, 75.6453), "place": "Bundi Delhi-Mumbai Expressway Corridor", "keywords": ["BUNDI", "KESHORAIPATAN", "NAINWA", "HINDOLI", "INDARGARH"]},
        {"district": "Baran", "coords": (25.1011, 76.5131), "place": "Chhabra Super Thermal Power Plant", "keywords": ["BARAN", "CHHABRA", "ANTA", "ATRU", "KISHANGANJ RJ", "SHAHBAD"]},
        {"district": "Jhalawar", "coords": (24.5975, 76.1611), "place": "Kalishindh Thermal Power & Jhalawar Corridor", "keywords": ["JHALAWAR", "JHALRAPATAN", "KALISINDH", "BHAWANI MANDI", "PIRAWAN", "KHANPUR", "MANOHAR THANA"]},
        {"district": "Karauli", "coords": (26.4950, 77.0200), "place": "Karauli Highway & Stone Cluster", "keywords": ["KARAULI", "HINDAUN", "TODABHIM", "SAPOTRA", "MANDRAYAL"]},
        {"district": "Dholpur", "coords": (26.7025, 77.8931), "place": "Dholpur Gas Thermal & Chambal Bridge", "keywords": ["DHOLPUR", "BARI", "BASERI", "RAJAKHERA"]},
        {"district": "Sawai Madhopur", "coords": (25.9928, 76.3533), "place": "Sawai Madhopur Expressway & Tourism Corridor", "keywords": ["SAWAI MADHOPUR", "GANGAPUR CITY", "BONLI", "BAMANWAS", "KHANDAR"]},
        {"district": "Tonk", "coords": (26.1667, 75.7833), "place": "Tonk Highway & Bisalpur Dam Corridor", "keywords": ["TONK", "DEOLI", "MALPURA", "NIWAI", "TODARAYSINGH", "UNIARA"]},
        {"district": "Churu", "coords": (28.2900, 74.9600), "place": "Churu Highway & Rail Junction", "keywords": ["CHURU", "RATANGARH", "SUJANGARH", "SARDARSHAHAR", "RAJGARH RJ", "TARANAGAR"]},
        {"district": "Jhunjhunu", "coords": (28.1289, 75.3992), "place": "Khetri Copper Complex & Jhunjhunu", "keywords": ["JHUNJHUNU", "KHETRI", "CHIRAWA", "NAWALGARH", "UDAIPURWATI", "BUHANA"]},
        {"district": "Sikar", "coords": (27.6094, 75.1397), "place": "Sikar Education City & Highway Corridor", "keywords": ["SIKAR", "NEEM KA THANA", "SRI MADHOPUR", "FATEHPUR RJ", "LAXMANGARH", "DANTA RAMGARH"]},
        {"district": "Hanumangarh", "coords": (29.5800, 74.3200), "place": "Hanumangarh & Amritsar-Jamnagar Expressway", "keywords": ["HANUMANGARH", "PILIBANGA", "RAWATSAR", "NOHAR", "BHADRA RJ", "SANGARIA"]},
        {"district": "Sri Ganganagar", "coords": (29.9200, 73.8800), "place": "Suratgarh Super Thermal Power Plant", "keywords": ["GANGANAGAR", "SRI GANGANAGAR", "SURATGARH", "RAISINGHNAGAR", "ANUPGARH", "PADAMPUR", "GHARSANA"]},
        {"district": "Beawar", "coords": (26.1011, 74.3183), "place": "Beawar Cement Hub & Highway Corridor", "keywords": ["BEAWAR", "BEAWER", "JAITARAN", "RAIPUR PALI", "MASUDA", "BADNOR"]},
        {"district": "Balotra", "coords": (25.8300, 72.2400), "place": "HPCL Rajasthan Refinery Pachpadra", "keywords": ["BALOTRA", "PACHPADRA", "SIWANA", "SAMDARI", "BAYTU"]},
    ],
    "ODISHA": [
        {"district": "Mayurbhanj", "coords": (21.9287, 86.7411), "place": "Bangriposi & Gorumahisani Rail Link", "keywords": ["MAYURBHANJ", "BARIPADA", "BANGRIPOSI", "GORUMAHISANI", "BADAMPAHAR", "RAIRANGPUR", "KARANJIA"]},
        {"district": "Kendujhar", "coords": (21.6289, 85.5817), "place": "Kendujhargarh Iron Ore Rail Corridor", "keywords": ["KENDUJHAR", "KEONJHAR", "KENDUJHARGARH", "BARBIL", "JODA", "ANANDAPUR", "GHATGAON"]},
        {"district": "Jajpur", "coords": (20.8400, 86.3300), "place": "Kalinganagar Steel SEZ & Kuakhia Highway", "keywords": ["JAJPUR", "KALINGANAGAR", "KUAKHIA", "JAJPUR ROAD", "VYASANAGAR", "DANAGADI", "CHANDIKHOLE", "SUKINDA"]},
        {"district": "Bhadrak", "coords": (21.0544, 86.5056), "place": "Dhamra Port & LNG Terminal", "keywords": ["BHADRAK", "DHAMRA", "DHAMRA PORT", "CHANDBALI", "BASUDEVPUR", "TIHIDI"]},
        {"district": "Kendrapara", "coords": (20.5000, 86.4200), "place": "Kendrapara Coastal Rail & Highway", "keywords": ["KENDRAPARA", "PATTAMUNDAI", "AUL", "RAJNAGAR ODISHA", "MARSHAGHAI"]},
        {"district": "Puri", "coords": (19.8135, 85.8312), "place": "Puri International Airport & Tourism Corridor", "keywords": ["PURI", "KONARK", "PIPILI", "NIMAPARA", "SATAPADA", "BRAHMAGIRI"]},
        {"district": "Ganjam", "coords": (19.3149, 84.7941), "place": "Gopalpur Port & Ganjam Highway", "keywords": ["GANJAM", "BERHAMPUR", "GOPALPUR", "CHATRAPUR", "ASKA", "BHANJANAGAR", "HINJILICUT"]},
        {"district": "Gajapati", "coords": (18.8167, 84.1667), "place": "Paralakhemundi & Gajapati Corridor", "keywords": ["GAJAPATI", "PARALAKHEMUNDI", "KASHINAGARA", "MOHANA", "R.UDAYAGIRI"]},
        {"district": "Kandhamal", "coords": (20.4667, 84.2333), "place": "Phulbani & Kandhamal Highway Corridor", "keywords": ["KANDHAMAL", "PHULBANI", "BALLIGUDA", "G.UDAYAGIRI", "TIKABALI"]},
        {"district": "Boudh", "coords": (20.8333, 84.3167), "place": "Boudh Mahanadi Rail/Road Corridor", "keywords": ["BOUDH", "BAUDH", "PURUNAKATAK", "HARBHANGA", "KANTA MAL"]},
        {"district": "Subarnapur", "coords": (20.9000, 83.9167), "place": "Sonepur Silk & Rail Corridor", "keywords": ["SUBARNAPUR", "SONEPUR", "TARBHA", "BINKA", "ULLUNDA"]},
        {"district": "Balangir", "coords": (20.7100, 83.4800), "place": "Khurda-Balangir Rail Project", "keywords": ["BALANGIR", "BOLANGIR", "TITLAGARH", "PATNAGARH", "KANTABANJI", "TUSHURA"]},
        {"district": "Nuapada", "coords": (20.8333, 82.5333), "place": "Khariar Road & Nuapada Corridor", "keywords": ["NUAPADA", "KHARIAR", "KHARIAR ROAD", "KOMNA", "SINAPALI"]},
        {"district": "Kalahandi", "coords": (19.9100, 83.1100), "place": "Bhawanipatna & Kesinga Rail Corridor", "keywords": ["KALAHANDI", "BHAWANIPATNA", "KESINGA", "JUNAGARH ODISHA", "DHARAMGARH", "LANJIGARH"]},
        {"district": "Rayagada", "coords": (19.1667, 83.4167), "place": "Rayagada Alumina & Railway Division", "keywords": ["RAYAGADA", "GUNUPUR", "TIKIRI", "KASHIPUR ODISHA", "BISSAM CUTTACK", "MUNIGUDA"]},
        {"district": "Nabarangpur", "coords": (19.2300, 82.5500), "place": "Nabarangpur Rail Link & Highway", "keywords": ["NABARANGPUR", "NOWRANGPUR", "UMERKOTE", "CHANDAHANDI", "RAIGHAR"]},
        {"district": "Malkangiri", "coords": (18.3500, 81.9000), "place": "Malkangiri Airport & Border Highway", "keywords": ["MALKANGIRI", "BALIMELA", "CHITRAKONDA", "MATHILI", "KALIMELA"]},
        {"district": "Deogarh", "coords": (21.5333, 84.7333), "place": "Deogarh NH-49 Highway Corridor", "keywords": ["DEOGARH", "DEBAGARH", "BARKOTE", "REAMAL"]},
        {"district": "Dhenkanal", "coords": (20.6667, 85.6000), "place": "Kamakhya Nagar & Dhenkanal Industrial Node", "keywords": ["DHENKANAL", "KAMAKHYA NAGAR", "BHUBAN", "HINDOL", "GONDIA ODISHA"]},
        {"district": "Bargarh", "coords": (21.3333, 83.6167), "place": "Bargarh Ethanol & Highway Corridor", "keywords": ["BARGARH", "PADAMPUR ODISHA", "ATTABIRA", "BARPALI", "BHATLI", "SOHELA"]},
    ],
    "KERALA": [
        {"district": "Kasaragod", "coords": (12.5102, 74.9852), "place": "Chengala & Neeleshwaram 6-Lane NH-66 Corridor", "keywords": ["KASARAGOD", "CHENGALA", "NEELESHWARAM", "KANHANGAD", "MANJESHWAR", "UPPALA", "TRIKARIPUR"]},
        {"district": "Kannur", "coords": (11.8745, 75.3704), "place": "Kannur International Airport & Port", "keywords": ["KANNUR", "THALASSERY", "PAYYANUR", "MATTANNUR", "IRITTY", "TALIPARAMBA"]},
        {"district": "Wayanad", "coords": (11.6854, 76.1320), "place": "Kalpetta & Sultan Bathery Corridor", "keywords": ["WAYANAD", "KALPETTA", "SULTAN BATHERY", "MANANTHAVADY", "MEPPADI"]},
        {"district": "Malappuram", "coords": (11.0510, 76.0711), "place": "Valanchery Bypass & Calicut Airport", "keywords": ["MALAPPURAM", "VALANCHERY", "KONDOTTY", "TIRUR", "PERINTHALMANNA", "PONNANI", "KOTTAKKAL", "VALANCHERY BYPASS"]},
        {"district": "Palakkad", "coords": (10.7867, 76.6548), "place": "Palakkad Mega Food Park & Industrial Corridor", "keywords": ["PALAKKAD", "OTTAPALAM", "SHORANUR", "CHITTUR", "MANNARKKAD", "ALATHUR"]},
        {"district": "Thrissur", "coords": (10.5276, 76.2144), "place": "Thrissur Cultural Capital & Highway Node", "keywords": ["THRISSUR", "TRICHUR", "GURUVAYUR", "CHALAKUDY", "KODUNGALLUR", "KUNNAMKULAM", "WADAKKANCHERY"]},
        {"district": "Idukki", "coords": (9.8497, 76.9790), "place": "Idukki Hydroelectric Project & Munnar", "keywords": ["IDUKKI", "MUNNAR", "THODUPUZHA", "KATTAPPANA", "NEDUMKANDAM", "PEERMADE"]},
        {"district": "Kottayam", "coords": (9.5916, 76.5222), "place": "Kottayam Rubber Hub & Inland Waterways", "keywords": ["KOTTAYAM", "CHANGANASSERY", "PALA", "VAIKOM", "KANJIRAPPALLY"]},
        {"district": "Alappuzha", "coords": (9.4981, 76.3388), "place": "Alappuzha Port & Coastal Highway", "keywords": ["ALAPPUZHA", "ALLEPPEY", "CHERTHALA", "KAYAMKULAM", "MAVELIKKARA", "AMBALAPUZHA"]},
        {"district": "Pathanamthitta", "coords": (9.2648, 76.7870), "place": "Sabarimala Pilgrim Corridor & Adoor", "keywords": ["PATHANAMTHITTA", "ADOOR", "THIRUVALLA", "RANNI", "KONNI", "KOZHENCHERRY"]},
    ],
    "PUNJAB": [
        {"district": "Sri Muktsar Sahib", "coords": (30.4744, 74.5167), "place": "Sri Muktsar Sahib Highway Corridor", "keywords": ["MUKTSAR", "SRI MUKTSAR SAHIB", "MALOUT", "GIDDERBAHA"]},
        {"district": "Fazilka", "coords": (30.4033, 74.0278), "place": "Abohar & Fazilka Border Highway", "keywords": ["FAZILKA", "ABOHAR", "JALALABAD PUNJAB"]},
        {"district": "Firozpur", "coords": (30.9237, 74.6133), "place": "Firozpur Railway Division & Border Post", "keywords": ["FIROZPUR", "FEROZEPUR", "GURU HAR SAHAI", "ZIRA"]},
        {"district": "Faridkot", "coords": (30.6769, 74.7583), "place": "Faridkot Medical University & Highway", "keywords": ["FARIDKOT", "KOTKAPURA", "JAITU"]},
        {"district": "Moga", "coords": (30.8165, 75.1717), "place": "Moga Food Processing & Highway Corridor", "keywords": ["MOGA", "BAGHA PURANA", "NIHAL SINGH WALA", "DHARAMKOT"]},
        {"district": "Barnala", "coords": (30.3819, 75.5469), "place": "Barnala Industrial & Highway Node", "keywords": ["BARNALA", "TAPA", "MEHAL KALAN"]},
        {"district": "Mansa", "coords": (29.9889, 75.3917), "place": "Mansa Thermal Power Plant", "keywords": ["MANSA PUNJAB", "MANSA", "BUDHLADA", "SARDULGARH"]},
        {"district": "Sangrur", "coords": (30.2458, 75.8422), "place": "Sangrur & Sunam Highway Corridor", "keywords": ["SANGRUR", "SUNAM", "DHURI", "LEHRAGAGA", "DIRBA"]},
        {"district": "Kapurthala", "coords": (31.3800, 75.3800), "place": "Rail Coach Factory Kapurthala", "keywords": ["KAPURTHALA", "RCF KAPURTHALA", "PHAGWARA", "SULTANPUR LODHI", "BHOLATH"]},
        {"district": "Hoshiarpur", "coords": (31.5300, 75.9200), "place": "Hoshiarpur & Dasuya Highway Corridor", "keywords": ["HOSHIARPUR", "DASUYA", "MUKERIAN", "GARHSHANKAR"]},
        {"district": "Shahid Bhagat Singh Nagar", "coords": (31.1256, 76.1189), "place": "Nawanshahr & Banga Corridor", "keywords": ["NAWANSHAHR", "SBS NAGAR", "SHAHID BHAGAT SINGH NAGAR", "BANGA", "BALACHAUR"]},
        {"district": "Rupnagar", "coords": (30.9664, 76.5331), "place": "IIT Ropar & Rupnagar Power Plant", "keywords": ["RUPNAGAR", "ROPAR", "ANANDPUR SAHIB", "MORINDA", "NANGAL"]},
        {"district": "Fatehgarh Sahib", "coords": (30.6431, 76.3883), "place": "Mandi Gobindgarh Steel Cluster", "keywords": ["FATEHGARH SAHIB", "MANDI GOBINDGARH", "SIRHIND", "AMLOH", "KHAMANON"]},
        {"district": "Pathankot", "coords": (32.2689, 75.6497), "place": "Pathankot Airport & Defense Corridor", "keywords": ["PATHANKOT", "SUJANPUR PUNJAB", "DHAR KALAN"]},
        {"district": "Tarn Taran", "coords": (31.4522, 74.9256), "place": "Tarn Taran & Harike Wetland Corridor", "keywords": ["TARN TARAN", "PATTI PUNJAB", "KHADUR SAHIB", "HARIKE"]},
    ],
    "HARYANA": [
        {"district": "Rewari", "coords": (28.1833, 76.6167), "place": "Rewari DFC & Kund Bypass Highway", "keywords": ["REWARI", "KUND BYPASS", "KUND", "BAWAL", "DHARUHERA", "KOSLI"]},
        {"district": "Mahendragarh", "coords": (28.2800, 76.1500), "place": "Narnaul Logistics Hub & Central University", "keywords": ["MAHENDRAGARH", "MOHINDERGARH", "NARNAUL", "ATELI", "KANINA"]},
        {"district": "Charkhi Dadri", "coords": (28.5928, 76.2667), "place": "Charkhi Dadri Highway & Cement Corridor", "keywords": ["CHARKHI DADRI", "DADRI", "BADHRA"]},
        {"district": "Bhiwani", "coords": (28.7833, 76.1333), "place": "Bhiwani Rail & Highway Junction", "keywords": ["BHIWANI", "TOSHAM", "LOHARU", "SIWANI", "BAWAL"]},
        {"district": "Jhajjar", "coords": (28.6067, 76.6567), "place": "Jhajjar NTPC & AIIMS Badsa Node", "keywords": ["JHAJJAR", "BADSA", "BAHADURGARH", "BERI", "MATANHAIL"]},
        {"district": "Jind", "coords": (29.3167, 76.3167), "place": "Jind Railway Junction & Highway", "keywords": ["JIND", "NARWANA", "SAFIDON", "JULANA", "UCHANA"]},
        {"district": "Kaithal", "coords": (29.8000, 76.4000), "place": "Kaithal Highway Corridor", "keywords": ["KAITHAL", "GUHLA", "KALAYAT", "PUNDRI"]},
        {"district": "Fatehabad", "coords": (29.5167, 75.4500), "place": "Gorakhpur Haryana Nuclear Power Plant", "keywords": ["FATEHABAD", "TOHANA", "RATIA", "BHUNA", "GORAKHPUR HARYANA"]},
        {"district": "Sirsa", "coords": (29.5333, 75.0333), "place": "Sirsa Air Force Station & Highway", "keywords": ["SIRSA", "DABWALI", "ELLENABAD", "RANIA"]},
        {"district": "Kurukshetra", "coords": (29.9667, 76.8833), "place": "Kurukshetra University & Tourism Corridor", "keywords": ["KURUKSHETRA", "THANESAR", "PEHOWA", "SHAHBAD HARYANA", "LADWA"]},
        {"district": "Yamunanagar", "coords": (30.1333, 77.2833), "place": "Yamunanagar Paper & Thermal Power", "keywords": ["YAMUNANAGAR", "JAGADHRI", "BILASPUR HARYANA", "CHHACHHRAULI", "RADAUR"]},
        {"district": "Nuh", "coords": (28.1167, 77.0167), "place": "Delhi-Mumbai Expressway Mewat Node", "keywords": ["NUH", "MEWAT", "TAORU", "FEROZEPUR JHIRKA", "PUNHANA"]},
        {"district": "Palwal", "coords": (28.1444, 77.3256), "place": "Palwal KMP Expressway & Freight Corridor", "keywords": ["PALWAL", "HODAL", "HATHIN", "KMP EXPRESSWAY"]},
    ],
    "UTTARAKHAND": [
        {"district": "Champawat", "coords": (29.3333, 80.1000), "place": "Champawat Bypass & Border Highway", "keywords": ["CHAMPAWAT", "CHAMPAWAT BYPASS", "LOHAGHAT", "TANAKPUR", "BANBASA", "PATI"]},
        {"district": "Pithoragarh", "coords": (29.5833, 80.2167), "place": "GMC Pithoragarh & Border Highway", "keywords": ["PITHORAGARH", "GMC PITHORAGARH", "DARCHULA", "DIDIHAT", "BERINAG", "MUNSIYARI", "GANGOLIHAT"]},
        {"district": "Almora", "coords": (29.5975, 79.6592), "place": "Almora Cultural Capital & Highway Node", "keywords": ["ALMORA", "RANIKHET", "DWARAHAT", "BHIKIYASEN", "SOMESHWAR"]},
        {"district": "Bageshwar", "coords": (29.8394, 79.7719), "place": "Bageshwar Pindar Valley Corridor", "keywords": ["BAGESHWAR", "KAPCOT", "GARUR"]},
        {"district": "Chamoli", "coords": (30.4167, 79.3333), "place": "Tapovan Vishnugad Hydroelectric Project", "keywords": ["CHAMOLI", "JOSHIMATH", "GOPESHWAR", "KARNAPRAYAG", "GAUCHAR", "VISHNUGAD", "PIPALKOTI"]},
        {"district": "Rudraprayag", "coords": (30.2858, 78.9817), "place": "Rishikesh-Karnaprayag Rail Rudraprayag Node", "keywords": ["RUDRAPRAYAG", "UKHIMATH", "JAKHOLI", "AGASTYAMUNI"]},
        {"district": "Uttarkashi", "coords": (30.7300, 78.4500), "place": "Uttarkashi Char Dham Highway Corridor", "keywords": ["UTTARKASHI", "BARKOT", "PUROLA", "BHATWARI", "CHINYALISAUR"]},
        {"district": "Pauri Garhwal", "coords": (30.1500, 78.7800), "place": "Kotdwar & Pauri Rail/Road Corridor", "keywords": ["PAURI", "PAURI GARHWAL", "KOTDWAR", "SRINAGAR UTTARAKHAND", "LANSDOWNE"]},
        {"district": "Haridwar", "coords": (29.9457, 78.1642), "place": "BHEL Haridwar & SIDCUL Industrial Area", "keywords": ["HARIDWAR", "ROORKEE", "BHAGWANPUR", "LAKSAR", "SIDCUL HARIDWAR"]},
    ],
    "HIMACHAL PRADESH": [
        {"district": "Bilaspur", "coords": (31.3300, 76.7500), "place": "AIIMS Bilaspur & Kol Dam Hydroelectric", "keywords": ["BILASPUR HP", "BILASPUR HIMACHAL", "GHUMARWIN", "KOL DAM"]},
        {"district": "Hamirpur", "coords": (31.6862, 76.5218), "place": "NIT Hamirpur & Highway Node", "keywords": ["HAMIRPUR HP", "HAMIRPUR HIMACHAL", "NADAUN", "BARSAR"]},
        {"district": "Una", "coords": (31.4685, 76.2708), "place": "Una Bulk Drug Park & Railway Terminal", "keywords": ["UNA HP", "UNA HIMACHAL", "AMB", "MEHATPUR", "GAGRET"]},
        {"district": "Chamba", "coords": (32.5564, 76.1258), "place": "Chamera Hydroelectric Project & Chamba", "keywords": ["CHAMBA", "DALHOUSIE", "CHAMERA", "BHARMOUR", "KIANI"]},
        {"district": "Kullu", "coords": (31.9579, 77.1095), "place": "Kullu-Manali Tourism & Tunnel Corridor", "keywords": ["KULLU", "MANALI", "BHUNTAR", "BANJAR", "NIRMAND"]},
        {"district": "Kinnaur", "coords": (31.5833, 78.3333), "place": "Karcham Wangtoo & Nathpa Jhakri Hydro", "keywords": ["KINNAUR", "RECKONG PEO", "KARCHAM", "NATHPA JHAKRI", "POOH"]},
        {"district": "Lahaul and Spiti", "coords": (32.5700, 77.0300), "place": "Atal Tunnel North Portal & Kaza", "keywords": ["LAHAUL", "SPITI", "KEYLONG", "KAZA", "ATAL TUNNEL"]},
    ],
    "ASSAM": [
        {"district": "Goalpara", "coords": (26.1800, 90.6200), "place": "Goalpara Rail Doubling Corridor", "keywords": ["GOALPARA", "DUDHNOI", "MATIA", "LAKHIPUR ASSAM"]},
        {"district": "Bongaigaon", "coords": (26.4789, 90.5583), "place": "Bongaigaon Refinery & Rail Junction", "keywords": ["BONGAIGAON", "NEW BONGAIGAON", "BIJNI", "ABHAYAPURI"]},
        {"district": "Barpeta", "coords": (26.3200, 91.0000), "place": "Barpeta Road & Highway Corridor", "keywords": ["BARPETA", "BARPETA ROAD", "HOWLY", "SARTHEBARI"]},
        {"district": "Nalbari", "coords": (26.4400, 91.4400), "place": "Nalbari Medical College & Highway", "keywords": ["NALBARI", "TIHU", "MUKALMUA", "BARBHAG"]},
        {"district": "Baksa", "coords": (26.6800, 91.6000), "place": "Musalpur & Indo-Bhutan Highway", "keywords": ["BAKSA", "MUSALPUR", "TAMULPUR", "GORESWAR"]},
        {"district": "Chirang", "coords": (26.5500, 90.5000), "place": "Kajalgon & BTR Highway Node", "keywords": ["CHIRANG", "KAJALGAON", "SIDLI", "RUNIKHATA"]},
        {"district": "Kokrajhar", "coords": (26.4000, 90.2700), "place": "Kokrajhar Rail Corridor & Bodoland Central", "keywords": ["KOKRAJHAR", "GOSSAIGAON", "FAKIRAGRAM", "DOTMA"]},
        {"district": "Udalguri", "coords": (26.7400, 92.1000), "place": "Udalguri Border Highway & Tea Area", "keywords": ["UDALGURI", "TANGLA", "KALAIGAON", "ROWTA"]},
        {"district": "Darrang", "coords": (26.4500, 92.0300), "place": "Mangaldai & Darrang Highway Node", "keywords": ["DARRANG", "MANGALDAI", "SIPAJHAR", "DALGAON"]},
        {"district": "Morigaon", "coords": (26.2500, 92.3400), "place": "Tata Semiconductor Facility Jagiroad", "keywords": ["MORIGAON", "JAGIROAD", "BHURAGAON", "MAYONG"]},
        {"district": "Nagaon", "coords": (26.3500, 92.6800), "place": "Nagaon Bypass & Kaliabor Highway", "keywords": ["NAGAON", "KALIABOR", "RAHA", "DHING", "SAMAGURI"]},
        {"district": "Hojai", "coords": (26.0000, 92.8500), "place": "Lumding Railway Division & Hojai", "keywords": ["HOJAI", "LUMDING", "DOBOKA", "LANKA"]},
        {"district": "Karbi Anglong", "coords": (26.1500, 93.3600), "place": "Diphu Tribal & Highway Corridor", "keywords": ["KARBI ANGLONG", "DIPHU", "BOKAJAN", "HOWRAGHAT"]},
        {"district": "Dima Hasao", "coords": (25.1800, 93.0300), "place": "Haflong Hill Station & Lumding-Badarpur BG Line", "keywords": ["DIMA HASAO", "HAFLONG", "MAIBANG", "HARANGAJAO", "UMRANGSO"]},
        {"district": "Cachar", "coords": (24.8333, 92.7789), "place": "Silchar Airport & Multi-Modal Logistics Hub", "keywords": ["SILCHAR", "CACHAR", "LAKHIPUR CACHAR", "UDHARBOND", "SONAI", "DHOLAI"]},
        {"district": "Hailakandi", "coords": (24.6800, 92.5600), "place": "Hailakandi & Algapur Rail Link", "keywords": ["HAILAKANDI", "ALGAPUR", "LALA", "KATLICHERRA"]},
        {"district": "Karimganj", "coords": (24.8700, 92.3500), "place": "Karimganj Border River Port & ICP", "keywords": ["KARIMGANJ", "BADARPUR", "RAMKRISHNA NAGAR", "PATHARKANDI"]},
        {"district": "Lakhimpur", "coords": (27.2400, 94.1000), "place": "North Lakhimpur Medical College & Highway", "keywords": ["LAKHIMPUR", "NORTH LAKHIMPUR", "BIHPURIA", "NARAYANPUR ASSAM", "DHAKUAKHANA"]},
        {"district": "Dhemaji", "coords": (27.4800, 94.5800), "place": "Bogibeel Bridge North Bank & Dhemaji", "keywords": ["DHEMAJI", "SILAPATHAR", "JONAI", "GOGAMUKH", "MURKONGSELEK", "HARMUTY"]},
        {"district": "Tinsukia", "coords": (27.5000, 95.3700), "place": "Digboi Refinery & Tinsukia Rail Junction", "keywords": ["TINSUKIA", "DIGBOI", "MARGHERITA", "MAKUM", "DOOMDOOMA", "LEDO"]},
        {"district": "Sivasagar", "coords": (26.9800, 94.6300), "place": "ONGC Assam Asset & Sivasagar Heritage", "keywords": ["SIVASAGAR", "SIBSAGAR", "NAZIRA", "DEMOW", "AMGURI"]},
        {"district": "Charaideo", "coords": (27.0500, 95.0000), "place": "Sonari & Charaideo Maidams Heritage Node", "keywords": ["CHARAIDEO", "SONARI", "SAPEKHATI"]},
        {"district": "Jorhat", "coords": (26.7500, 94.2200), "place": "Jorhat Airport & Tea Research Centre", "keywords": ["JORHAT", "MARIANI", "TITABAR", "TEOK"]},
        {"district": "Majuli", "coords": (26.9500, 94.2000), "place": "Majuli River Island Major Bridge Project", "keywords": ["MAJULI", "GARAMUR", "KAMALABARI", "JENGRAIMUKH"]},
        {"district": "Biswanath", "coords": (26.7300, 93.1500), "place": "Biswanath Chariali & Highway Corridor", "keywords": ["BISWANATH", "BISWANATH CHARIALI", "GOHPUR", "SOOTEA"]},
        {"district": "Sonitpur", "coords": (26.6500, 92.8000), "place": "Tezpur Defense Hub & Kaliabhomora Bridge", "keywords": ["TEZPUR", "SONITPUR", "DHEKIAJULI", "RANGAPARA", "JAMUGURIHAT"]},
    ],
    "WEST BENGAL": [
        {"district": "Howrah", "coords": (22.5958, 88.2636), "place": "Howrah Railway Division & Kolkata Metro East-West", "keywords": ["HOWRAH", "SANTRAGACHI", "SHALIMAR", "ULUBERIA", "BALLY", "DOMJUR"]},
        {"district": "Hooghly", "coords": (22.9000, 88.3900), "place": "Dankuni Freight Corridor Hub & Hooghly", "keywords": ["HOOGHLY", "DANKUNI", "BANDEL", "CHINSURAH", "SERAMPORE", "CHANDANNAGAR", "TARAKESWAR"]},
        {"district": "Nadia", "coords": (23.4700, 88.5500), "place": "Kalyani AIIMS & Expressway Corridor", "keywords": ["NADIA", "KALYANI", "RANAGHAT", "KRISHNANAGAR", "SHANTIPUR", "BETHUADAHARI"]},
        {"district": "Murshidabad", "coords": (24.1800, 88.2700), "place": "Farakka Super Thermal Power Station", "keywords": ["MURSHIDABAD", "FARAKKA", "BERHAMPORE WB", "JANGIPUR", "LALGOLA", "DHULIYAN"]},
        {"district": "Birbhum", "coords": (23.8400, 87.6200), "place": "Deucha Pachami Coal & Bolpur Shantiniketan", "keywords": ["BIRBHUM", "SURI", "BOLPUR", "SHANTINIKETAN", "RAMPURHAT", "SAINTHIA", "DEUCHA PACHAMI"]},
        {"district": "Bankura", "coords": (23.2300, 87.0700), "place": "Bankura & Mejia Thermal Power Plant", "keywords": ["BANKURA", "MEJIA", "BISHNUPUR WB", "BARJORA", "KHATRA"]},
        {"district": "Purulia", "coords": (23.3300, 86.3600), "place": "Purulia Pumped Storage Hydro & Adra Rail", "keywords": ["PURULIA", "ADRA", "RAGHUNATHPUR WB", "JHALDA", "MANBAZAR"]},
        {"district": "Jhargram", "coords": (22.4500, 86.9800), "place": "Jhargram Tribal & CGD Corridor", "keywords": ["JHARGRAM", "BELPAHARI", "GOPABALLAVPUR", "BINPUR"]},
        {"district": "Purba Medinipur", "coords": (21.9300, 87.7700), "place": "Haldia Port & Petrochemicals Complex", "keywords": ["HALDIA", "PURBA MEDINIPUR", "EAST MEDINIPUR", "TAMLUK", "DIGHA", "CONTAI", "KOLAGHAT"]},
        {"district": "Paschim Medinipur", "coords": (22.4200, 87.3200), "place": "IIT Kharagpur & Railway Division", "keywords": ["KHARAGPUR", "PASCHIM MEDINIPUR", "WEST MEDINIPUR", "MIDNAPORE", "MEDINIPUR", "GHATAL"]},
        {"district": "Malda", "coords": (25.0000, 88.1400), "place": "Malda Town Railway Division & Airport", "keywords": ["MALDA", "ENGLISH BAZAR", "CHANCHAL", "GAZOLE", "HABIBPUR"]},
        {"district": "Uttar Dinajpur", "coords": (25.6200, 88.1200), "place": "Raiganj & Dalkhola Highway Corridor", "keywords": ["UTTAR DINAJPUR", "RAIGANJ", "DALKHOLA", "ISLAMPUR WB", "KALIYAGANJ"]},
        {"district": "Dakshin Dinajpur", "coords": (25.2200, 88.7600), "place": "Balurghat Airport & Rail Link", "keywords": ["DAKSHIN DINAJPUR", "BALURGHAT", "GANGARAMPUR", "BUNIADPUR", "HARIRAMPUR"]},
        {"district": "Jalpaiguri", "coords": (26.5200, 88.7300), "place": "Jalpaiguri & Dhupguri Highway Corridor", "keywords": ["JALPAIGURI", "DHUPGURI", "MALBAZAR", "MAYNAGURI", "RAJGANJ"]},
        {"district": "Alipurduar", "coords": (26.4900, 89.5300), "place": "Alipurduar Railway Division & CGD", "keywords": ["ALIPURDUAR", "FALAKATA", "BIRPARA", "JAIGAON", "HASIMARA"]},
        {"district": "Cooch Behar", "coords": (26.3200, 89.4500), "place": "Cooch Behar Airport & Heritage Node", "keywords": ["COOCH BEHAR", "DINHATA", "MATHABHANGA", "TOFANGANJ", "MEKLIGANJ"]},
        {"district": "Kalimpong", "coords": (27.0600, 88.4700), "place": "Sivok-Rangpo Rail Kalimpong Tunnels", "keywords": ["KALIMPONG", "TEESTA", "GORUBATHAN", "PEDONG"]},
    ],
    "CHHATTISGARH": [
        {"district": "Rajnandgaon", "coords": (21.1000, 81.0300), "place": "Rajnandgaon Solar & Industrial Corridor", "keywords": ["RAJNANDGAON", "DONGARGARH", "KHAIRAGARH", "CHHURIYA", "AMBAGARH CHOWKI"]},
        {"district": "Kabirdham", "coords": (22.0100, 81.2500), "place": "Kawardha Sugar & Highway Corridor", "keywords": ["KABIRDHAM", "KAWARDHA", "PANDARIYA", "BODLA", "SAHASPUR LOHARA"]},
        {"district": "Balod", "coords": (20.7300, 81.2000), "place": "Dalli Rajhara Iron Ore Mines", "keywords": ["BALOD", "DALLI RAJHARA", "DALLIRAJHRA", "DALLIRAJHRA- ROWGHAT", "GUNDERDEHI", "SANJARI"]},
        {"district": "Bemetara", "coords": (21.7000, 81.5500), "place": "Bemetara Agriculture & Highway Corridor", "keywords": ["BEMETARA", "SAJA", "BERLA", "NAWAGARH"]},
        {"district": "Dhamtari", "coords": (20.7100, 81.5500), "place": "Gangrel Dam & Raipur-Visakhapatnam Corridor", "keywords": ["DHAMTARI", "KURUD", "NAGRI", "MAGARLOD"]},
        {"district": "Gariaband", "coords": (20.9500, 82.0600), "place": "Gariaband Forest & Mineral Corridor", "keywords": ["GARIABAND", "RAJIM", "CHHURA", "FINGESHWAR", "DEOBHOG"]},
        {"district": "Mahasamund", "coords": (21.1100, 82.1000), "place": "Mahasamund Railway & Highway Node", "keywords": ["MAHASAMUND", "BAGBAHRA", "SARAIPALI", "BASNA", "PITHORA"]},
        {"district": "Baloda Bazar", "coords": (21.6600, 81.9800), "place": "Baloda Bazar Cement Hub of India", "keywords": ["BALODA BAZAR", "BHATAPARA", "SIMGA", "KASDOL", "PALARI"]},
        {"district": "Janjgir-Champa", "coords": (22.0100, 82.5700), "place": "Champa Railway Junction & Thermal Power", "keywords": ["JANJGIR", "CHAMPA", "AKALTARA", "NAWAGARH CG", "PAMGARH"]},
        {"district": "Sakti", "coords": (21.9500, 82.9500), "place": "Sakti Rail & Industrial Node", "keywords": ["SAKTI", "DABHRA", "MALKHARODA", "JAJAEPUR"]},
        {"district": "Sarangarh-Bilaigarh", "coords": (21.5800, 83.0800), "place": "Sarangarh Highway Corridor", "keywords": ["SARANGARH", "BILAIGARH", "BARAMKELA"]},
        {"district": "Gaurela-Pendra-Marwahi", "coords": (22.7500, 81.9000), "place": "Pendra Road Rail Link & Anuppur Border", "keywords": ["GAURELA", "PENDRA", "MARWAHI", "PENDRA ROAD"]},
        {"district": "Mungeli", "coords": (22.0700, 81.6800), "place": "Mungeli Highway & Food Cluster", "keywords": ["MUNGELI", "LORMI", "PATHARIA CG"]},
        {"district": "Surajpur", "coords": (23.2200, 82.8700), "place": "Surajpur Coalfields & Highway", "keywords": ["SURAJPUR", "BISHRAMPUR", "PRATAPPUR", "BHAIYATHAN"]},
        {"district": "Balrampur", "coords": (23.6100, 83.6100), "place": "Balrampur Border & Minerals Node", "keywords": ["BALRAMPUR CG", "RAMANUJGANJ", "KUSMI CG", "WADRAFNAGAR"]},
        {"district": "Koriya", "coords": (23.2500, 82.5500), "place": "Baikunthpur Coalfields & Highway Node", "keywords": ["KORIYA", "KOREA", "BAIKUNTHPUR", "SONHAT"]},
        {"district": "Jashpur", "coords": (22.8800, 84.1400), "place": "Jashpur Tribal & Highway Corridor", "keywords": ["JASHPUR", "KUNKURI", "PATTHALGAON", "BAGICHA"]},
        {"district": "Kanker", "coords": (20.2700, 81.4900), "place": "North Bastar Kanker & Rail Link", "keywords": ["KANKER", "CHARAMA", "BHANUPRATAPPUR", "ANTAGARH", "PAKHANJUR"]},
        {"district": "Kondagaon", "coords": (19.6000, 81.6700), "place": "Kondagaon Bell Metal & NH-30 Corridor", "keywords": ["KONDAGAON", "KESH KAL", "MAKDI", "FARASGAON"]},
        {"district": "Narayanpur", "coords": (19.7200, 81.2500), "place": "Rowghat Iron Ore Mining Rail Link", "keywords": ["NARAYANPUR", "ROWGHAT", "ORCHHA CG", "DALLIRAJHRA- ROWGHAT"]},
        {"district": "Bastar", "coords": (19.0700, 82.0300), "place": "NMDC Steel Plant Nagarnar Jagdalpur", "keywords": ["BASTAR", "JAGDALPUR", "NAGARNAR", "TOKAPAL", "BASTANAR"]},
        {"district": "Dantewada", "coords": (18.9000, 81.3500), "place": "Bailadila Iron Ore Mines NMDC", "keywords": ["DANTEWADA", "BAILADILA", "KIRANDUL", "BACHELE", "GEEDAM", "KATEKALYAN"]},
        {"district": "Bijapur", "coords": (18.8000, 80.8200), "place": "Bijapur Border & Forest Node", "keywords": ["BIJAPUR CG", "BHAIRAMGARH", "BHOPALPATNAM", "USOOR"]},
        {"district": "Sukma", "coords": (18.4000, 81.6700), "place": "Sukma Border & National Highway Node", "keywords": ["SUKMA", "KONTA", "CHINTAGUPHA", "DORNA PAL"]},
    ],
    "JHARKHAND": [
        {"district": "Garhwa", "coords": (24.1800, 83.8000), "place": "Garhwa Rail Junction & Border Corridor", "keywords": ["GARHWA", "NAGAR UNTARI", "BHAWANATHPUR", "MAJHIYAON"]},
        {"district": "Palamu", "coords": (24.0300, 84.0700), "place": "Daltonganj Railway Division & Coal Mines", "keywords": ["PALAMU", "DALTONGANJ", "MEDININAGAR", "HUSSAINABAD", "CHHATARPUR JH"]},
        {"district": "Latehar", "coords": (23.7400, 84.5000), "place": "Tetariakhar OC & Chandwa Coalfields", "keywords": ["LATEHAR", "TETARIAKHAR", "CHANDWA", "BALUMATH", "GARU", "MAHUADANR"]},
        {"district": "Chatra", "coords": (24.2100, 84.8700), "place": "North Karanpura Super Thermal Power Project", "keywords": ["CHATRA", "NORTH KARANPURA", "TANDWA", "SIMARIA", "HUNTERGANJ", "ITARIKHAS"]},
        {"district": "Koderma", "coords": (24.4700, 85.5900), "place": "Koderma Thermal Power Station & Rail Junction", "keywords": ["KODERMA", "JHUMRI TELAIYA", "DOMCHANCH", "JAYNAGAR JH"]},
        {"district": "Giridih", "coords": (24.1800, 86.3000), "place": "Giridih Coal Mining & Parasnath Node", "keywords": ["GIRIDIH", "PARASNATH", "MADHUPUR RAIL", "DUMRI", "BAGODAR", "BENAGARIA"]},
        {"district": "Deoghar", "coords": (24.4800, 86.7000), "place": "Deoghar International Airport & AIIMS", "keywords": ["DEOGHAR", "MADHUPUR", "JASIDIH", "SARATH", "DEVI PUR"]},
        {"district": "Dumka", "coords": (24.2600, 87.2500), "place": "Dumka Sub-Capital & Rail Link", "keywords": ["DUMKA", "JAMA", "SARAIYAHAT", "SHIKARIPARA", "RANISHWAR"]},
        {"district": "Godda", "coords": (24.8300, 87.2100), "place": "Adani Godda Ultra Supercritical Power Plant", "keywords": ["GODDA", "MAHAGAMA", "MEHRMA", "BOARIJOR", "LALMATIA"]},
        {"district": "Sahibganj", "coords": (25.2500, 87.6500), "place": "Sahibganj Multi-Modal Inland Water Terminal", "keywords": ["SAHIBGANJ", "RAJMAHAL", "BARHARWA", "TINPAHAR", "TALJHARI"]},
        {"district": "Pakur", "coords": (24.6300, 87.8500), "place": "Pakur Stone Quarry & Rail Link", "keywords": ["PAKUR", "MAHESHPUR", "HIRANPUR", "LITIPARA", "PAKAUR"]},
        {"district": "Jamtara", "coords": (23.9600, 86.8000), "place": "Mihijam & Chittaranjan Locomotive Border", "keywords": ["JAMTARA", "MIHIJAM", "NUNDA", "KUNDAHIT"]},
        {"district": "Lohardaga", "coords": (23.4300, 84.6800), "place": "Lohardaga Bauxite Mines & Rail Link", "keywords": ["LOHARDAGA", "KUDO", "BHANDRA", "KISKO", "KAIRO"]},
        {"district": "Gumla", "coords": (23.0400, 84.5400), "place": "Gumla Bauxite Mining & Highway Corridor", "keywords": ["GUMLA", "GHAGHRA", "CHAINPUR JH", "RAIDIH", "SISAI"]},
        {"district": "Simdega", "coords": (22.6100, 84.5100), "place": "Simdega Sports & Border Highway", "keywords": ["SIMDEGA", "KOLEBIRA", "BANO", "KURDEG", "BOLBA"]},
        {"district": "Khunti", "coords": (23.0700, 85.2800), "place": "Khunti Highway & Tribal Node", "keywords": ["KHUNTI", "TORPA", "MURHU", "KARRA", "RANIA"]},
        {"district": "Saraikela Kharsawan", "coords": (22.7000, 85.9300), "place": "Adityapur Industrial Area & DFC", "keywords": ["SARAIKELA", "KHARSAWAN", "ADITYAPUR", "GAMHARIA", "CHANDIL"]},
        {"district": "West Singhbhum", "coords": (22.5800, 85.8100), "place": "Chaiabasa & Gua Iron Ore Mines", "keywords": ["CHAIBASA", "WEST SINGHBHUM", "GUA", "NOAMUNDI", "KIRIBURU", "CHAKRADHARPUR"]},
    ],
    "TAMIL NADU": [
        {"district": "Chengalpattu", "coords": (12.6939, 79.9756), "place": "Mahabalipuram & Mahindra World City SEZ", "keywords": ["CHENGALPATTU", "MAHINDRA WORLD CITY", "MARAIMALAI NAGAR", "TAMBARAM", "PALLAVARAM", "VANDALUR"]},
        {"district": "Kanchipuram", "coords": (12.8342, 79.7036), "place": "Sriperumbudur Industrial Auto Cluster", "keywords": ["KANCHIPURAM", "SRIPERUMBUDUR", "ORAGADAM", "WALAJABAD", "UTTIRAMERUR"]},
        {"district": "Tiruvallur", "coords": (13.1439, 79.9083), "place": "Kamarajar Port Ennore & Gummidipoondi", "keywords": ["TIRUVALLUR", "ENNORE", "GUMMIDIPOONDI", "AVADI", "PONNERI", "MINJUR"]},
        {"district": "Ranipet", "coords": (12.9228, 79.3328), "place": "Ranipet Leather SEZ & Highway Corridor", "keywords": ["RANIPET", "ARAKKONAM", "WALAJAPET", "SHOLINGHUR", "NEMILI"]},
        {"district": "Vellore", "coords": (12.9165, 79.1325), "place": "Vellore Airport & Industrial Corridor", "keywords": ["VELLORE", "KATPADI", "GUDIYATHAM", "ANAICUT"]},
        {"district": "Tirupathur", "coords": (12.4961, 78.5667), "place": "Jolarpettai Rail Junction & Tirupathur", "keywords": ["TIRUPATHUR", "JOLARPETTAI", "VANIYAMBADI", "AMBUR", "NATRAMPALLI"]},
        {"district": "Tiruvannamalai", "coords": (12.2253, 79.0747), "place": "Tiruvannamalai Highway & SIPCOT Node", "keywords": ["TIRUVANNAMALAI", "ARANI", "CHENGAM", "POLUR", "VANDAVASI"]},
        {"district": "Viluppuram", "coords": (11.9401, 79.4861), "place": "Viluppuram Railway Junction & Highway", "keywords": ["VILUPPURAM", "TINDIVANAM", "VIKRAVANDI", "GINGEE", "VALAVANUR"]},
        {"district": "Cuddalore", "coords": (11.7480, 79.7714), "place": "NLC India Neyveli Lignite Power Complex", "keywords": ["CUDDALORE", "NEYVELI", "NLC", "VRIDDHACHALAM", "PANRUTI", "CHIDAMBARAM"]},
        {"district": "Dharmapuri", "coords": (12.1211, 78.1582), "place": "Dharmapuri Highway & Food Processing", "keywords": ["DHARMAPURI", "HARUR", "PALAKKODU", "PENNAGARAM", "PAPPIREDDIPATTI"]},
        {"district": "Krishnagiri", "coords": (12.5186, 78.2137), "place": "Hosur Electronics & EV Manufacturing Hub", "keywords": ["KRISHNAGIRI", "HOSUR", "POCHAMPALLI", "DENKANIKOTTAI", "BARGUR"]},
        {"district": "Erode", "coords": (11.3410, 77.7172), "place": "Erode Textile Hub & Locomotive Shed", "keywords": ["ERODE", "PERUNDURAI", "BHAVANI", "GOBICHETTIPALAYAM", "SATHYAMANGALAM"]},
        {"district": "Tiruppur", "coords": (11.1085, 77.3411), "place": "Tiruppur Knitwear Export Capital", "keywords": ["TIRUPPUR", "AVINASHI", "PALLADAM", "DHARAPURAM", "UDUMALAIPETTAI", "KANGEYAM"]},
        {"district": "The Nilgiris", "coords": (11.4102, 76.6950), "place": "Ooty Mountain Railway & Wellington", "keywords": ["NILGIRIS", "OOTY", "UDHAGAMANDALAM", "COONOOR", "KOTAGIRI", "GUDALUR"]},
        {"district": "Dindigul", "coords": (10.3673, 77.9803), "place": "Dindigul Rail Junction & Lock Cluster", "keywords": ["DINDIGUL", "PALANI", "KODAIKANAL", "ODDANCHATRAM", "NILAKKOTTAI"]},
        {"district": "Karur", "coords": (10.9601, 78.0766), "place": "Karur Textile Export & Paper Mill", "keywords": ["KARUR", "KULITHALAI", "ARAVAKURICHI", "PUGALUR", "KRISHNARAYAPURAM"]},
        {"district": "Ariyalur", "coords": (11.1401, 79.0786), "place": "Ariyalur Cement Capital of Tamil Nadu", "keywords": ["ARIYALUR", "UDAYARPALAYAM", "SENDURAI", "ANDIMADAM"]},
        {"district": "Nagapattinam", "coords": (10.7672, 79.8449), "place": "Nagapattinam Port & CPCL Refinery", "keywords": ["NAGAPATTINAM", "CPCL REFINERY", "VELANKANNI", "KILVELUR", "THIRUKKUVALAI"]},
        {"district": "Mayiladuthurai", "coords": (11.1018, 79.6522), "place": "Mayiladuthurai Rail Junction & Heritage", "keywords": ["MAYILADUTHURAI", "SIRKAZHI", "THARANGAMBADI", "KUTHALLAM"]},
        {"district": "Thanjavur", "coords": (10.7870, 79.1378), "place": "Thanjavur Air Force Station & Rice Bowl", "keywords": ["THANJAVUR", "KUMBAKONAM", "PATTUKKOTTAI", "ORATHANADU", "THIRUVAIYARU"]},
        {"district": "Pudukkottai", "coords": (10.3833, 78.8000), "place": "Pudukkottai SIPCOT & Highway Node", "keywords": ["PUDUKKOTTAI", "ARANTHANGI", "VIRALIMALAI", "GANDARVAKKOTTAI", "ALANGUDI"]},
        {"district": "Ramanathapuram", "coords": (9.3639, 78.8395), "place": "Rameshwaram New Pamban Sea Bridge", "keywords": ["RAMANATHAPURAM", "RAMESHWARAM", "PAMBAN", "PARAMAKUDI", "KILAKARAI", "MANDAPAM"]},
        {"district": "Virudhunagar", "coords": (9.5680, 77.9624), "place": "Sivakasi Fireworks & Virudhunagar Industrial", "keywords": ["VIRUDHUNAGAR", "SIVAKASI", "RAJAPALAYAM", "ARUPPUKKOTTAI", "SATTUR"]},
        {"district": "Theni", "coords": (10.0104, 77.4768), "place": "Theni Highway & Bodi Broad Gauge Line", "keywords": ["THENI", "BODINAYAKANUR", "PERIYAKULAM", "ANDIPATTI", "UTHAMAPALAYAM"]},
        {"district": "Tenkasi", "coords": (8.9594, 77.3150), "place": "Tenkasi Rail Junction & Courtallam", "keywords": ["TENKASI", "SANKARANKOVIL", "KADAYANALLUR", "ALANGULAM", "SHENCOTTAH"]},
        {"district": "Thoothukudi", "coords": (8.7642, 78.1348), "place": "VO Chidambaranar Port (Tuticorin)", "keywords": ["THOOTHUKUDI", "TUTICORIN", "VOC PORT", "KOVILPATTI", "TIRUCHENDUR", "OTTAPIDARAM"]},
        {"district": "Tirunelveli", "coords": (8.7139, 77.7567), "place": "Kudankulam Nuclear Power Plant & ISRO", "keywords": ["TIRUNELVELI", "KUDANKULAM", "MAHENDRAGIRI", "AMBASAMUDRAM", "NANGUNERI"]},
        {"district": "Kanniyakumari", "coords": (8.0883, 77.5385), "place": "Kanyakumari International Container Transhipment", "keywords": ["KANNIYAKUMARI", "KANYAKUMARI", "NAGERCOIL", "PADMANABHAPURAM", "THUCKALAY", "KULITTHURAI"]},
    ],
    "TELANGANA": [
        {"district": "Jagtial", "coords": (18.7967, 78.9133), "place": "Jagtial Highway & Agriculture Corridor", "keywords": ["JAGTIAL", "KORATLA", "METPALLY", "DHARMAPURI TG", "RAIKAL"]},
        {"district": "Peddapalli", "coords": (18.6167, 79.3833), "place": "NTPC Ramagundam & RFCL Fertilizer Plant", "keywords": ["PEDDAPALLI", "RAMAGUNDAM", "NTPC RAMAGUNDAM", "RFCL", "SULTANABAD", "MANTHANI"]},
        {"district": "Jayashankar Bhupalpally", "coords": (18.4300, 79.8600), "place": "KTPS & Bhupalpally Coal Mining Area", "keywords": ["BHUPALPALLY", "JAYASHANKAR", "CHITYAL", "TEKUMATLA", "MALHAR RAO"]},
        {"district": "Bhadradri Kothagudem", "coords": (17.5500, 80.6100), "place": "Kothagudem Thermal Power & SCCL Mines", "keywords": ["KOTHAGUDEM", "BHADRADRI", "BHADRACHALAM", "PALONCHA", "YELLANDU", "MANUGURU"]},
        {"district": "Mahabubabad", "coords": (17.6000, 80.0000), "place": "Mahabubabad Railway Junction & Highway", "keywords": ["MAHABUBABAD", "DORNAKAL", "MARIPEDA", "KESAMUDRAM", "KURAVI"]},
        {"district": "Warangal", "coords": (17.9689, 79.5941), "place": "Kakatiya Mega Textile Park Warangal", "keywords": ["WARANGAL", "KAZIPET", "GEESUGONDA", "WARDHANNAPET", "NARSAMPET"]},
        {"district": "Hanamkonda", "coords": (18.0167, 79.5500), "place": "NIT Warangal & Smart City Node", "keywords": ["HANAMKONDA", "NIT WARANGAL", "HASANPARTHY", "ELKATHURTHY"]},
        {"district": "Jangaon", "coords": (17.7200, 79.1800), "place": "Jangaon Highway & Industrial Corridor", "keywords": ["JANGAON", "STATION GHANPUR", "PALAKURTHY", "BACHANNAPET"]},
        {"district": "Siddipet", "coords": (18.1000, 78.8500), "place": "Kaleshwaram Project Ranganayaka Sagar", "keywords": ["SIDDIPET", "GAJWEL", "DUBBAK", "HUSAINABAD", "MULUGU"]},
        {"district": "Medak", "coords": (18.0500, 78.2600), "place": "Medak Ordnance Factory & Rail Link", "keywords": ["MEDAK", "NARSAPUR", "RAMAYAMPET", "ALLADURG", "SHANKARAMPET"]},
        {"district": "Kamareddy", "coords": (18.3200, 78.3400), "place": "Kamareddy Rail & Highway Junction", "keywords": ["KAMAREDDY", "BANSWADA", "YELLAREDDY", "DOMAKONDA"]},
        {"district": "Nizamabad", "coords": (18.6725, 78.0941), "place": "Nizamabad IT Hub & Spice Park", "keywords": ["NIZAMABAD", "BODHAN", "ARMOOR", "DICHPALLY", "BALKONDA"]},
        {"district": "Nirmal", "coords": (19.1000, 78.3500), "place": "Kadam Dam & Nirmal Highway Corridor", "keywords": ["NIRMAL", "BHAINSA", "KHANAPUR TG", "SARANGAPUR"]},
        {"district": "Komaram Bheem Asifabad", "coords": (19.3600, 79.2800), "place": "Asifabad Tribal & Mineral Corridor", "keywords": ["ASIFABAD", "KOMARAM BHEEM", "KAGHAZNAGAR", "SIRPUR", "REBBENA"]},
        {"district": "Adilabad", "coords": (19.6667, 78.5333), "place": "Adilabad Airport & Cotton SEZ", "keywords": ["ADILABAD", "BELA", "JAINATH", "UTNOOR", "BOATH"]},
        {"district": "Rajanna Sircilla", "coords": (18.3800, 78.8300), "place": "Sircilla Apparel Park & Textile Zone", "keywords": ["SIRCILLA", "RAJANNA SIRCILLA", "VEMULAWADA", "YELLAREDDYPET"]},
        {"district": "Yadadri Bhuvanagiri", "coords": (17.5100, 78.8800), "place": "Yadadri Thermal Power Project 4000 MW", "keywords": ["YADADRI", "BHUVANAGIRI", "BHONGIR", "DAMERACHERLA", "ALAIR", "CHOUTUPPAL"]},
        {"district": "Suryapet", "coords": (17.1400, 79.6200), "place": "Suryapet Vijayawada Highway Corridor", "keywords": ["SURYAPET", "KODAD", "HUZURNAGAR", "THUNGATHURTHY", "MELLACHERUVU"]},
        {"district": "Nalgonda", "coords": (17.0500, 79.2700), "place": "Nagarjuna Sagar Dam & Nalgonda Highway", "keywords": ["NALGONDA", "MIRYALGUDA", "DEVARAKONDA", "NAGARJUNA SAGAR", "NAKREKAL"]},
        {"district": "Mahabubnagar", "coords": (16.7488, 77.9856), "place": "Divitipally IT SEZ & Highway Corridor", "keywords": ["MAHABUBNAGAR", "JADCHERLA", "BHOOTPUR", "DEVARKADRA", "MIDJIL"]},
        {"district": "Nagarkurnool", "coords": (16.4800, 78.3300), "place": "Srisailam Left Bank Power & Kalwakurthy", "keywords": ["NAGARKURNOOL", "KALWAKURTHY", "ACHAMPET", "KOLLAPUR", "SRISAILAM LEFT BANK"]},
        {"district": "Wanaparthy", "coords": (16.3600, 78.0600), "place": "Wanaparthy Highway & Agriculture Node", "keywords": ["WANAPARTHY", "KOTHAKOTA", "PEBBAIR", "PANAGAL"]},
        {"district": "Jogulamba Gadwal", "coords": (16.2300, 77.7700), "place": "Gadwal Rail Junction & Tungabhadra Node", "keywords": ["GADWAL", "JOGULAMBA", "ALAMPUR", "IERUKU", "MALDAKAL"]},
        {"district": "Vikarabad", "coords": (17.3300, 77.9000), "place": "Vikarabad Rail Corridor & Tandur Cements", "keywords": ["VIKARABAD", "TANDUR", "PARGI", "KODANGAL", "MOMINPET"]},
    ],
}

print("Loaded all additional districts.")
