"""
scripts/india_authoritative_gazetteer.py
Authoritative All-India District, Place & Facility Gazetteer for MoSPI PAIMANA April 2026.
Contains comprehensive districts for all 36 States and Union Territories.
"""

AUTHORITATIVE_GAZETTEER = {
    "BIHAR": [
        {"district": "Patna", "coords": (25.5941, 85.1376), "place": "Bihta Airport & Patna Metro", "keywords": ["PATNA", "BIHTA", "DANAPUR", "DIDARGANJ", "FATUHA", "PATLIPUTRA", "PHULWARI"]},
        {"district": "Begusarai", "coords": (25.4184, 86.1272), "place": "Barauni Refinery & Fertilizer Complex", "keywords": ["BARAUNI", "BEGUSARAI", "TEGHRA", "BAKHRI"]},
        {"district": "Gaya", "coords": (24.7914, 85.0002), "place": "Dobhi Industrial Node (AKIC)", "keywords": ["DOBHI", "GAYA", "BODHGAYA", "SHERGATI", "MANPUR"]},
        {"district": "Bhagalpur", "coords": (25.2425, 87.0139), "place": "Vikramshila 4-Lane Ganga Bridge", "keywords": ["BHAGALPUR", "VIKRAMSHILA", "KAHALGAON", "SULTANGANJ", "NTPC KAHALGAON"]},
        {"district": "Muzaffarpur", "coords": (26.1209, 85.3647), "place": "Kanti Power & 4-Lane Highway", "keywords": ["MUZAFFARPUR", "KANTI", "MOTIPUR", "KUDHNI"]},
        {"district": "Darbhanga", "coords": (26.1542, 85.8918), "place": "Darbhanga Airport & AIIMS", "keywords": ["DARBHANGA", "KABIR CHAK", "BAHERA", "BENIPUR"]},
        {"district": "Vaishali", "coords": (25.6858, 85.2146), "place": "Hajipur Rail Zonal Headquarters", "keywords": ["HAJIPUR", "VAISHALI", "MAHNAR", "LALGANJ"]},
        {"district": "Rohtas", "coords": (24.9500, 84.0300), "place": "Sasaram Dedicated Freight Corridor", "keywords": ["SASARAM", "ROHTAS", "DEHRI", "DALMIANAGAR"]},
        {"district": "Purnia", "coords": (25.7771, 87.4753), "place": "Purnia Airport & Highway Node", "keywords": ["PURNIA", "PURNEA", "KASBA", "BANMANKHI"]},
        {"district": "Saran", "coords": (25.7796, 84.7499), "place": "Chapra Wheel Plant & Sonepur Rail", "keywords": ["SARAN", "CHAPRA", "SONEPUR", "MARHAURA"]},
        {"district": "Bhojpur", "coords": (25.5702, 84.4616), "place": "Arrah Rail Bridge Corridor", "keywords": ["ARRAH", "BHOJPUR", "KOILWAR", "BIHIYA"]},
        {"district": "Nalanda", "coords": (25.1315, 85.4476), "place": "Rajgir Tourism & Highway", "keywords": ["NALANDA", "RAJGIR", "BIHAR SHARIF", "HARNAUT"]},
        {"district": "East Champaran", "coords": (26.6580, 84.9100), "place": "Motihari Highway & ICP Raxaul", "keywords": ["MOTIHARI", "RAXAUL", "CHAMPARAN", "ARERAJ"]},
        {"district": "West Champaran", "coords": (27.0000, 84.3667), "place": "Bettiah Narkatiaganj Corridor", "keywords": ["BETTIAH", "NARKATIAGANJ", "BAGAHA"]},
        {"district": "Katihar", "coords": (25.5394, 87.5667), "place": "Katihar Railway Junction", "keywords": ["KATIHAR", "BARSOI", "MANIHARI"]},
        {"district": "Madhubani", "coords": (26.3568, 86.0712), "place": "Jaynagar Nepal Border Rail", "keywords": ["MADHUBANI", "JAYNAGAR", "BIJALPURA", "JHANJHARPUR"]},
        {"district": "Buxar", "coords": (25.5600, 83.9800), "place": "Chausa Buxar Thermal Power Project", "keywords": ["BUXAR", "CHAUSA", "DUMRAON", "BRAHMPUR"]},
    ],
    "GUJARAT": [
        {"district": "Patan", "coords": (23.8347, 71.3094), "place": "Santalpur & Patan NH-27 Corridor", "keywords": ["SANTALPUR", "RADHANPUR", "PATAN", "SAMAKHIYALI TO SANTALPUR", "SANCHORE - SANTALPUR", "GOJARIYA", "RAJPUR"]},
        {"district": "Ahmedabad", "coords": (22.2500, 72.1900), "place": "Dholera Smart City & Expressway", "keywords": ["DHOLERA", "SIR DHOLERA", "DHOLERA AIRPORT", "DHOLERA EXPRESSWAY", "SABARMATI", "AHMEDABAD", "SANAND", "VIRAMGAM", "BAWLA", "SARKHEJ", "LOTHAL", "BAGODARA"]},
        {"district": "Surat", "coords": (21.1702, 72.8311), "place": "Hazira Petrochem & Surat Metro", "keywords": ["SURAT", "HAZIRA", "SACHIN", "BARDOLI", "PALSANA", "OLPAD", "KIM", "KOSAMBA"]},
        {"district": "Kutch", "coords": (23.2500, 69.6700), "place": "Kandla Port & Khavda 30 GW Park", "keywords": ["KANDLA", "DEENDAYAL PORT", "TUNA-TEKRA", "MUNDRA", "KHAVDA", "KUTCH HYBRID", "BHUJ", "SAMAKHIYALI", "KUTCH", "NALIYA", "JAKHAU", "LAKHPAT", "KPS1", "KPS2"]},
        {"district": "Vadodara", "coords": (22.3072, 73.1812), "place": "Koyali Refinery & Bullet Train Depot", "keywords": ["VADODARA", "BARODA", "KOYALI", "MANJUSAR", "SAVLI", "PADRA", "KARJAN", "DABHOI"]},
        {"district": "Bharuch", "coords": (21.7051, 72.9959), "place": "Dahej PCPIR Petrochemical SEZ", "keywords": ["DAHEJ", "BHARUCH", "ANKLESHWAR", "PCPIR", "JAGHADIA", "VALIA", "JAMBUSAR"]},
        {"district": "Jamnagar", "coords": (22.4707, 70.0577), "place": "Moti Khavdi & Sikka Petrochem Complex", "keywords": ["JAMNAGAR", "MOTI KHAVDI", "SIKKA", "BEDI", "RELIANCE JAMNAGAR"]},
        {"district": "Rajkot", "coords": (22.3039, 70.8022), "place": "Hirasar International Airport & AIIMS", "keywords": ["RAJKOT", "HIRASAR", "METODA", "SHAPAR", "GONDAL", "JETPUR"]},
        {"district": "Gandhinagar", "coords": (23.2156, 72.6369), "place": "GIFT City & Mahatma Mandir", "keywords": ["GANDHINAGAR", "GIFT CITY", "KALOL", "MANSA", "KUDASAN"]},
        {"district": "Bhavnagar", "coords": (21.7645, 72.1519), "place": "Bhavnagar Port & Alang Ship Recycling", "keywords": ["BHAVNAGAR", "ALANG", "TALAJA", "MAHUVA", "SIHOR"]},
        {"district": "Morbi", "coords": (22.8120, 70.8378), "place": "Morbi Ceramic SEZ & Highway", "keywords": ["MORBI", "WANKANER", "MALIYA", "HALVAD"]},
        {"district": "Banaskantha", "coords": (24.1720, 72.4346), "place": "Palanpur & Ambaji Rail Corridor", "keywords": ["BANASKANTHA", "RAGHANESDA", "PALANPUR", "DISA", "DEESA", "DANTA", "AMBAJI", "THARAD"]},
        {"district": "Sabarkantha", "coords": (23.6000, 72.9500), "place": "Himmatnagar & Idar Corridor", "keywords": ["SABARKANTHA", "HIMMATNAGAR", "PRANTIJ"]},
        {"district": "Narmada", "coords": (21.8700, 73.7200), "place": "Sardar Sarovar & Statue of Unity", "keywords": ["SARDAR SAROVAR", "NARMADA", "KEVADIA", "EKTA NAGAR", "RAJPIPLA"]},
        {"district": "Junagadh", "coords": (21.5222, 70.4579), "place": "Keshod Airport & Junagadh Tourism Corridor", "keywords": ["KESHOD", "JUNAGADH", "MANAVADAR", "VISAVADAR", "MANGROL"]},
        {"district": "Devbhumi Dwarka", "coords": (22.2442, 68.9685), "place": "Jam Khambhaliya PS & Dwarka Port", "keywords": ["KHAMBHALIYA", "JAM KHAMBHALIYA", "DWARKA", "OKHA", "KALYANPUR GUJARAT"]},
        {"district": "Mehsana", "coords": (23.5880, 72.3693), "place": "Mehsana Industrial & ONGC Asset", "keywords": ["MEHSANA", "BECHRAJI", "KHERALU", "SATLASANA", "DHAROI", "VADNAGAR", "VISNAGAR", "KADI"]},
    ],
    "KARNATAKA": [
        {"district": "Bengaluru Urban", "coords": (12.9716, 77.5946), "place": "Bengaluru Metro & Tech Hub", "keywords": ["BANGALORE", "BENGALURU", "BMRCL", "YELAHANKA", "WHITEFIELD", "ELECTRONIC CITY", "KENGERI", "HEBBAL", "PEENYA", "BYAPPANAHALLI", "BOMMASANDRA", "KRISHNARAJAPURAM", "K R PURAM", "MAJESTIC", "YESHWANTHPUR", "KADUGODI", "CHIKKABANAVARA", "CANTONMENT"]},
        {"district": "Bengaluru Rural", "coords": (13.2300, 77.5700), "place": "Bengaluru Rural Logistics Corridor", "keywords": ["DEVANAHALLI", "NELAMANGALA", "DODDABALLAPUR", "HOSKOTE", "KIAL"]},
        {"district": "Ramanagara", "coords": (12.7150, 77.2810), "place": "Harohalli & Ramanagara Industrial Corridor", "keywords": ["RAMANAGARA", "HAROHALLI", "CHANNAPATNA", "MAGADI", "KANAKAPURA", "BIDADI"]},
        {"district": "Dharwad", "coords": (15.3647, 75.1240), "place": "Hubballi-Dharwad Twin City & Airport", "keywords": ["HUBBALLI", "HUBBALI", "HUBLI", "DHARWAD", "NAVALGUND", "ALNAVAR", "KUNDGOL", "HEBSUR"]},
        {"district": "Belagavi", "coords": (15.8497, 74.4977), "place": "Belagavi Industrial & Smart City Node", "keywords": ["BELAGAVI", "BELGAUM", "BELGAVI", "GOKAK", "CHIKODI", "BAILHONGAL", "SAUNDATTI", "RAMDURG", "ATHANI", "NIPANI", "HUKKERI", "KHANAPUR", "SAMBRA"]},
        {"district": "Koppal", "coords": (15.3533, 76.1550), "place": "Koppal Renewable Energy Substation Complex", "keywords": ["KOPPAL", "KOPPAL-II", "KOPPAL-2", "GANGAVATHI", "KUSHTAGI", "YELBURGA", "TAVARAGERA", "MUNIRABAD"]},
        {"district": "Gadag", "coords": (15.4319, 75.6355), "place": "Gadag Wind-Solar Hybrid Corridor", "keywords": ["GADAG", "GADAGII", "GADAG-II", "GADAG-2", "BETAGERI", "RONA", "SHIRHATTI", "MUNDARGI", "NARAGUND", "LAKSHMESHWAR"]},
        {"district": "Davanagere", "coords": (14.4644, 75.9218), "place": "Davanagere Transmission & Textile Hub", "keywords": ["DAVANAGERE", "DAVANGERE", "HARIHAR", "CHANNAGIRI", "HONNALI", "JAGALUR", "NYAMATHI"]},
        {"district": "Ballari", "coords": (15.1394, 76.9214), "place": "Ballari Steel & Solar Energy Park", "keywords": ["BELLARY", "BALLARI", "SANDUR", "SIRUGUPPA", "TORANAGALLU", "HOSAPETE", "KAMPLI", "KUDATINI"]},
        {"district": "Vijayanagara", "coords": (15.2700, 76.3900), "place": "Vijayanagara Industrial & Tourism Node", "keywords": ["VIJAYANAGARA", "VIJAYANAGAR", "HOSPET", "HAMPI", "HARAPANAHALLI", "HOOVINA HADAGALI", "KOTTURU"]},
        {"district": "Chitradurga", "coords": (14.2251, 76.4019), "place": "Chitradurga Renewable Power Evacuation", "keywords": ["CHITRADURGA", "CHALLAKERE", "HIRIYUR", "HOLALKERE", "HOSADURGA", "MOLAKALMURU"]},
        {"district": "Tumakuru", "coords": (13.3379, 77.1006), "place": "Tumakuru Industrial Smart City (CBIC)", "keywords": ["TUMKUR", "TUMAKURU", "VASANTHANARASAPURA", "SIRA", "TIPTUR", "MADHUGIRI", "PAVAGADA", "KUNIGAL", "GUBBI", "TURUVEKERE", "CHIKKANAYAKANAHALLI"]},
        {"district": "Dakshina Kannada", "coords": (12.8703, 74.8806), "place": "New Mangalore Port & Petrochemicals (MRPL)", "keywords": ["MANGALORE", "MANGALURU", "MRPL", "PANAMBUR", "BANTWAL", "PUTTUR", "BELTHANGADY", "SULLIA", "ULLAL", "BAJPE", "SURATHKAL", "KADRI"]},
        {"district": "Udupi", "coords": (13.3409, 74.7421), "place": "Udupi Coastal Power & Highway Node", "keywords": ["UDUPI", "MANIPAL", "MALPE", "KUNDAPURA", "KARKALA", "PADUBIDRI", "BYNDOOR", "HEJAMADI", "BRAHMAVAR"]},
        {"district": "Uttara Kannada", "coords": (14.8185, 74.1416), "place": "Karwar Naval Base & Port Node", "keywords": ["KARWAR", "ANKOLA", "KUMTA", "HONNAVAR", "BHATKAL", "SIRSI", "DANDELLI", "KAIGA", "YELLAPUR", "HALIYAL", "JOIDA"]},
        {"district": "Shivamogga", "coords": (13.9299, 75.5681), "place": "Shivamogga Airport & Rail Infrastructure", "keywords": ["SHIVAMOGGA", "SHIMOGA", "BHADRAVATI", "SAGARA", "SHIKARIPURA", "SORABA", "TIRTHAHALLI", "HOSANAGARA"]},
        {"district": "Mysuru", "coords": (12.2958, 76.6394), "place": "Mysuru Multi-Modal Railway Hub", "keywords": ["MYSURU", "MYSORE", "NANJANAGUD", "HUNSUR", "T NARASIPURA", "HEGGADADEVANAKOTE", "K R NAGARA", "PERIYAPATNA"]},
        {"district": "Mandya", "coords": (12.5218, 76.8951), "place": "Mandya Expressway & Agritech Node", "keywords": ["MANDYA", "MADDUR", "MALAVALLI", "SRIRANGAPATNA", "PANDAVAPURA", "NAGAMANGALA", "K R PET"]},
        {"district": "Hassan", "coords": (13.0033, 76.1004), "place": "Hassan Industrial Corridor & Yettinahole", "keywords": ["HASSAN", "YETTINAHOLE", "CHANNARAYAPATNA", "ARASIKERE", "ALUR", "ARKALGUD", "BELUR", "SAKLESHPUR", "SHRAVANABELAGOLA"]},
        {"district": "Kalaburagi", "coords": (17.3297, 76.8343), "place": "Kalaburagi Airport & Cement Cluster", "keywords": ["GULBARGA", "KALABURAGI", "SEDAM", "WADI", "CHITTAPUR", "ALAND", "AFZALPUR", "JEWARGI", "CHINCHOLI"]},
        {"district": "Vijayapura", "coords": (16.8302, 75.7100), "place": "Vijayapura Airport & NTPC Kudgi", "keywords": ["BIJAPUR", "VIJAYAPURA", "KUDGI", "INDI", "SINDAGI", "BASAVANA BAGEWADI", "MUDDEBIHAL", "CHADCHAN", "TIKOTA"]},
        {"district": "Bidar", "coords": (17.9104, 77.5199), "place": "Bidar Air Force & Express Node", "keywords": ["BIDAR", "HUMNABAD", "BHALKI", "AURAD", "BASAVAKALYAN", "KAMALNAGAR"]},
        {"district": "Raichur", "coords": (16.2076, 77.3463), "place": "Raichur Thermal Power & Mining Hub", "keywords": ["RAICHUR", "RTPS", "YERMARUS", "SINDHANUR", "MANVI", "DEODURGA", "LINGASUGUR", "MASKI", "SIRWAR"]},
        {"district": "Kolar", "coords": (13.1367, 78.1291), "place": "Kolar Industrial Cluster & KGF", "keywords": ["KOLAR", "KGF", "BANGARAPET", "MALUR", "SRINIVASPUR", "MULBAGAL"]},
        {"district": "Chikkaballapur", "coords": (13.4355, 77.7275), "place": "Chikkaballapur Space & Highway Corridor", "keywords": ["CHIKKABALLAPUR", "CHIKBALLAPUR", "GAURIBIDANUR", "BAGEPALLI", "CHINTAMANI", "SIDLAGHATTA", "GUDIBANDE"]},
        {"district": "Chamarajanagar", "coords": (11.9261, 76.9437), "place": "Chamarajanagar Border Corridor", "keywords": ["CHAMARAJANAGAR", "GUNDLUPET", "KOLLEGAL", "YELANDUR", "HANUR"]},
        {"district": "Bagalkot", "coords": (16.1691, 75.6615), "place": "Bagalkot Upper Krishna Project Hub", "keywords": ["BAGALKOT", "BAGALKOTE", "BADAMI", "JAMKHANDI", "MUDHOL", "ILKAL", "BILAGI", "HUNAGUND", "GULEDGUDDA"]},
        {"district": "Yadgir", "coords": (16.7628, 77.1442), "place": "Yadgir Industrial Node", "keywords": ["YADGIR", "SHAHAPUR", "SHORAPUR", "HUNSAGI", "GURMITKAL", "WADGERA"]},
        {"district": "Haveri", "coords": (14.7954, 75.3991), "place": "Haveri Rail & Highway Node", "keywords": ["HAVERI", "RANEBENNUR", "BYADGI", "HANGAL", "SHIGGAON", "HIREKERUR", "SAVANUR"]},
        {"district": "Kodagu", "coords": (12.4244, 75.7382), "place": "Madikeri Tourism & Highway Node", "keywords": ["KODAGU", "COORG", "MADIKERI", "VIRAJPET", "SOMWARPET", "KUSHALNAGAR"]},
        {"district": "Chikkamagaluru", "coords": (13.3161, 75.7720), "place": "Chikkamagaluru Rail & Highway", "keywords": ["CHIKKAMAGALURU", "CHIKMAGALUR", "TARIKERE", "KADUR", "MUDIGERE", "KOPPA", "SRINGERI", "NR PURA"]},
    ],
    "UTTAR PRADESH": [
        {"district": "Prayagraj", "coords": (25.4358, 81.8463), "place": "Jasra Bypass & Prayagraj Ring Road", "keywords": ["JASRA", "PRAYAGRAJ", "ALLAHABAD", "NAINI", "PHAPHAMAU", "JHUSI", "SORAON", "KARCHANA", "HANDIA", "SHANKARGARH", "BARA PRAYAGRAJ"]},
        {"district": "Raebareli", "coords": (26.2236, 81.2409), "place": "Raebareli Ring Road & Rail Coach Factory", "keywords": ["RAEBARELI", "RAE BARELI", "LALGANJ", "SALON", "DALMAU", "MAHARAJGANJ", "UNCHAHAR", "BACHHRAWAN"]},
        {"district": "Balrampur", "coords": (27.4300, 82.1800), "place": "Balrampur Bypass & Highway NH-330", "keywords": ["BALRAMPUR", "TULSIPUR", "UTRAULA", "GAURA CHAUHAN", "PACHPEDI"]},
        {"district": "Pratapgarh", "coords": (25.9000, 81.9800), "place": "Pratapgarh Bypass NH-31 to NH-330", "keywords": ["PRATAPGARH", "BELA PRATAPGARH", "KUNDA", "PATTI", "RANIGANJ", "LALGANJ AJHARA"]},
        {"district": "Amethi", "coords": (26.1558, 81.8153), "place": "Amethi Bypass & Jagdishpur Industrial Area", "keywords": ["AMETHI", "JAGDISHPUR", "JAIS", "GAURIGANJ", "MUSAFIRKHANA", "TILOI"]},
        {"district": "Jaunpur", "coords": (25.7464, 82.6837), "place": "Mariahu Bypass & Jaunpur Hub", "keywords": ["JAUNPUR", "MARIAHU", "SHAHGANJ", "BADLAPUR", "MACHHLISHAHR", "KERAKAT", "ZAFARABAD"]},
        {"district": "Siddharthnagar", "coords": (27.2917, 82.8167), "place": "Shohratgarh Bypass & Siddharthnagar Rail", "keywords": ["SIDDHARTHNAGAR", "SHOHRATGARH", "NAUGARH", "BANSI", "ITWA", "DOMARIYAGANJ", "BARHNI"]},
        {"district": "Mirzapur", "coords": (25.1337, 82.5644), "place": "Chunar Junction & Mirzapur Terminal", "keywords": ["CHUNAR", "MIRZAPUR", "VINDHYACHAL", "LALGANJ MIRZAPUR", "MARIHAN", "CHILH", "KACHHWA"]},
        {"district": "Sonbhadra", "coords": (24.2000, 83.0300), "place": "Chopan Doubling & Singrauli Thermal Stage-III", "keywords": ["CHOPAN", "SONBHADRA", "SONEBHADRA", "ROBERTSGANJ", "ANPARA", "OBRA", "SHAKTINAGAR", "RENUKOOT", "DUDHI", "SINGRAULI SUPER THERMAL", "SINGRAULI STAGE-III", "SINGRAULI STPS", "RIHAND", "GHORAWAL"]},
        {"district": "Varanasi", "coords": (25.3176, 82.9739), "place": "Lal Bahadur Shastri Airport & BHU Kayakalp", "keywords": ["VARANASI", "BANARAS", "KASHI", "BABATPUR", "BHU", "SARNATH", "SHIVPUR", "PINDRA", "RAMNAGAR"]},
        {"district": "Agra", "coords": (27.1767, 78.0081), "place": "Agra Civil Enclave & Agra Metro Rail", "keywords": ["AGRA", "KHERIA", "FATEHABAD", "ETMADPUR", "KIRAOLI", "BAH", "SHAMSHABAD"]},
        {"district": "Kanpur Nagar", "coords": (26.4499, 80.3319), "place": "Ghatampur Power & Kanpur Metro & LPG Hub", "keywords": ["KANPUR", "GHATAMPUR", "CHAKERI", "PANKI", "KALYANPUR", "BILHAUR", "ROOMA", "MANDHANA", "SARSAUL"]},
        {"district": "Kanpur Dehat", "coords": (26.3400, 79.9500), "place": "Rania & Akbarpur Industrial Node", "keywords": ["KANPUR DEHAT", "AKBARPUR", "RANIA", "PUKHRAYAN", "RASULABAD", "DERAPUR", "BHOGNIPUR"]},
        {"district": "Lucknow", "coords": (26.8467, 80.9462), "place": "Lucknow Metro Phase-1B & Sewerage System", "keywords": ["LUCKNOW", "AMAUSI", "CHARBAGH", "GOMTI NAGAR", "ALAMBAGH", "BAKSHI KA TALAB", "MOHANLALGANJ", "SAROJINI NAGAR", "MALHIHABAD"]},
        {"district": "Mathura", "coords": (27.4924, 77.6737), "place": "Mathura Refinery & Bitumen Augmentation", "keywords": ["MATHURA", "VRINDAVAN", "CHHATA", "GOVERDHAN", "BARSANA", "KOSI KALAN", "BALDEO"]},
        {"district": "Jhansi", "coords": (25.4484, 78.5685), "place": "Jhansi Water Supply Infrastructure Phase-II", "keywords": ["JHANSI", "BABINA", "MAURANIPUR", "GARAUTHA", "MOTH", "CHIRGAON"]},
        {"district": "Ayodhya", "coords": (26.7922, 82.1998), "place": "Maryada Purushottam Shri Ram International Airport", "keywords": ["AYODHYA", "FAIZABAD", "PARIKRAMA MARG", "RUDUAU", "BIKAPUR", "MILKIPUR", "SOHAWAL"]},
        {"district": "Gorakhpur", "coords": (26.7606, 83.3732), "place": "Gorakhpur AIIMS & Fertilizer Complex", "keywords": ["GORAKHPUR", "GIDA", "SAHJANWA", "CHAURI CHAURA", "BANSGAON", "CAMPIERGANJ", "KHAJANI", "PIPIGANJ"]},
        {"district": "Gautam Buddha Nagar", "coords": (28.5355, 77.3910), "place": "Noida International Airport Jewar", "keywords": ["NOIDA", "GREATER NOIDA", "JEWAR", "DADRI", "DANKAUR", "RABUPURA"]},
        {"district": "Ghaziabad", "coords": (28.6692, 77.4538), "place": "Ghaziabad RRTS & Logistics Hub", "keywords": ["GHAZIABAD", "HINDON", "MODINAGAR", "MURADNAGAR", "LILIPAT", "LONI"]},
        {"district": "Meerut", "coords": (28.9845, 77.7064), "place": "Meerut RRTS Corridor & Metro", "keywords": ["MEERUT", "PARTAPUR", "SARDHANA", "MAWANA", "HASTINAPUR", "DAURALA"]},
        {"district": "Bareilly", "coords": (28.3670, 79.4304), "place": "Bareilly Smart City & Airport Hub", "keywords": ["BAREILLY", "IZZATNAGAR", "AONLA", "FARIDPUR", "BAHERI", "NAWABGANJ"]},
        {"district": "Aligarh", "coords": (27.8974, 78.0880), "place": "Aligarh Defense Industrial Corridor", "keywords": ["ALIGARH", "KHAIR", "ATRAULI", "IGLAS", "GABHANA", "TAPPAL"]},
        {"district": "Moradabad", "coords": (28.8386, 78.7733), "place": "Moradabad Brass & Smart City Hub", "keywords": ["MORADABAD", "BILARI", "KANDARKI", "THAKURDWARA"]},
        {"district": "Saharanpur", "coords": (29.9679, 77.5452), "place": "Saharanpur Freight & Expressway Corridor", "keywords": ["SAHARANPUR", "DEOBAND", "NAKUR", "BEHAT", "RAMPUR MANIHARAN"]},
        {"district": "Banda", "coords": (25.4754, 80.3346), "place": "Banda Bundelkhand Expressway Node", "keywords": ["BANDA", "ATARRA", "BABERU", "NARAINI"]},
        {"district": "Chitrakoot", "coords": (25.2064, 80.9234), "place": "Chitrakoot Airport & Defense Node", "keywords": ["CHITRAKOOT", "KARWI", "MANIKPUR", "MAU"]},
        {"district": "Mahoba", "coords": (25.2921, 79.8722), "place": "Mahoba Solar & Bundelkhand Corridor", "keywords": ["MAHOBA", "CHARKHARI", "KULPAHAR"]},
        {"district": "Lalitpur", "coords": (24.6865, 78.4110), "place": "Lalitpur Bulk Drug Park & Solar", "keywords": ["LALITPUR", "MEHRAUNI", "TALBEHAT", "MADANPUR"]},
        {"district": "Jalaun", "coords": (26.1472, 79.3371), "place": "Orai-Jalaun Industrial & Expressway Node", "keywords": ["JALAUN", "ORAI", "KONCH", "KALPI", "MADHOGARH"]},
        {"district": "Gonda", "coords": (27.1337, 81.9619), "place": "Gonda Rail & Highway Corridor", "keywords": ["GONDA", "COLONELGANJ", "MANKAPUR", "TARABGANJ"]},
        {"district": "Bahraich", "coords": (27.5705, 81.5977), "place": "Bahraich Indo-Nepal Border Node", "keywords": ["BAHRAICH", "NANPARA", "MAHESI", "PAYAGPUR", "KAISERGANJ", "JARWAL"]},
        {"district": "Shravasti", "coords": (27.7000, 82.0000), "place": "Shravasti Airport & Buddhist Circuit", "keywords": ["SHRAVASTI", "BHINGA", "IKONA"]},
        {"district": "Basti", "coords": (26.7994, 82.7633), "place": "Basti Highway & Sugar Cluster", "keywords": ["BASTI", "HARRAIYA", "BHANPUR", "RUDHAULI"]},
        {"district": "Sant Kabir Nagar", "coords": (26.7800, 83.0500), "place": "Khalilabad Textile & Rail Hub", "keywords": ["SANT KABIR NAGAR", "KHALILABAD", "MEHDAWAL", "DHANGHATA"]},
        {"district": "Kushinagar", "coords": (26.7410, 83.8893), "place": "Kushinagar International Airport Node", "keywords": ["KUSHINAGAR", "KASIA", "PADRAUNA", "HATA", "TAMTUKHI RAJ"]},
        {"district": "Deoria", "coords": (26.5024, 83.7791), "place": "Deoria Highway & Rail Network", "keywords": ["DEORIA", "SALEMPUR", "RUDRAPUR", "BHATPAR RANI", "BARHAJ"]},
        {"district": "Azamgarh", "coords": (26.0684, 83.1837), "place": "Azamgarh Purvanchal Expressway Node", "keywords": ["AZAMGARH", "MANDURI", "SAGRI", "NIZAMABAD", "LALGANJ AZAMGARH", "PHOOLPUR"]},
        {"district": "Mau", "coords": (25.9417, 83.5614), "place": "Mau Textile & Rail Hub", "keywords": ["MAU", "MAUNATH BHANJAN", "GHOSI", "MADHUBAN", "MUHAMMADABAD", "DOHRIGHAT"]},
        {"district": "Ballia", "coords": (25.7607, 84.1491), "place": "Ballia Green Field Expressway", "keywords": ["BALLIA", "RASRA", "BAIRIA", "SIKANDERPUR", "BANSDIH"]},
        {"district": "Ghazipur", "coords": (25.5840, 83.5770), "place": "Ghazipur Purvanchal Expressway Terminal", "keywords": ["GHAZIPUR", "ZAMANIA", "MOHAMMADABAD GHAZIPUR", "SAIDPUR", "JAKHANIAN"]},
        {"district": "Chandauli", "coords": (25.2605, 83.2652), "place": "Pt. Deen Dayal Upadhyaya Junction (Mughalsarai)", "keywords": ["CHANDAULI", "MUGHALSARAI", "DDU", "SAKALDIHA", "CHAKIA"]},
        {"district": "Fatehpur", "coords": (25.9272, 80.8122), "place": "Fatehpur Freight Corridor Node", "keywords": ["FATEHPUR", "BINDKI", "KHAGA"]},
        {"district": "Unnao", "coords": (26.5393, 80.4878), "place": "Unnao Leather Industrial & Expressway Node", "keywords": ["UNNAO", "SHUKLAGANJ", "HASANGANJ", "PURWA", "BANGARMAU", "BIGHAPUR"]},
        {"district": "Sitapur", "coords": (27.5644, 80.6829), "place": "Sitapur Highway & Sugar Complex", "keywords": ["SITAPUR", "BISWAN", "MAHMUDABAD", "LAHARPUR", "MISRIKH", "SIDHAULI"]},
        {"district": "Lakhimpur Kheri", "coords": (27.9482, 80.7788), "place": "Kheri Bio-Energy & Rail Node", "keywords": ["KHERI", "LAKHIMPUR", "GOLA GOKARAN NATH", "MOHAMMADI", "NIGHASAN", "PALIA KALAN"]},
        {"district": "Hardoi", "coords": (27.3989, 80.1306), "place": "Hardoi Rail & Agriculture Node", "keywords": ["HARDOI", "SHAHABAD HARDOI", "BILGRAM", "SANDILA", "SAWASAI"]},
        {"district": "Shahjahanpur", "coords": (27.8805, 79.9120), "place": "Shahjahanpur Power & Expressway Node", "keywords": ["SHAHJAHANPUR", "ROZA", "TILHAR", "PUWAYAN", "JALALABAD"]},
        {"district": "Pilibhit", "coords": (28.6310, 79.8044), "place": "Pilibhit Highway Corridor", "keywords": ["PILIBHIT", "PURANPUR", "BISALPUR"]},
        {"district": "Budaun", "coords": (28.0381, 79.1257), "place": "Budaun Highway & Solar Node", "keywords": ["BUDAUN", "BISAULI", "SAHASWAN", "DATAGANJ"]},
        {"district": "Rampur", "coords": (28.8154, 79.0257), "place": "Rampur Highway & Rail Hub", "keywords": ["RAMPUR", "BILASPUR UP", "MILAK", "SUAR", "SHAHABAD RAMPUR"]},
        {"district": "Sambhal", "coords": (28.5855, 78.5714), "place": "Sambhal Agriculture & Industrial Node", "keywords": ["SAMBHAL", "CHANDAUSI", "GUNNAUR"]},
        {"district": "Amroha", "coords": (28.9044, 78.4678), "place": "Amroha Highway NH-9 Corridor", "keywords": ["AMROHA", "GAJRAULA", "DHANAURA", "HASANPUR"]},
        {"district": "Bijnor", "coords": (29.3732, 78.1354), "place": "Bijnor Ganga River Expressway Node", "keywords": ["BIJNOR", "DHAMPUR", "NAJIBABAD", "NAGINA", "CHANDPUR"]},
        {"district": "Hapur", "coords": (28.7306, 77.7759), "place": "Hapur Freight & Logistics Node", "keywords": ["HAPUR", "GARHMUKTESHWAR", "DHAULANA"]},
        {"district": "Baghpat", "coords": (28.9454, 77.2206), "place": "Baghpat Eastern Peripheral Expressway", "keywords": ["BAGHPAT", "BARAUT", "KHEKRA"]},
        {"district": "Shamli", "coords": (29.4494, 77.3117), "place": "Shamli Highway & Sugar Node", "keywords": ["SHAMLI", "KAIRANA", "THANABHAWAN"]},
        {"district": "Muzaffarnagar", "coords": (29.4727, 77.7085), "place": "Muzaffarnagar Highway Corridor", "keywords": ["MUZAFFARNAGAR", "KHATAULI", "BUDHANA", "JANSATH"]},
        {"district": "Bulandshahr", "coords": (28.4069, 77.8498), "place": "Narora Atomic & Khurja Power Hub", "keywords": ["BULANDSHAHR", "KHURJA", "NARORA", "SIKANDRABAD", "SIYANA", "ANOOPSHAHR"]},
        {"district": "Firozabad", "coords": (27.1591, 78.3957), "place": "Firozabad Glass & Industrial Hub", "keywords": ["FIROZABAD", "SHIKOHABAD", "TUNDLA", "JASRANA"]},
        {"district": "Mainpuri", "coords": (27.2285, 79.0284), "place": "Mainpuri Expressway & Highway Node", "keywords": ["MAINPURI", "BHONGAON", "KARHAL", "KISHNI"]},
        {"district": "Etawah", "coords": (26.7855, 79.0154), "place": "Etawah Rail & Wildlife Safari Node", "keywords": ["ETAWAH", "SAIFAI", "BHARTHANA", "JASWANTNAGAR"]},
        {"district": "Auraiya", "coords": (26.4674, 79.5167), "place": "GAIL Pata & Auraiya Petrochemicals Node", "keywords": ["AURAIYA", "PATA", "DIBIYAPUR", "BIDHUNA"]},
        {"district": "Kannauj", "coords": (27.0545, 79.9192), "place": "Kannauj Perfume Park & Expressway Node", "keywords": ["KANNAUJ", "CHHIBRAMAU", "TIRWA"]},
        {"district": "Farrukhabad", "coords": (27.3828, 79.5844), "place": "Farrukhabad Potato & Textile Hub", "keywords": ["FARRUKHABAD", "FATEHGARH", "KAIMGANJ", "AMRITPUR"]},
        {"district": "Etah", "coords": (27.5615, 78.6653), "place": "Etah Jawaharpur Thermal Power Plant", "keywords": ["ETAH", "JAWAHARPUR", "JALESAR", "ALIGANJ"]},
        {"district": "Kasganj", "coords": (27.8083, 78.6477), "place": "Kasganj Rail Junction Hub", "keywords": ["KASGANJ", "GANJDUNDWARA", "PATIALI", "SAHAWAR"]},
        {"district": "Hathras", "coords": (27.5969, 78.0518), "place": "Hathras Industrial & Spice Node", "keywords": ["HATHRAS", "SIKANDRA RAO", "SADABAD", "SASNI"]},
        {"district": "Kaushambi", "coords": (25.5312, 81.3970), "place": "Kaushambi Buddhist Tourism Corridor", "keywords": ["KAUSHAMBI", "MANJHANPUR", "CHAIL", "SIRATHU"]},
    ],
    "ANDHRA PRADESH": [
        {"district": "YSR Kadapa", "coords": (14.4673, 78.8242), "place": "Kadapa Airport & Kopparthy Mega Industrial Node", "keywords": ["KADAPA", "CUDDAPAH", "KOPPARTHY", "PULIVENDULA", "PRODDATUR", "JAMMALAMADUGU", "RAYACHOTY", "BADVEL", "KAMALAPURAM", "MYDUKUR", "CHINA ORAMPADU", "ORAMPADU", "YERRAGUDIPADU", "AUDIREDDIPALLI", "KADAPA CHINA ORAMPADU"]},
        {"district": "NTR", "coords": (16.5062, 80.6480), "place": "Vijayawada International Airport & Rail Hub", "keywords": ["VIJAYAWADA", "GANNAVARAM", "NTR", "IBRAHIMPATNAM", "KONDAPALLI", "MYLAVARAM", "TIRUVURU", "JAGGAYYAPETA", "NANDIGAMA"]},
        {"district": "East Godavari", "coords": (17.0005, 81.8040), "place": "Rajahmundry Airport & Godavari Bridge Corridor", "keywords": ["RAJAHMUNDRY", "RAJAHMAHENDRAVARAM", "EAST GODAVARI", "KORUKONDA", "NIDADAVOLE", "KOVUR", "ANAPARTHI"]},
        {"district": "Kakinada", "coords": (16.9891, 82.2475), "place": "Kakinada Deep Water Port & SEZ Node", "keywords": ["KAKINADA", "SAMALKOT", "PITHAPURAM", "PEDDAPURAM", "TUNI", "PRATHIPADU", "KG-DWN-98/2"]},
        {"district": "Ananthapuramu", "coords": (14.6819, 77.6006), "place": "Tadipatri Bypass NH-67 & Solar Energy Zone", "keywords": ["ANANTAPUR", "ANANTHAPURAMU", "TADIPATRI", "TADPATRI", "GUNTAKAL", "GOOTY", "KALYANDURG", "RAYADURG", "URAVAKONDA", "GOOTY-PENDEKALLU"]},
        {"district": "Kurnool", "coords": (15.8281, 78.0373), "place": "Orvakal Mega Industrial Node & Kurnool-III PS", "keywords": ["KURNOOL", "ORVAKAL", "DHONE", "YEMMIGANUR", "ADONI", "ALUR", "KODUMUR", "PATTIKONDA", "PENDEKALLU"]},
        {"district": "Nandyal", "coords": (15.4886, 78.4836), "place": "Sangameswaram-Atmakuru & Velugodu-Nandyal Hub", "keywords": ["NANDYAL", "SANGAMESWARAM", "ATMAKURU", "ATMAKUR", "VELUGODU", "VELEGODU", "SRISAILAM", "ALLAGADDA", "BANAGANAPALLE", "KOILKUNTLA", "NANDIKOTKUR"]},
        {"district": "Visakhapatnam", "coords": (17.6868, 83.2185), "place": "Visakh Refinery (HPCL) & ESIC Sheelanagar", "keywords": ["VISAKHAPATNAM", "VIZAG", "VISAKH", "SHEELANAGAR", "DUVVADA", "GAJUWAKA", "ANANDAPURAM", "PENDURTHI", "BHEEMUNIPATNAM", "SIMHACHALAM", "VADLAPUDI", "VISAKH REFINERY"]},
        {"district": "Anakapalli", "coords": (17.6913, 83.0039), "place": "Atchutapuram SEZ & Anakapalli Node", "keywords": ["ANAKAPALLI", "ATCHUTAPURAM", "PARAWADA", "NARSIPATNAM", "CHODAVARAM", "YELAMANCHILI"]},
        {"district": "Tirupati", "coords": (13.6288, 79.4192), "place": "Tirupati Airport & Srikalahasti Node", "keywords": ["TIRUPATI", "SRIKALAHASTI", "RENIGUNTA", "CHANDRAGIRI", "VILLUPURAM-TIRUPATI", "TIRUPATI-KATPADI", "KATPADI", "VENKATAGIRI", "SULLURPETA", "NAIDUPETA", "TURPUKANUPUR", "POYYA"]},
        {"district": "Chittoor", "coords": (13.2172, 79.1003), "place": "Chittoor Industrial Cluster & NH-69", "keywords": ["CHITTOOR", "PALAMANER", "KUPPAM", "PUNGANUR", "NAGARI", "GANGADHARA NELLORE", "BAIREDDYPALLI", "BAIREDDYPALLE", "BANGALORE CHENNAI EXPRESSWAY PHASE-II PKG-II", "BANGALORE CHENNAI EXPRESSWAY PHASE-II PKG-III"]},
        {"district": "Sri Potti Sriramulu Nellore", "coords": (14.4426, 79.9865), "place": "Krishnapatnam Port Node Phase-1", "keywords": ["NELLORE", "SPSR NELLORE", "KRISHNAPATNAM", "KAVALI", "GUDUR", "ATMAKUR NELLORE", "KOVVUR NELLORE"]},
        {"district": "Guntur", "coords": (16.3067, 80.4365), "place": "Guntur Smart City & Amaravati Capital Node", "keywords": ["GUNTUR", "AMARAVATI", "TENALI", "MANGALAGIRI", "TADIKONDA"]},
        {"district": "Palnadu", "coords": (16.2300, 80.0500), "place": "Nadikudi Junction & Palnadu Mining Node", "keywords": ["PALNADU", "NADIKUDI", "NARASARAOPET", "SATTENAPALLE", "VINUKONDA", "GURAJALA", "MACHARLA", "PIDUGURALLA", "PERECHERLA", "KONDAMODU", "KONDAMODU TO PERECHERLA"]},
        {"district": "Bapatla", "coords": (15.9042, 80.4678), "place": "Bapatla Coastal Corridor", "keywords": ["BAPATLA", "CHIRALA", "REPALLE", "VEMURU", "ADDAKI"]},
        {"district": "Prakasam", "coords": (15.5057, 80.0499), "place": "Ongole Industrial Node & Ramayapatnam Port", "keywords": ["ONGOLE", "PRAKASAM", "RAMAYAPATNAM", "KANDUKUR", "MARKAPUR", "GIDDALUR", "KANIGIRI", "GUNDLAKAMMA"]},
        {"district": "West Godavari", "coords": (16.5449, 81.5212), "place": "Narasapur-Kotipalli Rail Link & Bhimavaram", "keywords": ["WEST GODAVARI", "BHIMAVARAM", "NARASAPUR", "NARSAPUR", "TADEPALLIGUDEM", "TANUKU", "PALAKOLLU", "ACHANTA"]},
        {"district": "Eluru", "coords": (16.7107, 81.0952), "place": "Eluru Smart City Corridor", "keywords": ["ELURU", "DENDULURU", "CHINTALAPUDI", "POLAVARAM", "JANGAREDDYGUDEM", "NUZVID", "GUNDUGOLANU", "KALAPARRU", "GUNDUGOLANU TO KALAPARRU"]},
        {"district": "Dr. B.R. Ambedkar Konaseema", "coords": (16.5700, 82.0000), "place": "Pasarlapudi-Dhindi & Kotipalli Rail Terminal", "keywords": ["KONASEEMA", "AMALAPURAM", "KOTIPALLI", "KOTAPALLI", "PASARLAPUDI", "DHINDI", "RAZOLE", "MANDAPETA", "RAMACHANDRAPURAM", "MUMMIDIVARAM"]},
        {"district": "Krishna", "coords": (16.1809, 81.1303), "place": "Machilipatnam Deep Sea Port", "keywords": ["KRISHNA", "MACHILIPATNAM", "GUDIVADA", "AVANIGADDA", "PAMARRU", "PENAMALURU"]},
        {"district": "Vizianagaram", "coords": (18.1124, 83.3956), "place": "Bhogapuram International Airport Node", "keywords": ["VIZIANAGARAM", "BHOGAPURAM", "BOBBILI", "CHEEPURUPALLI", "GAJAPATHINAGARAM", "NELLIMARLA", "JAKKUVA", "JAKKUVA KORLAM", "THOTAPALLI"]},
        {"district": "Parvathipuram Manyam", "coords": (18.7700, 83.4200), "place": "Central Tribal University of AP (Salur)", "keywords": ["PARVATHIPURAM", "MANYAM", "SALUR", "KURUPAM", "PALAKONDA", "CENTRAL TRIBAL UNIVERSITY"]},
        {"district": "Srikakulam", "coords": (18.2949, 83.8938), "place": "Bhavanapadu Port & Srikakulam Corridor", "keywords": ["SRIKAKULAM", "BHAVANAPADU", "PALASA", "TEKKALI", "AMADALAVALASA", "ICHAPURAM", "KORLAM", "KOTABOMMALI", "NARASANNAPETA"]},
        {"district": "Sri Sathya Sai", "coords": (14.1667, 77.8167), "place": "Gorantla-Hindupur NH-716G & Puttaparthi", "keywords": ["PUTTAPARTHI", "HINDUPUR", "GORANTLA", "DHARMAVARAM", "KADIRI", "PENUKONDA", "MADAKASIRA", "ODULAPALLE", "NALLACHERUVU", "NALLACHERUVUPALLI"]},
        {"district": "Annamayya", "coords": (14.0000, 78.7500), "place": "Rayachoti & Madanapalle Industrial Node", "keywords": ["ANNAMAYYA", "RAYACHOTI", "MADANAPALLE", "RAJAMPET", "PILERU", "RAILWAY KODUR"]},
        {"district": "Alluri Sitharama Raju", "coords": (18.0667, 82.5333), "place": "Paderu & Upper Sileru Hydro Node", "keywords": ["PADERU", "ARAKU", "CHINTAPALLE", "RAMPACHODAVARAM", "SILERU", "LAMBASINGI", "LAMBASINGI TO PADERU"]},
    ],
    "MAHARASHTRA": [
        {"district": "Nagpur", "coords": (21.1458, 79.0882), "place": "Saoner & Makardhokra Coal & MIHAN SEZ", "keywords": ["SAONER", "MAKARDHOKRA", "SINGHORI", "GOKUL", "UMRER", "NAGPUR", "MIHAN", "BUTIBORI", "KAMPTEE", "RAMTEK", "KALMESHWAR", "INDORA CHOWK", "PACHPAOLI", "BHANEGAON"]},
        {"district": "Chandrapur", "coords": (19.9615, 79.2961), "place": "Bhatadi, Sasti & Yekona Coalfields", "keywords": ["BHATADI", "SASTI", "YEKONA", "DHUPTALA", "NEW MAJRI", "CHANDRAPUR", "BALLARPUR", "WARORA", "TADOBA", "WCL", "GAURIDEEP", "GAURI CENTRAL", "GADCHANDUR", "KORPANA"]},
        {"district": "Bhandara", "coords": (20.8732, 79.6468), "place": "Gosikhurd Dam, Wainganga River, Pauni", "keywords": ["GOSIKHURD", "BHANDARA", "PAUNI", "WAINGANGA", "TUMSAR", "MOHADI", "SAKOLI", "LAKHANDUR"]},
        {"district": "Palghar", "coords": (19.6967, 72.7699), "place": "Palghar & Talasari Expressway Corridor", "keywords": ["PALGHAR", "SHIRSAD", "MASVAN", "GANJAD", "MANOR", "BOISAR", "DAHANU", "TALASARI", "TALSARI", "TARAPUR", "JAWHAR", "WADA", "VASAI", "VIRAR", "SHIRSAD - MASVAN", "MASVAN - GANJAD", "SHIRSAD - AKLOLI"]},
        {"district": "Thane", "coords": (19.2183, 72.9781), "place": "Kalyan-Bhiwandi Logistics Hub", "keywords": ["THANE", "KALYAN", "BHIWANDI", "DOMBIVLI", "MUMBRA", "KASARA", "DIVA", "TITWALA", "AKLOLI", "AMNE", "BHOJ", "AKLOLI - AMNE", "AMNE - BHOJ", "VADAPE"]},
        {"district": "Raigad", "coords": (18.5158, 73.1822), "place": "Navi Mumbai International Airport & JNPT", "keywords": ["NAVI MUMBAI", "NMIAL", "JNPT", "NHAVA SHEVA", "PANVEL", "ROHA", "ALIBAG", "TALOJA", "RAIGAD", "MORBE", "BHOJ - MORBE", "MANGAON", "REWAS", "USAR", "PANVEL INDAPUR", "PEN", "KHOPOLI", "KARJAT", "MAHAD", "POLADPUR"]},
        {"district": "Ratnagiri", "coords": (16.9902, 73.3120), "place": "Ratnagiri Port & NH-66 Coastal Highway", "keywords": ["RATNAGIRI", "KASHEDI", "KHED", "CHIPLUN", "LANJA", "RAJAPUR", "SANGAMESHWAR", "GUHAGAR", "BHOGAON KHURD", "KASHEDI GHAT", "KASHEDI GHAT TUNNEL"]},
        {"district": "Sindhudurg", "coords": (16.1200, 73.7000), "place": "Sindhudurg Coastal & Irrigation Corridor", "keywords": ["SINDHUDURG", "ARUNA", "NARDAVE", "VAIBHAVWADI", "KANKAVLI", "SAWANTWADI", "MALVAN", "VENGURLA", "KUDAL", "DODAMARG", "ARUNA MEDIUM", "NARDAVE MEDIUM"]},
        {"district": "Pune", "coords": (18.5204, 73.8567), "place": "Hinjawadi IT & Ring Road", "keywords": ["PUNE", "HINJAWADI", "HADAPSAR", "TALEGAON", "CHAKAN", "SHIVAJINAGAR", "PIMPRI", "CHINCHWAD", "PCMC", "NIGDI", "SWARGATE", "KATRAJ", "VANAZ", "CHANDANI CHOWK", "DIVE GHAT"]},
        {"district": "Mumbai Suburban", "coords": (19.0657, 72.8687), "place": "Bandra-Kurla Complex & Chembur Refinery", "keywords": ["BKC", "BANDRA", "KURLA", "ANDHERI", "BORIVALI", "GHATKOPAR", "SANTA CRUZ", "MAHUL", "CHEMBUR", "MUMBAI REFINERY", "LUBE MODERNIZATION", "PRFCC", "HP TDAE", "MUMBAI METRO LINE 3"]},
        {"district": "Mumbai City", "coords": (18.9400, 72.8353), "place": "Chhatrapati Shivaji Maharaj Terminus & South Mumbai", "keywords": ["MUMBAI CITY", "CSMT", "CHHATRAPATI SHIVAJI MAHARAJ TERMINUS", "MUMBAI FORT", "COLABA", "CHURCHGATE", "DADAR", "WORLI", "SEWRI", "COASTAL ROAD", "MUMBAI COASTAL ROAD"]},
        {"district": "Nashik", "coords": (19.9975, 73.7898), "place": "Ambad & Sinnar Industrial SEZ", "keywords": ["NASHIK", "SINNAR", "AMBAD", "SATPUR", "MALEGAON", "IGATPURI", "OZAR", "GONDE", "PIMPRI SADO"]},
        {"district": "Chhatrapati Sambhajinagar", "coords": (19.8762, 75.3433), "place": "Shendra-Bidkin DMIC Node", "keywords": ["SAMBHAJINAGAR", "AURANGABAD", "SHENDRA", "BIDKIN", "WALUJ", "CHIKALTHANA"]},
        {"district": "Solapur", "coords": (17.6599, 75.9064), "place": "Solapur NTPC & Highway", "keywords": ["SOLAPUR", "PANDHARPUR", "AKKALKOT", "BARSHI", "MOHOL", "PANDHARPUR TOWN", "DHARAMPURI-LONAND"]},
        {"district": "Satara", "coords": (17.6805, 74.0183), "place": "Helwak-Patan-Karad Corridor", "keywords": ["SATARA", "PATAN-KARAD", "HELWAK-PATAN", "KARAD", "MAHABALESHWAR", "WAI", "KHANDALA", "SHIRWAL", "URMODI", "KHAMBATAKI", "SHIRWAL-LONAND", "LONAND TO DIVE GHAT"]},
        {"district": "Kolhapur", "coords": (16.7050, 74.2433), "place": "Kolhapur Textile & Auto Node", "keywords": ["KOLHAPUR", "ICHALKARANJI", "KAGAL", "SHIROL", "GOKUL SHIRGAON", "KAGAL-SATARA"]},
        {"district": "Dhule", "coords": (20.9042, 74.7749), "place": "Dhule-Nardana DMIC Corridor", "keywords": ["DHULE", "FAGNE", "NARDANA", "SHIRPUR", "SULWADE", "JAMPHAL", "KANOLI", "SULWADE-JAMPHAL-KANOLI", "TARSOD - FAGNE", "BODHRE - DHULE"]},
        {"district": "Jalgaon", "coords": (21.0077, 75.5626), "place": "Jalgaon Bhusawal Hub", "keywords": ["JALGAON", "BHUSAWAL", "AMALNER", "CHALISGAON", "WAGHUR", "PACHORA", "JAMNER"]},
        {"district": "Yavatmal", "coords": (20.3888, 78.1204), "place": "Yavatmal WCL Mining Corridor", "keywords": ["YAVATMAL", "PUSAD", "WANI", "DARWHA", "MUNGOLI", "NIRGUDA", "KOLARPIMPRI"]},
        {"district": "Amravati", "coords": (20.9374, 77.7796), "place": "Amravati Industrial Node", "keywords": ["AMRAVATI", "ACHALPUR", "CHIKHALDARA", "LOWER PEDHI"]},
        {"district": "Gondia", "coords": (21.4624, 80.2210), "place": "Gondia Tiroda Thermal", "keywords": ["GONDIA", "TIRODA"]},
        {"district": "Wardha", "coords": (20.7453, 78.6022), "place": "Wardha Sevagram Junction", "keywords": ["WARDHA", "SEWAGRAM", "HINGANGHAT"]},
        {"district": "Nanded", "coords": (19.1383, 77.3210), "place": "Nanded Express Corridor", "keywords": ["NANDED", "DEGLOOR", "MUDKHED", "LOHA-WARANGA"]},
    ],
    "ODISHA": [
        {"district": "Jharsuguda", "coords": (21.8550, 84.0080), "place": "Integrated Lakhanpur-Belpahar Mining Complex", "keywords": ["LAKHANPUR", "BELPAHAR", "JHARSUGUDA", "IB VALLEY", "BRAJRAJNAGAR", "TALABIRA"]},
        {"district": "Sundargarh", "coords": (22.1167, 84.0333), "place": "Integrated Kulda Garjanbahal & Basundhara", "keywords": ["SUNDARGARH", "SUNDERGARH", "KULDA", "GARJANBAHAL", "BASUNDHARA", "ROURKELA", "HEMGIR", "TANGARPALI", "RAJGANGPUR", "DARLIPALI"]},
        {"district": "Angul", "coords": (20.8400, 85.1000), "place": "Subhadra & Bharatpur & Hingula Coal Complex", "keywords": ["ANGUL", "SUBHADRA", "SIARMAL", "BALARAM", "GOPALJI", "KANIHA", "BHARATPUR", "HINGULA", "TALCHER", "NALCO", "DERA"]},
        {"district": "Koraput", "coords": (18.8135, 82.7123), "place": "NALCO Alumina Refinery & Pottangi Bauxite Mines", "keywords": ["DAMANJODI", "KORAPUT", "POTTANGI", "JEYPORE", "SUNABEDA", "KOTPAD", "SEMILIGUDA"]},
        {"district": "Khordha", "coords": (20.2961, 85.8245), "place": "Bhubaneswar Smart City & Metro Corridor", "keywords": ["BHUBANESWAR", "KHORDHA", "JATNI", "BALIPATNA", "TANGI"]},
        {"district": "Cuttack", "coords": (20.4625, 85.8828), "place": "Cuttack Multi-Modal Logistic Park", "keywords": ["CUTTACK", "CHOUDWAR", "ATHAGARH", "BANKI", "NARSINGHPUR"]},
        {"district": "Jagatsinghpur", "coords": (20.2644, 86.6667), "place": "Paradip Port Mega Petrochemical Complex", "keywords": ["PARADIP", "PARADEEP", "JAGATSINGHPUR", "KUJANG", "TIRTOL", "ERASAMA"]},
        {"district": "Jajpur", "coords": (20.8500, 86.1333), "place": "Kalinganagar National Steel Hub", "keywords": ["KALINGANAGAR", "JAJPUR", "SUKINDA", "VYASANAGAR", "DANAGADI"]},
        {"district": "Sambalpur", "coords": (21.4669, 83.9812), "place": "Hirakud & Sambalpur Industrial Cluster", "keywords": ["SAMBALPUR", "HIRAKUD", "BURLA", "RENGALI", "KUCHINDA"]},
        {"district": "Ganjam", "coords": (19.3150, 84.7941), "place": "Gopalpur Port & SEZ & IISER Berhampur", "keywords": ["GOPALPUR", "GANJAM", "BERHAMPUR", "CHHATRAPUR", "ASKA", "BHANJANAGAR", "IISER BERHAMPUR"]},
        {"district": "Balasore", "coords": (21.4934, 86.9135), "place": "Balasore Defense & Space Coast", "keywords": ["BALASORE", "BALESHWAR", "CHANDIPUR", "JALESWAR", "SORO"]},
    ],
    "MADHYA PRADESH": [
        {"district": "Balaghat", "coords": (21.8100, 80.1800), "place": "Expansion of Malanjkhand Copper Project", "keywords": ["MALANJKHAND", "BALAGHAT", "WARASEONI", "KATANGI", "BAIHAR", "LALBURRA"]},
        {"district": "Umaria", "coords": (23.5256, 80.8353), "place": "Jhiria West & Gandhigram Mining Node", "keywords": ["JHIRIA", "GANDHIGRAM", "UMARIA", "NOWROZABAD", "CHANDIA", "MANPUR", "PALI UMBER"]},
        {"district": "Singrauli", "coords": (24.1997, 82.6647), "place": "Nigahi, Jayant & Block-B Coal Mega Hub", "keywords": ["SINGRAULI", "NIGAHI", "JAYANT", "BLOCK B", "BLOCK-B", "BAIDHAN", "WAIDHAN", "SASAN", "VINDHYACHAL MP", "KANCHAN", "MAHAN ENERGEN"]},
        {"district": "Narsinghpur", "coords": (22.9431, 79.1950), "place": "Gadarwara Super Thermal Power Project Stage-II", "keywords": ["GADARWARA", "NARSINGHPUR", "GOTITORIA", "KARELI", "TENDUKHEDA"]},
        {"district": "Chhindwara", "coords": (22.0574, 78.9382), "place": "Pench & Kanhan Valley Coalfields", "keywords": ["CHHINDWARA", "DHANKASA", "JAMUNIA", "VISHNUPURI", "URDHAN", "PARASIA", "JUNNARDEO", "SAUSAR"]},
        {"district": "Shahdol", "coords": (23.2844, 81.3539), "place": "Sohagpur Coalfield & Shahdol Hub", "keywords": ["SHAHDOL", "SOHAGPUR", "BURHAR", "BEOHARI", "JAITPUR", "SHARDA UG", "RAMPUR BATURA"]},
        {"district": "Anuppur", "coords": (23.1000, 81.7000), "place": "Amadand OCP & Chachai Thermal Hub", "keywords": ["ANUPPUR", "AMADAND", "AMARKANTAK", "CHACHAI", "KOTMA", "JAITHARI"]},
        {"district": "Betul", "coords": (21.9014, 77.9022), "place": "Tawa-III & Betul Highway Node", "keywords": ["BETUL", "TAWA", "SARNI", "MULTAI", "BHAINSDEHI"]},
        {"district": "Bhopal", "coords": (23.2599, 77.4126), "place": "Bhopal Metro Rail Project Phase-1", "keywords": ["BHOPAL", "HABIBGANJ", "RANI KAMLAPATI", "MANDIDEEP", "BAIRAGARH", "BERASIA", "KOLAR BHOPAL"]},
        {"district": "Indore", "coords": (22.7196, 75.8577), "place": "Indore Metro Rail Corridor & Pithampur", "keywords": ["INDORE", "PITHAMPUR", "SANWER", "MHOW", "DEPALPUR"]},
        {"district": "Jabalpur", "coords": (23.1815, 79.9864), "place": "Jabalpur Ring Road & Defense Hub", "keywords": ["JABALPUR", "KHAMARIA", "SIHORA", "PATAN MP", "PANAGAR"]},
        {"district": "Gwalior", "coords": (26.2183, 78.1828), "place": "Gwalior Airport New Terminal & Highway", "keywords": ["GWALIOR", "DABRA", "MORAR", "GHATIGAON"]},
        {"district": "Rewa", "coords": (24.5362, 81.3037), "place": "Rewa Ultra Mega Solar Park & Airport", "keywords": ["REWA", "CHURHAT", "MAUGANJ", "TEONTHAR", "HANUMANA"]},
        {"district": "Satna", "coords": (24.5800, 80.8300), "place": "Satna Cement Cluster & Smart City", "keywords": ["SATNA", "MAIHAR", "NAGOD", "AMARPATAN", "RAMNAGAR"]},
        {"district": "Katni", "coords": (23.8343, 80.3957), "place": "Katni Rail Grade Separator Hub", "keywords": ["KATNI", "MURWARA", "VIJAYRAGHAVGARH", "SLIMANABAD"]},
        {"district": "Ujjain", "coords": (23.1765, 75.7885), "place": "Ujjain Mahakal Tourism & Expressway", "keywords": ["UJJAIN", "NAGDA", "KHACHROD", "TARANA", "MAHIDPUR"]},
    ],
    "RAJASTHAN": [
        {"district": "Bundi", "coords": (25.4305, 75.6499), "place": "Greenfield Airport at Bundi, Kota", "keywords": ["BUNDI", "KOTA AIRPORT", "BUNDI AIRPORT", "HINDOLI", "KESHORAIPATAN", "NAINWA"]},
        {"district": "Kota", "coords": (25.1800, 75.8300), "place": "Kota Energy & Industrial Hub", "keywords": ["KOTA", "RAMGANJ MANDI", "SANGOD", "DIGOD"]},
        {"district": "Jodhpur", "coords": (26.2389, 73.0243), "place": "Jodhpur Airport Terminal & AIIMS", "keywords": ["JODHPUR", "BHADLA", "OSIAN", "BILARA", "LUNI", "PHALODI"]},
        {"district": "Udaipur", "coords": (24.5854, 73.7125), "place": "Udaipur Airport & Zinc City", "keywords": ["UDAIPUR", "DEBARI", "MAVLI", "SALUMBER", "VALLABHNAGAR"]},
        {"district": "Barmer", "coords": (25.7521, 71.3967), "place": "Barmer Petrochemical Evacuation Marketing Terminal", "keywords": ["BARMER", "UTARLAI", "SHEO", "BAYTU", "GUDAMALANI", "RAMSAR", "CHHOTAN"]},
        {"district": "Balotra", "coords": (25.8300, 72.2400), "place": "Pachpadra HRRL Rajasthan Refinery Project", "keywords": ["BALOTRA", "PACHPADRA", "REFINERY", "SIWANA", "SAMDARI", "SINDHARI"]},
        {"district": "Jaisalmer", "coords": (26.9157, 70.9083), "place": "Fatehgarh Solar PS & Renewable Evacuation", "keywords": ["JAISALMER", "FATEHGARH", "POKRAN", "RAMGARH JAISALMER", "MOHANGARH"]},
        {"district": "Bikaner", "coords": (28.0229, 73.3119), "place": "Bikaner Solar Complex & Ceramic Hub", "keywords": ["BIKANER", "NOKHA", "LUNKARANSAR", "KOLAYAT", "DUNGARGARH"]},
        {"district": "Jaipur", "coords": (26.9124, 75.7873), "place": "Jaipur Metro & Ring Road", "keywords": ["JAIPUR", "SANGANER", "AMER", "CHOMU", "CHAKSU", "BAGRU", "BASSi"]},
        {"district": "Ajmer", "coords": (26.4499, 74.6399), "place": "Pushkar-Merta & Ajmer Rail Junction", "keywords": ["AJMER", "PUSHKAR", "KISHANGARH", "BEAWAR", "NASIRABAD"]},
        {"district": "Chittorgarh", "coords": (24.8887, 74.6269), "place": "Chanderiya & Chittorgarh Doubling Node", "keywords": ["CHITTORGARH", "CHANDERIYA", "NIMBAHERA", "RAWATBHATA", "BEGUN"]},
        {"district": "Rajsamand", "coords": (25.0700, 73.8800), "place": "Devgarh Madariya - Nathdwara Rail Corridor", "keywords": ["RAJSAMAND", "NATHDWARA", "DEVGARH", "MADARIYA", "AMET", "KUMBHALGARH"]},
    ],
    "TAMIL NADU": [
        {"district": "Chennai", "coords": (13.0827, 80.2707), "place": "Chennai Airport Modernization & Metro Rail Phase-II", "keywords": ["CHENNAI", "MADRAS", "MEENAMBAKKAM", "EGMORE", "CENTRAL CHENNAI", "VELACHERY", "ST THOMAS MOUNT", "GUINDY", "ALANDUR", "SHOLINGANALLUR", "PORUR", "MADHAVARAM", "POONAMALLEE"]},
        {"district": "Tirunelveli", "coords": (8.7139, 77.7567), "place": "Kudankulam Nuclear Power Project Units", "keywords": ["TIRUNELVELI", "KUDANKULAM", "RADHAPURAM", "NANGUNERI", "AMBASAMUDRAM"]},
        {"district": "Thoothukudi", "coords": (8.7642, 78.1348), "place": "VO Chidambaranar Port & Kayathar Wind Hub", "keywords": ["THOOTHUKUDI", "TUTICORIN", "KAYATHAR", "KOVILPATTI", "TIRUCHENDUR", "OTTAPIDARAM"]},
        {"district": "Madurai", "coords": (9.9252, 78.1198), "place": "AIIMS Madurai & Achambathu-Viratipathu Bypass", "keywords": ["MADURAI", "ACHAMBATHU", "VIRATIPATHU", "THOPPUR", "MELUR", "USILAMPATTI", "VADIPATTI", "TIRUMANGALAM"]},
        {"district": "Nagapattinam", "coords": (10.7672, 79.8449), "place": "Cauvery Basin Refinery (CBR 9 MMTPA) CPCL", "keywords": ["NAGAPATTINAM", "CBR", "CAUVERY BASIN", "PANAGUDI", "VELANKANNI", "KILVELUR", "VILLUPURAM-TIRUPATI"]},
        {"district": "Nilgiris", "coords": (11.4102, 76.6950), "place": "Nilgiris CGD Project & Tourism Rail", "keywords": ["NILGIRIS", "OOTY", "UDHAGAMANDALAM", "COONOOR", "KOTAGIRI", "GUDALUR"]},
        {"district": "Erode", "coords": (11.3410, 77.7172), "place": "Erode City Gas Distribution & Textile Node", "keywords": ["ERODE", "BHAVANI", "PERUNDURAI", "GOBICHETTIPALAYAM", "SATHYAMANGALAM"]},
        {"district": "Ranipet", "coords": (12.9229, 79.3328), "place": "Bangalore-Chennai Expressway Walajahpet-Arakkonam", "keywords": ["RANIPET", "WALAJAHPET", "WALAJAPET", "ARAKKONAM", "ARCOT", "SHOLINGHUR", "KARAIPETTAI"]},
        {"district": "Kanchipuram", "coords": (12.8342, 79.7036), "place": "Bangalore-Chennai Expressway Kancheepuram Section", "keywords": ["KANCHEEPURAM", "KANCHIPURAM", "SRIPERUMBUDUR", "ORAGADAM", "WALAJABAD"]},
        {"district": "Chengalpattu", "coords": (12.6841, 79.9836), "place": "Chengalpattu Industrial & Auto SEZ", "keywords": ["CHENGALPATTU", "MAHINDRA WORLD CITY", "MARAIMALAI NAGAR", "TAMBARAM", "VANDALUR"]},
        {"district": "Coimbatore", "coords": (11.0168, 76.9558), "place": "Coimbatore Smart City & Airport Corridor", "keywords": ["COIMBATORE", "PEELAMEDU", "POLLACHI", "SULUR", "METTUPALAYAM"]},
        {"district": "Tiruchirappalli", "coords": (10.7905, 78.7047), "place": "Tiruchirappalli International Airport Terminal", "keywords": ["TIRUCHIRAPPALLI", "TRICHY", "SRIRANGAM", "THIRUVERUMBUR", "MANAPPARAI"]},
    ],
    "WEST BENGAL": [
        {"district": "Darjeeling", "coords": (26.7100, 88.3200), "place": "Bagdogra Airport New Civil Enclave", "keywords": ["BAGDOGRA", "DARJEELING", "SILIGURI", "KURSEONG", "MIRIK"]},
        {"district": "Kolkata", "coords": (22.5726, 88.3639), "place": "Kolkata Metro & Port Modernization", "keywords": ["KOLKATA", "CALCUTTA", "SEALDAH", "HOWRAH", "ESPLANADE", "SALT LAKE", "NEW TOWN", "DUM DUM"]},
        {"district": "North 24 Parganas", "coords": (22.6500, 88.4500), "place": "Netaji Subhash Chandra Bose Airport Upgradation", "keywords": ["NORTH 24 PARGANAS", "BARASAT", "BARRACKPORE", "DUM DUM AIRPORT", "HABRA", "BASHIRHAT"]},
        {"district": "Paschim Bardhaman", "coords": (23.6889, 86.9661), "place": "Raniganj Coalfields (Jhanjra, Sonepur Bazari, Parasea)", "keywords": ["ASANSOL", "DURGAPUR", "PASCHIM BARDHAMAN", "RANIGANJ", "JHANJRA", "SONEPUR BAZARI", "MOHANPUR", "BONJEMEHARI", "NAKRAKONDA", "SIDULI", "TILABONI", "ITAPARA", "SHYAMSUNDARPUR", "PARASEA", "PARASCOLE", "BHOJUDIH", "ANDAL", "KULTI"]},
        {"district": "Purulia", "coords": (23.4900, 86.6800), "place": "Raghunathpur Thermal Power Station Phase-II (DVC)", "keywords": ["PURULIA", "RAGHUNATHPUR", "ADRA", "JHALDA", "BAGHMUNDI"]},
        {"district": "Purba Medinipur", "coords": (22.0667, 88.1000), "place": "Haldia Port Complex & Petrochemicals", "keywords": ["HALDIA", "PURBA MEDINIPUR", "TAMLUK", "DIGHA", "PANSKURA"]},
    ],
    "JHARKHAND": [
        {"district": "Godda", "coords": (25.0300, 87.2100), "place": "Rajmahal Coalfield & Hura C OCP", "keywords": ["GODDA", "HURA C", "RAJMAHAL", "MAHAGAMA", "BOARIJOR"]},
        {"district": "Bokaro", "coords": (23.6693, 86.1511), "place": "Bokaro Steel City & Konar / Karo Coalfields", "keywords": ["BOKARO", "KONAR", "KARO", "BERMO", "CHAS", "GOMIA", "CHANDRAPURA", "PHUSRO", "TENUGHAT"]},
        {"district": "Chatra", "coords": (24.2100, 84.8700), "place": "North Karanpura Super Coal Hub (Amrapali, Magadh, Sanghmitra)", "keywords": ["CHATRA", "AMRAPALI", "MAGADH", "SANGHMITRA", "CHANDRAGUPT", "ASHOK OC", "TANDWA", "SIMARIA", "HUNTERGANJ"]},
        {"district": "Ramgarh", "coords": (23.6300, 85.5100), "place": "Rajrappa & Kotre Basantpur Pachmo Coal Complex", "keywords": ["RAMGARH", "RAJRAPPA", "KOTRE", "BASANTPUR", "PACHMO", "GOLA", "PATRATU"]},
        {"district": "Hazaribagh", "coords": (23.9900, 85.3600), "place": "North Urimari & Rohini-Karketta Coal Mining Node", "keywords": ["HAZARIBAGH", "URIMARI", "ROHINI", "KARKETTA", "PUNDI", "BARKAGAON", "ICHAK"]},
        {"district": "Deoghar", "coords": (24.4826, 86.6975), "place": "Chitra East OCP & Deoghar AIIMS / Airport", "keywords": ["DEOGHAR", "CHITRA", "CHITRA EAST", "MADHUPUR", "JASIDIH"]},
        {"district": "Ranchi", "coords": (23.3441, 85.3096), "place": "Ranchi Smart City & Core Infrastructure", "keywords": ["RANCHI", "HATIA", "DHURWA", "NAMKUM", "KANKAY"]},
        {"district": "Dhanbad", "coords": (23.7957, 86.4304), "place": "Jharia Coalfield & BCCL Mining Infrastructure", "keywords": ["DHANBAD", "JHARIA", "KATRAS", "SINDRI", "KUMARDHUBI", "NIRSA", "GOVINDPUR"]},
        {"district": "East Singhbhum", "coords": (22.8046, 86.2029), "place": "Jamshedpur Steel & Adityapur Auto Cluster", "keywords": ["JAMSHEDPUR", "EAST SINGHBHUM", "GHATSHILA", "BAHAPATNA", "TATA"]},
        {"district": "Pakur", "coords": (24.6300, 87.8400), "place": "Pachwara South Coal Block", "keywords": ["PAKUR", "PACHWARA", "LITIPARA", "AMRAPARA", "HIRANPUR"]},
    ],
    "ASSAM": [
        {"district": "Kamrup Metropolitan", "coords": (26.1445, 91.7362), "place": "Guwahati Airport Terminal & AIIMS Changsari", "keywords": ["GUWAHATI", "KAMRUP", "BORJHAR", "CHANGSARI", "BETKUCHI", "DISPUR", "JALUKBARI", "AMINGAON", "NORTH GUWAHATI"]},
        {"district": "Tinsukia", "coords": (27.4922, 95.3468), "place": "Digboi Refinery, Baghjan & Margherita Coalfields", "keywords": ["TINSUKIA", "DIGBOI", "TIKAK", "TIRAP", "BAGHJAN", "MARGHERITA", "LEDO", "DOOMDOOMA", "MAKUM"]},
        {"district": "Golaghat", "coords": (26.5200, 93.9700), "place": "Numaligarh Refinery Bio-Ethanol Expansion (NRL)", "keywords": ["NUMALIGARH", "GOLAGHAT", "BOKAKHAT", "SARUPATHAR", "DERGAON"]},
        {"district": "Sivasagar", "coords": (26.9826, 94.6425), "place": "Lakwagaon & Rudrasagar ONGC Oil Assets", "keywords": ["LAKWAGAON", "RUDRASAGAR", "SIVASAGAR", "SIB SAGAR", "NAZIRA", "GELEKY", "DEMOW"]},
        {"district": "Sonitpur", "coords": (26.6528, 92.7926), "place": "Tezpur University & Highway Corridor", "keywords": ["TEZPUR", "SONITPUR", "DHEKIAJULI", "JAMUGURIHAT"]},
        {"district": "Dhubri", "coords": (26.0200, 89.9700), "place": "Kamardanga LPG & POL Rail Fed Facility", "keywords": ["DHUBRI", "KAMARDANGA", "BILASIPARA", "GAURIPUR", "GOLAKGANJ"]},
        {"district": "Dibrugarh", "coords": (27.4728, 94.9120), "place": "Bogibeel Rail-cum-Road Bridge & BCPL Lepetkata", "keywords": ["DIBRUGARH", "BOGIBEEL", "LEPETKATA", "CHABUA", "NAHARKATIA", "DULIAJAN"]},
        {"district": "Cachar", "coords": (24.8333, 92.7789), "place": "Silchar Multi-Modal Logistics Park", "keywords": ["SILCHAR", "CACHAR", "LAKHIPUR", "UDHARBOND", "KATIGORAH"]},
    ],
    "TELANGANA": [
        {"district": "Bhadradri Kothagudem", "coords": (17.5500, 80.6200), "place": "Jawahar Khani, Venkatesh Khani & Kothagudem Thermal", "keywords": ["KOTHAGUDEM", "JAWAHAR KHANI", "VENKATESH KHANI", "BHADRADRI", "YELLANDU", "PALWANCHA", "MANUGURU", "BHADRACHALAM", "DORNAKAL"]},
        {"district": "Mancherial", "coords": (18.8700, 79.4600), "place": "Kalyanikhani & Indaram Coal Mines", "keywords": ["KALYANIKHANI", "MANCHERIAL", "INDARAM", "BELLAMPALLI", "MANDAMARRI", "CHENNOOR", "NASPUR"]},
        {"district": "Kumuram Bheem Asifabad", "coords": (19.3600, 79.2900), "place": "Goleti Opencast Coal Mining Node", "keywords": ["GOLETI", "ASIFABAD", "KAGAZNAGAR", "REBBENA", "KUMURAM BHEEM"]},
        {"district": "Peddapalli", "coords": (18.7700, 79.5200), "place": "Godavarikhani & NTPC Ramagundam Super Thermal", "keywords": ["GODAVARIKHANI", "RAMAGUNDAM", "PEDDAPALLI", "SULTANABAD", "MANTHANI"]},
        {"district": "Jayashankar Bhupalpally", "coords": (18.4300, 79.8600), "place": "Kakatiyakhani Opencast Coal Project", "keywords": ["KAKATIYAKHANI", "BHUPALPALLY", "JAYASHANKAR", "CHITYAL", "REGONDA"]},
        {"district": "Sangareddy", "coords": (17.6193, 78.0814), "place": "IIT Hyderabad Permanent Campus & Zaheerabad Node", "keywords": ["SANGAREDDY", "KANDI", "ZAHEERABAD", "PATANCHERU", "BOLLARAM", "ISNAPUR", "MEDAK ROAD"]},
        {"district": "Yadadri Bhuvanagiri", "coords": (17.4728, 78.7894), "place": "AIIMS Bibinagar & Malkapur ATF Pipeline", "keywords": ["BIBINAGAR", "MALKAPUR", "YADADRI", "BHONGIR", "BHUVANAGIRI", "CHOUTUPPAL"]},
        {"district": "Hanamkonda", "coords": (18.0000, 79.5800), "place": "Kazipet Railway Manufacturing & Overhauling Unit", "keywords": ["KAZIPET", "HANAMKONDA", "WARANGAL", "HASANPARTHY"]},
        {"district": "Hyderabad", "coords": (17.3850, 78.4867), "place": "Hyderabad Metro & Urban Infrastructure", "keywords": ["HYDERABAD", "SECUNDERABAD", "CHARMINAR", "HITECH CITY", "GACHIBOWLI", "KUKATPALLY", "BEGUMPET"]},
    ],
    "CHHATTISGARH": [
        {"district": "Korba", "coords": (22.3595, 82.7501), "place": "Gevra, Dipka, Kusmunda Mega Coalfields (SECL)", "keywords": ["GEVRA", "DIPKA", "KUSMUNDA", "MANIKPUR", "KORBA", "DURGAPUR OCP", "KATGHORA", "HARDIBAZAR", "CHHURI"]},
        {"district": "Raigarh", "coords": (21.8974, 83.3950), "place": "Baroud, Pelma & Porda Chimtapani Coal Complex", "keywords": ["BAROUD", "PELMA", "PORDA", "CHIMTAPANI", "RAIGARH", "DHARAMJAIGARH", "GHARGHODA", "KHARSHIA", "SARANGARH"]},
        {"district": "Surajpur", "coords": (23.2200, 82.8600), "place": "Amera, Amgaon & Jagannathpur Coalfields", "keywords": ["AMERA", "AMGAON", "JAGANNATHPUR", "MAHAMAYA", "MADANNAGAR", "SURAJPUR", "BISHRAMPUR", "BHATGAON"]},
        {"district": "Koriya", "coords": (23.2600, 82.5500), "place": "Katkona Underground Coal Project", "keywords": ["KATKONA", "KORIYA", "KOREA", "BAIKUNTHPUR", "CHIRMIRI", "MANENDRAGARH"]},
        {"district": "Raipur", "coords": (21.2514, 81.6296), "place": "Swami Vivekananda Airport & Nava Raipur Smart City", "keywords": ["RAIPUR", "NAVA RAIPUR", "NARYANPUR", "TILDA", "ARANG", "MANDIR HASAUD"]},
        {"district": "Durg", "coords": (21.1900, 81.2800), "place": "Bhilai Steel Plant & IIT Bhilai Campus (Kutelabhata)", "keywords": ["BHILAI", "DURG", "KUTELABHATA", "CHARODA", "KUMHARI", "PATAN CG"]},
        {"district": "Bilaspur", "coords": (22.0797, 82.1409), "place": "SECL Headquarters & Bilaspur Railway Zone", "keywords": ["BILASPUR", "SECL", "BODRI", "KOTA CG", "TAKHTPUR", "MASTURI"]},
    ],
    "HARYANA": [
        {"district": "Mahendragarh", "coords": (27.9800, 76.1300), "place": "Nangal Chaudhary Integrated Multi-Modal Logistics Hub", "keywords": ["NANGAL CHAUDHARY", "MAHENDRAGARH", "NARNAUL", "ATELI", "KANINA"]},
        {"district": "Gurugram", "coords": (28.4595, 77.0266), "place": "Cyber City & Dwarka Expressway Haryana", "keywords": ["GURUGRAM", "GURGAON", "MANESAR", "CYBER CITY", "SOHNA", "DWARKA EXPRESSWAY HARYANA", "PATAUDI", "FARUKHNAGAR"]},
        {"district": "Faridabad", "coords": (28.4089, 77.3178), "place": "Faridabad Smart City & Industrial Node", "keywords": ["FARIDABAD", "BALLABGARH", "NEHARPAR", "BADKHAL"]},
        {"district": "Panipat", "coords": (29.3909, 76.9635), "place": "Panipat Refinery & Petrochemical Complex", "keywords": ["PANIPAT", "SAMALKHA", "REFINERY PANIPAT", "ISRANA", "MADLAUDA"]},
        {"district": "Sonipat", "coords": (28.9931, 77.0151), "place": "Kundli-Manesar-Palwal (KMP) Logistics Node", "keywords": ["SONIPAT", "KUNDLI", "RAI", "GANAUR", "KMP EXPRESSWAY", "GOHANA", "MURTHAL"]},
        {"district": "Rewari", "coords": (28.1800, 76.6200), "place": "Rewari DFC & Industrial Corridor", "keywords": ["REWARI", "BAWAL", "DHARUHERA", "KOSLI"]},
        {"district": "Hisar", "coords": (29.1500, 75.7200), "place": "Hisar International Airport Node", "keywords": ["HISAR", "HANSI", "BARWALA", "AGROHA"]},
        {"district": "Rohtak", "coords": (28.8900, 76.6000), "place": "Rohtak Industrial Model Township (IMT)", "keywords": ["ROHTAK", "SAMPLA", "MEHAM", "KALANAUR"]},
    ],
    "PUNJAB": [
        {"district": "Pathankot", "coords": (32.2689, 75.6499), "place": "City Gas Distribution Project at Pathankot", "keywords": ["PATHANKOT", "MADHOPUR", "SUJANPUR", "DHAR KALAN"]},
        {"district": "Fazilka", "coords": (30.4036, 74.0253), "place": "Relining of Rajasthan Feeder & Sirhind Feeder Canal", "keywords": ["SIRHIND FEEDER", "RAJASTHAN FEEDER", "FAZILKA", "ABOHAR", "JALALABAD PUNJAB"]},
        {"district": "Ludhiana", "coords": (30.9010, 75.8573), "place": "Ludhiana Freight Logistics & Smart City", "keywords": ["LUDHIANA", "SAHNEWAL", "KHANNA", "DORAHI", "JAGRAON", "SAMRALA"]},
        {"district": "Amritsar", "coords": (31.6340, 74.8723), "place": "Sri Guru Ram Dass Jee International Airport & Attari", "keywords": ["AMRITSAR", "ATTARI", "RAJA SANSI", "BEAS", "MAJITHA", "AJNALA"]},
        {"district": "Bathinda", "coords": (30.2110, 74.9455), "place": "Bathinda Refinery (HMEL) & AIIMS", "keywords": ["BATHINDA", "TALWANDI SABO", "RAMPURA PHUL", "MAUR"]},
        {"district": "Jalandhar", "coords": (31.3260, 75.5762), "place": "Jalandhar Smart City & Sports Industrial Hub", "keywords": ["JALANDHAR", "ADAMPUR", "PHAGWARA CORRIDOR", "NAKODAR", "KARTARPUR"]},
        {"district": "SAS Nagar", "coords": (30.6942, 76.7179), "place": "Mohali IT City & Chandigarh International Airport", "keywords": ["MOHALI", "SAS NAGAR", "KHARAR", "DERABASSI", "ZIRAKPUR", "NEW CHANDIGARH"]},
    ],
    "DELHI": [
        {"district": "South Delhi", "coords": (28.5355, 77.2500), "place": "DND Maharani Bagh - Jaitpur Pushta Road NH-148NA", "keywords": ["DND", "MAHARANI BAGH", "JAITPUR", "PUSHTA", "NH-148NA", "OKHLA", "BADARPUR", "NEHRU PLACE", "SAKET", "HAUZ KHAS"]},
        {"district": "South West Delhi", "coords": (28.5800, 77.0500), "place": "Dwarka Expressway, UER-II & IGI Airport Terminal", "keywords": ["DWARKA", "UER-II", "IGI AIRPORT", "PALAM", "BIJWASAN", "VASANT KUNJ", "NAJAFGARH"]},
        {"district": "New Delhi", "coords": (28.6139, 77.2090), "place": "Central Vista Executive Enclave & Ministries", "keywords": ["CENTRAL VISTA", "NEW DELHI", "PRAGATI MAIDAN", "CONNAUGHT PLACE", "MINISTRIES", "DELHI METRO", "BHIKAJI CAMA"]},
        {"district": "East Delhi", "coords": (28.6279, 77.2954), "place": "East Delhi RRTS & Multi-Modal Hub", "keywords": ["AKSHARDHAM", "EAST DELHI", "MAYUR VIHAR", "ANAND VIHAR", "LAXMI NAGAR", "SHAKARPUR"]},
        {"district": "North Delhi", "coords": (28.7000, 77.1500), "place": "Mukarba Chowk & Northern Rail Corridor", "keywords": ["NORTH DELHI", "BURARI", "ALIPUR", "MUKARBA", "CIVIL LINES"]},
    ],
    "JAMMU AND KASHMIR": [
        {"district": "Reasi", "coords": (33.0800, 74.8300), "place": "Katra Railway Station & Chenab River Bridge Node", "keywords": ["REASI", "KATRA", "CHENAB BRIDGE", "VAISHNO DEVI", "SALAL"]},
        {"district": "Ramban", "coords": (33.2400, 75.2400), "place": "Banihal Qazigund Tunnel & USBRL Corridor", "keywords": ["RAMBAN", "BANIHAL", "BATOTE", "GOOL", "DIGDOL", "MAKARKOOT"]},
        {"district": "Jammu", "coords": (32.7266, 74.8570), "place": "Jammu Civil Airport & Ring Road", "keywords": ["JAMMU", "AKHNOOR", "RS PURA", "BISHNAH", "NAGROTA", "VIJAYPUR JAMMU"]},
        {"district": "Srinagar", "coords": (34.0837, 74.7973), "place": "Srinagar Smart City & Airport Terminal", "keywords": ["SRINAGAR", "DAL LAKE", "PANTHA CHOWK", "NOWGAM", "BATAMALOO", "LAL CHOWK"]},
        {"district": "Udhampur", "coords": (32.9200, 75.1400), "place": "Udhampur Rail & Strategic Command Hub", "keywords": ["UDHAMPUR", "CHENANI", "NASHRI", "RAMNAGAR JK"]},
        {"district": "Kishtwar", "coords": (33.3100, 75.7600), "place": "Pakal Dul & Kiru Hydroelectric Projects", "keywords": ["KISHTWAR", "PAKAL DUL", "KIRU", "RATHLE", "KWAR"]},
    ],
    "UTTARAKHAND": [
        {"district": "Dehradun", "coords": (30.3165, 78.0322), "place": "Dehradun Smart City & Rishikesh-Karnaprayag Rail", "keywords": ["DEHRADUN", "RISHIKESH", "JOLLY GRANT", "VIKASNAGAR", "MUSSOORIE"]},
        {"district": "Haridwar", "coords": (29.9457, 78.1642), "place": "Haridwar Ring Road & SIDCUL Industrial Area", "keywords": ["HARIDWAR", "ROORKEE", "SIDCUL", "BHAGWANPUR", "LAKSAR"]},
        {"district": "Tehri Garhwal", "coords": (30.3800, 78.4800), "place": "Tehri Pumped Storage Plant (THDC)", "keywords": ["TEHRI", "KOTESHWAR", "NEW TEHRI", "CHAMBA UK", "NARENDRA NAGAR"]},
        {"district": "Udham Singh Nagar", "coords": (28.9800, 79.4000), "place": "Pantnagar Airport & Industrial Node", "keywords": ["UDHAM SINGH NAGAR", "PANTNAGAR", "RUDRAPUR", "KASHIPUR", "KICHHA", "SITARGANJ"]},
    ],
    "HIMACHAL PRADESH": [
        {"district": "Shimla", "coords": (31.1048, 77.1734), "place": "Shimla Smart City & World Bank Road Upgrade", "keywords": ["SHIMLA", "JUBBARHATTI", "THEOG", "RAMPUR HP", "ROHRU"]},
        {"district": "Solan", "coords": (30.9084, 77.0999), "place": "Baddi-Barotiwala-Nalagarh (BBN) Pharma Hub", "keywords": ["SOLAN", "BADDI", "NALAGARH", "PARWANOO", "KANDAGHAT"]},
        {"district": "Kullu", "coords": (31.9579, 77.1095), "place": "Manali Tourism Highway & Atal Tunnel North-South", "keywords": ["KULLU", "MANALI", "ATAL TUNNEL", "BHUNTAR", "BANJAR"]},
        {"district": "Mandi", "coords": (31.7087, 76.9320), "place": "IIT Mandi Permanent Campus & Kiratpur-Nerchowk", "keywords": ["MANDI", "KAMAND", "NERCHOWK", "SUNDERNAGAR", "SARKAGHAT"]},
        {"district": "Bilaspur", "coords": (31.3300, 76.7600), "place": "AIIMS Bilaspur (Kothipura) & Bhanupali Rail", "keywords": ["BILASPUR HP", "KOTHIPURA", "BHANUPALI", "GHUMARWIN", "KOLDAM"]},
    ],
    "KERALA": [
        {"district": "Ernakulam", "coords": (9.9816, 76.2999), "place": "Kochi Metro Phase 2 & BPCL Kochi Refinery (MSVI)", "keywords": ["ERNAKULAM", "KOCHI", "COCHIN", "ALUVA", "KAKKANAD", "AMBALAMUGAL", "WILLINGDON", "KALAMASSERY"]},
        {"district": "Thiruvananthapuram", "coords": (8.5241, 76.9366), "place": "Vizhinjam International Transshipment Deepwater Port", "keywords": ["THIRUVANANTHAPURAM", "TRIVANDRUM", "VIZHINJAM", "KAZHAKOOTTAM", "NEYYATTINKARA", "ATTINGAL"]},
        {"district": "Palakkad", "coords": (10.7867, 76.6548), "place": "IIT Palakkad Permanent Campus (Kanjikode)", "keywords": ["PALAKKAD", "KANJIKODE", "OTTAPALAM", "SHORANUR", "CHITTUR"]},
        {"district": "Kozhikode", "coords": (11.2588, 75.7804), "place": "Kozhikode Smart City & Calicut Airport", "keywords": ["KOZHIKODE", "CALICUT", "FEROKE", "VADAKARA", "KOYILANDY"]},
    ],
    "GOA": [
        {"district": "North Goa", "coords": (15.7200, 73.8600), "place": "Manohar International Airport, Mopa", "keywords": ["MOPA", "NORTH GOA", "PANAJI", "MAPUSA", "PERNEM", "BICHOLIM"]},
        {"district": "South Goa", "coords": (15.3900, 73.8100), "place": "Mormugao Port & Dabolim Airport Hub", "keywords": ["MORMUGAO", "SOUTH GOA", "VASCO", "MARGAO", "DABOLIM", "QUEPEM", "CANACONA"]},
    ],
    "SIKKIM": [
        {"district": "Pakyong", "coords": (27.2340, 88.5878), "place": "Pakyong Greenfield Airport & NH-717A", "keywords": ["PAKYONG", "RHENOCK", "MENLA", "RONGLI", "CHOCHENPHERI", "ROLEP", "NH-717"]},
        {"district": "Gangtok", "coords": (27.3389, 88.6065), "place": "Gangtok Smart City & Sivok-Rangpo Rail", "keywords": ["GANGTOK", "EAST SIKKIM", "RANIPOOL", "BURTUK", "KHAMDONG", "TETELIA", "SIVOK-RANGPO"]},
        {"district": "Namchi", "coords": (27.1667, 88.3500), "place": "Namchi & Yangang Infrastructure Hub", "keywords": ["NAMCHI", "SOUTH SIKKIM", "YANGANG", "RABANGLA", "RANGIT", "JPCL"]},
        {"district": "Mangan", "coords": (27.5000, 88.5300), "place": "Teesta-VI Hydroelectric Power Plant", "keywords": ["MANGAN", "NORTH SIKKIM", "TEESTA", "CHUNGTHANG", "LACHEN", "LACHUNG"]},
    ],
    "TRIPURA": [
        {"district": "West Tripura", "coords": (23.8315, 91.2868), "place": "Agartala Smart City & Agartala Airport", "keywords": ["AGARTALA", "WEST TRIPURA", "MBB AIRPORT", "BADHARGHAT", "RANIRBAZAR"]},
        {"district": "South Tripura", "coords": (23.1600, 91.4500), "place": "Belonia & Sabroom Integrated Check Post (ICP)", "keywords": ["SABROOM", "BELONIA", "SOUTH TRIPURA", "FENI RIVER", "MAITRI SETU", "SHANTIRBAZAR"]},
        {"district": "Gomati", "coords": (23.5300, 91.4900), "place": "Udaipur & Palatana Thermal Plant", "keywords": ["GOMATI", "UDAIPUR TRIPURA", "PALATANA", "AMARPUR"]},
    ],
    "MANIPUR": [
        {"district": "Imphal West", "coords": (24.8170, 93.9368), "place": "Bir Tikendrajit International Airport & Smart City", "keywords": ["IMPHAL WEST", "IMPHAL", "TULIHAL", "LAMPHELPAT", "LANGJING"]},
        {"district": "Tengnoupal", "coords": (24.2500, 94.3000), "place": "Moreh Integrated Check Post (ICP) Border Corridor", "keywords": ["MOREH", "TENGNOUPAL", "INDO-MYANMAR", "PURUM"]},
        {"district": "Senapati", "coords": (25.2600, 94.0100), "place": "Senapati Highway Corridor NH-2", "keywords": ["SENAPATI", "MARAM", "MAWBI", "KANGPOKPI"]},
        {"district": "Tamenglong", "coords": (24.9800, 93.4900), "place": "Jiribam-Imphal Railway Line & Makru Bridge", "keywords": ["TAMENGLONG", "JIRIBAM", "MAKRU", "NONGEYBUNG"]},
        {"district": "Churachandpur", "coords": (24.3300, 93.6700), "place": "Churachandpur Highway & Water Project", "keywords": ["CHURACHANDPUR", "LAMKA", "TUIVAL"]},
    ],
    "MIZORAM": [
        {"district": "Aizawl", "coords": (23.7271, 92.7176), "place": "Bairabi-Sairang Rail Terminal & Lengpui", "keywords": ["AIZAWL", "SAIRANG", "LENGPUI", "BAIRABI", "DURTLANG"]},
        {"district": "Kolasib", "coords": (24.2250, 92.6780), "place": "Chhimluang-Kolasib & Kolasib-Sethawn NH-6 Package", "keywords": ["KOLASIB", "CHHIMLUANG", "SETHAWN", "VAIRENGTE", "BILKHAWTHLIR", "NH-306"]},
        {"district": "Lunglei", "coords": (22.8800, 92.7300), "place": "Lunglei Highway & Regional Corridor", "keywords": ["LUNGLEI", "TUALTE", "HNAHTHIAL"]},
        {"district": "Champhai", "coords": (23.4700, 93.3200), "place": "Zokhawthar Indo-Myanmar Trade Corridor", "keywords": ["CHAMPHAI", "ZOKHAWTHAR", "KHAWZAWL"]},
    ],
    "NAGALAND": [
        {"district": "Dimapur", "coords": (25.9068, 93.7271), "place": "Dimapur Airport & Dimapur-Kohima Rail Link", "keywords": ["DIMAPUR", "ZUBZA", "CHUMOUKEDIMA", "MEDZIPHEMA", "PURANA BAZAR"]},
        {"district": "Kohima", "coords": (25.6751, 94.1086), "place": "Kohima Smart City & Medical College", "keywords": ["KOHIMA", "JAPFU", "NORTH KOHIMA", "TSEMINYU"]},
        {"district": "Mokokchung", "coords": (26.3200, 94.5200), "place": "Mokokchung Highway & Education Node", "keywords": ["MOKOKCHUNG", "CHANGTONGYA", "TULI"]},
    ],
    "MEGHALAYA": [
        {"district": "East Khasi Hills", "coords": (25.5788, 91.8933), "place": "Shillong Airport (Umroi) & NEIGRIHMS", "keywords": ["SHILLONG", "UMROI", "NEIGRIHMS", "EAST KHASI HILLS", "MAWLYNNOUNG", "CHERAPUNJI"]},
        {"district": "Ri-Bhoi", "coords": (25.9000, 91.8800), "place": "Nongpoh & Byrnihat Industrial Corridor", "keywords": ["RI-BHOI", "NONGPOH", "BYRNIHAT", "UMIAM"]},
        {"district": "West Garo Hills", "coords": (25.5100, 90.2200), "place": "Tura Smart Town & Regional Hub", "keywords": ["TURA", "WEST GARO HILLS", "DAWKI", "BAJENGDOBA"]},
    ],
    "ARUNACHAL PRADESH": [
        {"district": "Papum Pare", "coords": (27.0844, 93.6053), "place": "Donyi Polo Airport Itanagar (Hollongi)", "keywords": ["ITANAGAR", "HOLLONGI", "PAPUM PARE", "NAHARLAGUN", "BANDERDEWA"]},
        {"district": "Lower Dibang Valley", "coords": (28.1400, 95.8300), "place": "Dibang Multipurpose Hydroelectric Project (2880 MW)", "keywords": ["DIBANG", "LOWER DIBANG", "ROING", "DAMBUK"]},
        {"district": "West Kameng", "coords": (27.2600, 92.4200), "place": "Kameng Hydroelectric Project (600 MW)", "keywords": ["KAMENG", "WEST KAMENG", "BOMDILA", "DIRANG", "BHALUKPONG"]},
        {"district": "Tawang", "coords": (27.5800, 91.8600), "place": "Sela Tunnel Strategic Border Link", "keywords": ["SELA TUNNEL", "TAWANG", "JANG", "LUM LA"]},
        {"district": "East Siang", "coords": (28.0600, 95.3300), "place": "Pasighat Airport & Highway Corridor", "keywords": ["PASIGHAT", "EAST SIANG", "RUKTIN", "MBO"]},
    ],
    "LADAKH": [
        {"district": "Leh", "coords": (34.1526, 77.5771), "place": "Kushok Bakula Rimpochee Airport Terminal", "keywords": ["LEH", "LADAKH", "SHEY", "THIKSEY", "NIMOO", "KHALTSI"]},
        {"district": "Kargil", "coords": (34.5539, 76.1311), "place": "Zojila Tunnel Strategic Highway Link", "keywords": ["KARGIL", "ZOJILA", "DRAS", "SANKOO", "ZANSKAR"]},
    ],
    "ANDAMAN & NICOBAR": [
        {"district": "South Andaman", "coords": (11.6234, 92.7265), "place": "Port Blair International Terminal & Great Nicobar Node", "keywords": ["PORT BLAIR", "SOUTH ANDAMAN", "GARCHARAMA", "BAMBOO FLAT", "GREAT NICOBAR"]},
        {"district": "North & Middle Andaman", "coords": (12.9200, 92.9200), "place": "Mayabunder & Diglipur Highway Corridor", "keywords": ["MAYABUNDER", "DIGLIPUR", "RANGAT"]},
    ],
    "DADRA & NAGAR HAVELI AND DAMAN & DIU": [
        {"district": "Daman", "coords": (20.4283, 72.8397), "place": "Daman Coastal & Industrial Hub", "keywords": ["DAMAN", "MOTI DAMAN", "NANI DAMAN"]},
        {"district": "Dadra & Nagar Haveli", "coords": (20.2700, 73.0100), "place": "Silvassa Smart City & Industrial Node", "keywords": ["SILVASSA", "DADRA", "NAGAR HAVELI"]},
    ],
    "CHANDIGARH": [
        {"district": "Chandigarh", "coords": (30.7333, 76.7794), "place": "Chandigarh Capitol Complex & Smart City", "keywords": ["CHANDIGARH", "TRIBUNE", "SECTOR 17", "MANIMAJRA"]},
    ],
    "PUDUCHERRY": [
        {"district": "Puducherry", "coords": (11.9416, 79.8083), "place": "Puducherry Port & Smart City Infrastructure", "keywords": ["PUDUCHERRY", "PONDICHERRY", "KARAIKAL", "MAHE", "YANAM"]},
    ],
    "LAKSHADWEEP": [
        {"district": "Lakshadweep", "coords": (10.5667, 72.6417), "place": "Agatti Airport & Kavaratti Island Infrastructure", "keywords": ["AGATTI", "KAVARATTI", "LAKSHADWEEP", "AMINI", "ANDROTH"]},
    ]
}

# Merge all additional official districts and keywords
try:
    from scripts.expand_gazetteer_data import ADDITIONAL_DISTRICTS
    for st, nds in ADDITIONAL_DISTRICTS.items():
        if st not in AUTHORITATIVE_GAZETTEER:
            AUTHORITATIVE_GAZETTEER[st] = []
        existing_dists = {d["district"].upper(): d for d in AUTHORITATIVE_GAZETTEER[st]}
        for nd in nds:
            u_name = nd["district"].upper()
            if u_name in existing_dists:
                cur = existing_dists[u_name]
                cur_kws = set(cur.get("keywords", []))
                for kw in nd.get("keywords", []):
                    if kw not in cur_kws:
                        cur.setdefault("keywords", []).append(kw)
            else:
                AUTHORITATIVE_GAZETTEER[st].append(nd)
except Exception as _e:
    pass

# Ensure Kutch has SAMAKHIALI and GANDHIDHAM
if "GUJARAT" in AUTHORITATIVE_GAZETTEER:
    for d in AUTHORITATIVE_GAZETTEER["GUJARAT"]:
        if d["district"] == "Kutch":
            for extra_kw in ["SAMAKHIALI", "GANDHIDHAM", "SAMAKHIYALI"]:
                if extra_kw not in d["keywords"]:
                    d["keywords"].append(extra_kw)

total_districts = sum(len(v) for v in AUTHORITATIVE_GAZETTEER.values())
print(f"[INDIA GAZETTEER] Loaded comprehensive gazetteer with {len(AUTHORITATIVE_GAZETTEER)} state categories ({total_districts} official districts).")
