"""
scripts/verified_facility_overrides.py
======================================
Authoritative Facility & Site Geolocation Overrides (April 2026 Dataset)
Precision corrections mapping projects to actual facility, stretch, district and state.
"""

VERIFIED_FACILITY_OVERRIDES = {
    # ── Maharashtra Corridor & Local Project Corrections ─────────────────────
    "615917": { "district": "Chandrapur", "place": "Gaurideep / Gauri Central OCP, Majri Area", "coords": (19.8520, 79.3412), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "615918": { "district": "Nagpur", "place": "Bhanegaon Open Cast Mine, Saoner-Kamptee", "coords": (21.3250, 79.1620), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "617225": { "district": "Pune", "place": "PCMC to Nigdi Metro Extension Corridor", "coords": (18.6485, 73.7869), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "701745": { "district": "Thane", "place": "Digha Gaon Suburban Station, Thane-Airoli Link", "coords": (19.1820, 72.9980), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "702637": { "district": "Mumbai Suburban", "place": "BKC Metro Operations Centre & Junction, Line 3", "coords": (19.0607, 72.8644), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "604833": { "district": "Mumbai Suburban", "place": "Andheri Residential Development Site", "coords": (19.1197, 72.8464), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "616933": { "district": "Mumbai Suburban", "place": "BPCL Mumbai Refinery Lube Plant, Mahul, Chembur", "coords": (19.0062, 72.8945), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "619223": { "district": "Mumbai Suburban", "place": "HPCL Mumbai Refinery PRFCC Unit, Mahul, Chembur", "coords": (19.0090, 72.8980), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "709760": { "district": "Mumbai Suburban", "place": "HPCL Mumbai Refinery TDAE Unit, Mahul, Chembur", "coords": (19.0040, 72.8920), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "616691": { "district": "Mumbai Suburban", "place": "ESIC Model Hospital & PGIMSR, Andheri East", "coords": (19.1245, 72.8682), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "617201": { "district": "Chandrapur", "place": "Gondia - Balharshah [Chanda Fort] Railway Doubling", "coords": (19.9500, 79.3000), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "613015": { "district": "Mumbai City", "place": "Chhatrapati Shivaji Maharaj Terminus [CSMT] Complex, Fort", "coords": (18.9400, 72.8353), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "706779": { "district": "Mumbai Suburban", "place": "MUTP-II Kurla-CST 5th & 6th Rail Corridor, Kurla", "coords": (19.0660, 72.8790), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "706780": { "district": "Thane", "place": "MUTP-3A Suburban Rail Expansion, Diva-Kalyan", "coords": (19.2000, 73.0000), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "706781": { "district": "Palghar", "place": "MUTP-3 Quadrupling Corridor, Virar-Palghar-Dahanu", "coords": (19.5500, 72.8000), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "617944": { "district": "Ratnagiri", "place": "Kashedi Ghat Twin-Tube Tunnel, NH-66, Poladpur-Khed", "coords": (17.9250, 73.4750), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "617945": { "district": "Raigad", "place": "NH-66 Mangaon-Indapur Bypass Section", "coords": (18.2500, 73.2800), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618469": { "district": "Palghar", "place": "Vadodara-Mumbai Expressway Pkg-13, Shirsad - Masvan", "coords": (19.6100, 72.8400), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618470": { "district": "Thane", "place": "Vadodara-Mumbai Expressway Spur Pkg-14, Shirsad - Akloli", "coords": (19.4900, 73.0400), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618471": { "district": "Thane", "place": "Vadodara-Mumbai Expressway Spur Pkg-15, Akloli - Amne", "coords": (19.3400, 73.1200), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618472": { "district": "Thane", "place": "Vadodara-Mumbai Expressway Spur Pkg-16, Amne - Bhoj", "coords": (19.1200, 73.2200), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618473": { "district": "Raigad", "place": "Vadodara-Mumbai Expressway Spur Pkg-17, Bhoj - Morbe", "coords": (18.9200, 73.1900), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618766": { "district": "Ahmednagar", "place": "NH-160 Savali Vihir to Ahmednagar Bypass Corridor", "coords": (19.4500, 74.6500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618939": { "district": "Chandrapur", "place": "Gadchandur Town Flyover & ROB, NH-353B", "coords": (19.7359, 79.1746), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "619198": { "district": "Palghar", "place": "Vadodara-Mumbai Expressway Pkg-12, Masvan - Ganjad", "coords": (19.8200, 72.8500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "615919": { "district": "Yavatmal", "place": "Mungoli Nirguda Deep OCP, Wani North Area", "coords": (19.9800, 79.0800), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "617278": { "district": "Chandrapur", "place": "Kolarpimpri Expansion OCP, Majri Area", "coords": (19.9500, 79.1500), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "617947": { "district": "Ratnagiri", "place": "NH-66 Arawali - Kante Section, Ratnagiri", "coords": (17.3500, 73.5500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618154": { "district": "Beed", "place": "NH-548D Jamkhed to Sautada Section, Beed", "coords": (18.8900, 75.3500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "400105": { "district": "Satara", "place": "Urmodi Dam & Irrigation Project, Satara", "coords": (17.6500, 73.9500), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "400107": { "district": "Dhule", "place": "Sulwade Jamphal Kanoli Lift Irrigation, Tapi River, Dhule", "coords": (21.3200, 74.8800), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "701383": { "district": "Jalgaon", "place": "Waghur Dam & Reservoir Project, Jalgaon", "coords": (20.9300, 75.7200), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "705735": { "district": "Dharashiv", "place": "Solapur - Tuljapur - Dharashiv Rail Line", "coords": (18.0100, 76.0700), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "617215": { "district": "Parbhani", "place": "Parbhani - Parli Vaijanath Line Doubling", "coords": (19.2600, 76.7700), "source": "verified_facility", "level": "project_site", "confidence": "high" },

    # ── Jammu and Kashmir Projects ────────────────────────────────────────────
    "701167": { "district": "Pulwama", "place": "AIIMS Awantipora Medical Campus, Pulwama", "coords": (33.9189, 74.9967), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "618038": { "district": "Shopian", "place": "Shopian Bypass Corridor, NH-444", "coords": (33.7196, 74.8322), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618203": { "district": "Baramulla", "place": "Pattan Bypass 4-Lane Section, NH-1", "coords": (34.1610, 74.5528), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618206": { "district": "Kupwara", "place": "Rafiabad - Kupwara - Chowkibal Highway Corridor", "coords": (34.4250, 74.2500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618494": { "district": "Kathua", "place": "Delhi-Amritsar-Katra Expressway Pkg-15, Hiranagar", "coords": (32.4500, 75.2700), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618496": { "district": "Samba", "place": "Delhi-Amritsar-Katra Expressway Pkg-16, Vijaypur - Jakh", "coords": (32.5600, 75.0200), "source": "verified_facility", "level": "project_site", "confidence": "high" },

    # ── Bihar Projects ────────────────────────────────────────────────────────
    "618582": { "district": "Kishanganj", "place": "Galgalia - Bahadurganj Section, NH-327E", "coords": (26.1000, 87.9000), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618583": { "district": "Araria", "place": "Bahadurganj - Araria Section, NH-327E", "coords": (26.1500, 87.5200), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "705450": { "district": "Araria", "place": "Jogbani - Biratnagar Rail Link, Jogbani", "coords": (26.3000, 87.2700), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618839": { "district": "Begusarai", "place": "6-Lane Ganga Bridge at Simaria, Begusarai", "coords": (25.4300, 85.9700), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "617239": { "district": "Sitamarhi", "place": "Raxaul - Sitamarhi - Darbhanga Doubling", "coords": (26.5900, 85.4900), "source": "verified_facility", "level": "project_site", "confidence": "high" },

    # ── Andhra Pradesh Projects ───────────────────────────────────────────────
    "618101": { "district": "Palnadu", "place": "NH-167AG Kondamodu - Perecherla Section, Palnadu", "coords": (16.3200, 80.3500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618526": { "district": "Eluru", "place": "NH-16 Gundugolanu - Kalaparru Bypass Section, Eluru", "coords": (16.7100, 81.1000), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618475": { "district": "Chittoor", "place": "Bangalore-Chennai Expressway Pkg-2, Baireddypalli", "coords": (13.1200, 78.6500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618713": { "district": "YSR Kadapa", "place": "Greenfield Highway Yerragudipadu Section", "coords": (14.8800, 78.5000), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "619111": { "district": "Vizianagaram", "place": "NH-130CD Jakkuva - Korlam Section", "coords": (18.5200, 83.4500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618579": { "district": "Anakapalli", "place": "NH-16 Anandapuram - Pendurthi - Anakapalli 6-Lane", "coords": (17.7000, 83.0000), "source": "verified_facility", "level": "project_site", "confidence": "high" },

    # ── Uttar Pradesh Projects ────────────────────────────────────────────────
    "705918": { "district": "Aligarh", "place": "Aligarh - Harduaganj Railway Flyover, Aligarh", "coords": (27.9100, 78.1000), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "701408": { "district": "Bijnor", "place": "Madhya Ganga Canal Barrage & Network, Bijnor", "coords": (29.3500, 78.1500), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "618970": { "district": "Baghpat", "place": "Greenfield Highway Lohadda - Karaunda Section, Baraut", "coords": (29.1500, 77.2500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618248": { "district": "Ambedkar Nagar", "place": "NH-135A Jaunpur - Akbarpur 4-Lane Section, Akbarpur", "coords": (26.4300, 82.5400), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618249": { "district": "Jaunpur", "place": "NH-135A Jaunpur Bypass Section, Jaunpur", "coords": (25.7500, 82.6800), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618911": { "district": "Rampur", "place": "NH-109 Rampur - Rudrapur Greenfield Spur, Rampur", "coords": (28.8500, 79.0500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618854": { "district": "Amethi", "place": "Raebareli - Jagdishpur Corridor & Bypass, Amethi", "coords": (26.4700, 81.6300), "source": "verified_facility", "level": "project_site", "confidence": "high" },

    # ── Other State Corrections ───────────────────────────────────────────────
    "701668": { "district": "Palakkad", "place": "NICDC Palakkad Industrial Smart City Node, Pudussery", "coords": (10.8100, 76.7500), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "619183": { "district": "Daman", "place": "Daman Coastal Ring Road Widening, Daman", "coords": (20.4100, 72.8400), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618890": { "district": "Hamirpur", "place": "Hamirpur Bypass, NH-3/NH-103, Hamirpur", "coords": (31.6800, 76.5200), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618888": { "district": "Hamirpur", "place": "Hamirpur Highway Corridor, Hamirpur", "coords": (31.7000, 76.5400), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618231": { "district": "Hamirpur", "place": "Hamirpur - Awah Devi Section, Hamirpur", "coords": (31.7200, 76.5700), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "400006": { "district": "Jharsuguda", "place": "Jharsuguda - Barpali - Sardega Coal Rail Line", "coords": (21.8500, 83.9200), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618957": { "district": "Korba", "place": "Champa - Korba 4-Lane Highway Corridor, Korba", "coords": (22.3500, 82.6800), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "619167": { "district": "Korba", "place": "Pathrapalli - Katghora Highway Section, Korba", "coords": (22.5000, 82.5500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "619074": { "district": "Krishnagiri", "place": "Krishnagiri - Walajahpet 6-Lane Expressway Corridor", "coords": (12.5200, 78.2200), "source": "verified_facility", "level": "project_site", "confidence": "high" },

    # ── Multi-State / Pan-India Authentic Waypoints ───────────────────────────
    "602096": { "district": "Dhemaji", "place": "Subansiri Lower Hydroelectric Project, Gerukamukh", "coords": (27.5500, 94.2600), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "400369": { "district": "Sonbhadra", "place": "Bina - Kakri Coal Mine Complex, NCL", "coords": (24.1800, 82.7800), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "615183": { "district": "Sonbhadra", "place": "Khadia OCP Coal Mine, NCL", "coords": (24.1300, 82.7200), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "617806": { "district": "Ananthapuramu", "place": "Ananthapuramu REZ Transmission Substation", "coords": (14.6819, 77.6007), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "617185": { "district": "Kurnool", "place": "Kurnool-IV REZ Transmission Substation", "coords": (15.8281, 78.0373), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "615347": { "district": "Kutch", "place": "Khavda Renewable Energy Park Substation, Kutch", "coords": (23.8500, 69.7500), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "615339": { "district": "Bikaner", "place": "Bikaner REZ Phase-IV Substation Complex, Bikaner", "coords": (28.0176, 73.3119), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "615340": { "district": "Bhiwani", "place": "Siwani 765kV Inter-State Transmission Substation, Bhiwani", "coords": (28.9100, 75.6200), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "705428": { "district": "Bilaspur", "place": "Bhanupalli - Bilaspur - Beri Rail Link, Bilaspur", "coords": (31.3300, 76.6000), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618935": { "district": "Ambala", "place": "Ambala - Kala Amb 4-Lane Highway, Ambala", "coords": (30.3782, 76.7767), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "619093": { "district": "Ambala", "place": "Ismailabad - Ambala 4-Lane Corridor, NH-152, Ambala", "coords": (30.3200, 76.8100), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "619134": { "district": "SAS Nagar", "place": "Ambala - Chandigarh Greenfield Expressway Section", "coords": (30.5500, 76.7800), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "619291": { "district": "Sirmaur", "place": "NH-07 Paonta Sahib to Mednipur 4-Lane Section, Sirmaur", "coords": (30.4400, 77.6200), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618941": { "district": "Chandrapur", "place": "NH-930D Bamni - Rajura - Warur Section, Chandrapur", "coords": (19.7800, 79.3600), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618747": { "district": "Khammam", "place": "Khammam - Devarapalle Greenfield Highway Pkg-3, Khammam", "coords": (17.2500, 80.1500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618951": { "district": "Palamu", "place": "NH-98 Hariharganj - Parwa Mode Section, Palamu", "coords": (24.5200, 84.1000), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "619078": { "district": "Hazaribagh", "place": "NH-2 Chordaha - Gorhar 6-Lane Section, Chouparan", "coords": (24.3800, 85.2500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618676": { "district": "Nabarangpur", "place": "NH-130CD Dhanara - Hatibena 6-Lane Section, Nabarangpur", "coords": (19.3500, 82.4200), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618681": { "district": "Vizianagaram", "place": "NH-130CD Aluru - Jakkuva 6-Lane Section, Vizianagaram", "coords": (18.6000, 83.3500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618634": { "district": "Tiruvallur", "place": "Veera Kaveri Raja Puram to Pondavakkam 6-Lane Section", "coords": (13.3500, 79.9500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618771": { "district": "Chittoor", "place": "NH-716 Varadharajula to Kumarajapet 6-Lane Section", "coords": (13.2500, 79.3500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "618772": { "district": "Tiruvallur", "place": "Kumarajapet to Veera Kaveri Raja Puram Section", "coords": (13.3000, 79.7500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "617390": { "district": "Sundargarh", "place": "Sardega - Bhalumuda Coal Railway Line, Sundargarh", "coords": (21.9500, 83.7500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "616588": { "district": "Mayurbhanj", "place": "Buramara - Chakulia New Rail Line, Mayurbhanj", "coords": (22.1500, 86.7200), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "616699": { "district": "Aurangabad", "place": "Son Nagar - Andal Multi-Tracking Rail Corridor", "coords": (24.7500, 84.1800), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "616857": { "district": "Nalgonda", "place": "Motumari - Vishnupuram Rail Line Doubling", "coords": (16.8500, 79.6200), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "617214": { "district": "Guntur", "place": "Errupalem - Amaravati - Namburu Rail Link", "coords": (16.5100, 80.5200), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "701565": { "district": "Varanasi", "place": "National Waterway-1 Multi-Modal Terminal, Varanasi", "coords": (25.3200, 83.0500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "701346": { "district": "Kamrup Metropolitan", "place": "North East Natural Gas Pipeline Grid Hub, Guwahati", "coords": (26.1800, 91.7500), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "701338": { "district": "Pune", "place": "MNGL City Gas Distribution Network, Pune", "coords": (18.5300, 73.8400), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "400301": { "district": "Coimbatore", "place": "Irugur - Devangonthi Petroleum Pipeline Terminal, Irugur", "coords": (11.0200, 77.0600), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "705237": { "district": "Vadodara", "place": "Western DFC Heavy Freight Corridor, Vadodara Feeder Node", "coords": (22.3500, 73.2000), "source": "verified_facility", "level": "project_site", "confidence": "high" },
    "607709": { "district": "East Khasi Hills", "place": "NERPSIP Power System Control Hub, Shillong", "coords": (25.5788, 91.8933), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "705298": { "district": "New Delhi", "place": "Northern Railway Central Surveillance Centre, Baroda House", "coords": (28.6180, 77.2150), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "400013": { "district": "New Delhi", "place": "Universal Service Obligation Fund Headquarters, Sanchar Bhawan", "coords": (28.6220, 77.2140), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "701593": { "district": "New Delhi", "place": "BSNL 4G National Operations Command, Janpath", "coords": (28.6240, 77.2190), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "706775": { "district": "New Delhi", "place": "BharatNet National Broadband Mission Centre, C-DoT Campus", "coords": (28.5080, 77.1550), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "709856": { "district": "New Delhi", "place": "BSNL MAAN National Network Operations Centre, Okhla", "coords": (28.5350, 77.2750), "source": "verified_facility", "level": "facility", "confidence": "high" },
    "709857": { "district": "New Delhi", "place": "BSNL 4G Phase IX.2 National Project Command, New Delhi", "coords": (28.6280, 77.2180), "source": "verified_facility", "level": "facility", "confidence": "high" },
}
